### ISSUE TITLE
Running multiple instances of the same model simultaneously

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#1015]
What I'm talking about here is running the same model (i.e. same encoders, gains, biases, decoders, etc.) with multiple inputs simultaneously (you can think of this as independent instances of the same model, each with different inputs).

Is this something that people often do, and would want better support for?

If it is, then it would be much more efficient to build this right into the builder, by turning our matrix-vector multiplies into matrix-matrix multiplies, etc. These types of operations are much more efficient than e.g. making parallel threads/processes to do this, since you only need to load the connection weights once for all inputs, rather than loading them individually for each input.

I'm running into this because it would be much faster to run ANN-type things on many inputs, but it would also help for dynamic networks, but only if people want multiple runs with different inputs but the same parameters. It also has the added effect of the model starting from scratch for each different input, which can be useful for some applications.

The main downsides are that it would complicate the builder (the biggest issue, IMO), add to the API (only very slightly, though, I think), and would not be supported by many backends (though this should be easy to detect).

**Comment by tcstewar** [comment]
Quick summary of discussion in today's dev meeting:

- A few people did indicate that they've had situations where this would be handy.  For me, it was in benchmarking a model, where I tend to run it with multiple inputs and compare the outputs to the ideal.  It'd be faster to do this in parallel.
- @hunse thought that maybe it'd be possible to do this as a post-processing step at the end of the builder, rather than modifying lots of things inside the builder itself, so that might make it easier to try a first implementation.
- As a separate, but related, issue, it would also be interesting to allow learning rules to work across these instances.  This is biologically implausible, but is the sort of batch learning that can happen a lot in machine learning.

**Comment by drasmuss** [comment]
This can be done now using NengoDL (see https://www.nengo.ai/nengo-dl/examples/from-nengo.html#Batch-processing), so we'd recommend using that for anyone wanting to do batch processing.
