### ISSUE TITLE
Exclude NotImplemented lines from coverage analysis

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1018]
I was looking at the coverage report for #1014 and noticed that `raise NotImplementedError()` lines get marked as not covered. I think these lines should be ignored in the coverage report (instead of counting as missed lines) because it doesn't seem useful to test that a feature has indeed not been implemented.

**Comment by arvoelke** [comment]
Since @tbekolay mentioned he was thinking about switching to `codecov`, can see how the above is done [here](https://github.com/arvoelke/nengolib/blob/master/.coveragerc#L9). Might even be the same thing in `coveralls`.

**Comment by hunse** [comment]
If it's easy to do, then by all means! Not to put words in anyone's mouth, but I'm pretty sure we'll switch to `codecov`, since our coveralls isn't even working properly right now. So wait until then and we'll add in the fix from @arvoelke's repo.

Just a general comment, though: I don't think we're ever going to be aiming for/requiring coverage of every line in Nengo. I see it as more of a tool to look for big gaps that aren't covered.

**Comment by arvoelke** [comment]
> I don't think we're ever going to be aiming for/requiring coverage of every line in Nengo. I see it as more of a tool to look for big gaps that aren't covered.

Makes sense for projects of this size. Useful for code review in general, to check for anything new that should obviously be covered.

**Comment by jgosmann** [comment]
> Just a general comment, though: I don't think we're ever going to be aiming for/requiring coverage of every line in Nengo. I see it as more of a tool to look for big gaps that aren't covered.

Sure, but that's also easier if it isn't cluttered with irrelevant lines marked as 'missed'.

**Comment by hunse** [comment]
As I said, if it's easy, by all means.
