### ISSUE TITLE
Adopting a code of conduct

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#1070]
In prepping #1069, one aspect that I think is missing from the CONTRIBUTING document there is a code of conduct. Our community is relatively small at the moment, but it will (hopefully!) grow, and making a statement about trying to foster an inclusive and friendly environment is, in my opinion, super important for that growth.

If we can reach consensus on the questions below, I'll include the code of conduct in https://github.com/nengo/nengo.github.io and make a PR to link to it in Nengo repos.
### Questions
1. Do you support adding a code of conduct?
2. When incidents occur, we have to deal with them appropriately. Would you be willing to help enforce the code of conduct? (Note: definitely not necessary for everyone to help, but we need at least a few people who are committed to help enforce when necessary.)
3. Which code of conduct text should we adopt? Choices, with notes for additional context:
   - [Contributor covenant](http://contributor-covenant.org/version/1/4/) (by far the most widely used CoC out there, so the "standard")
   - [Ubuntu's](http://www.ubuntu.com/about/about-ubuntu/conduct) (somewhat specific to Ubuntu's aims and open source ambitions, but a few good sections not included in other CoCs)
   - [Django's](https://www.djangoproject.com/conduct/) (more detailed and pragmatic than other CoCs, includes guidelines for reporting and enforcement)
   - [Angular's](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md) (much shorter than the other CoCs)
   - Write our own, mixing in good ideas from others.

Please add a comment below with your answers to these questions so we can reach a consensus! Also, if you know of any other CoC text that you'd rather use, feel free to suggest it!

**Comment by tbekolay** [comment]
My answers:

1. Yeah, I made the issue so obvs.
2. Yes, I'll help enforce.
3. I think for the size of project that we are at the moment, Angular's CoC is has the right tone and is short enough that most people will actually read it.

**Comment by Seanny123** [comment]
My answers:

1. Yep.
2. I moderate on CogSci.SE as a hobby, so it's nice to be able to use my Mod skills in a professional setting too.
3. I like the brevity of Angular's CoC.

**Comment by hunse** [comment]
My personal opinion is that people should know how to conduct themselves with respect and courtesy to others everywhere (including everywhere on the internet), and for those who don't, are they really going to bother to read a code of conduct or change their behaviour because it's in some file? Also, I feel that sometimes having a document makes people more justified in their marginally unacceptable behaviour, because they can argue it wasn't quite covered in the CoC. 

But that's just my cynicism. It's just a small file, and I think it will do more good than harm. Frankly, at this point, I don't think it will do much at all, but if we implement it now we'll have it for down the road.

1. I'm not opposed.
2. I don't like talking about enforcement. But I'm happy to confront people whose behaviour is not acceptable here, whether we have a CoC or not.
3. Now for which one...

I think the common problem with these types of documents is that people glance at them and think "oh yeah, don't discriminate, don't troll, I know all this stuff". Or at least that's what I thought glancing at a few of them, particularly Angular's and CC. Looking at the other two (Ubuntu and Django), I think they go a bit deeper into the values of the project, particularly those values that are specific to an open-source software project with extensive web-based collaboration.

Of course I agree that no one should be discriminated against because of race, gender, sexual identity, etc. And while I do think it's important to make that clear, those things are so obvious to me (and something I strive for *all* the time), that I start reading that and immediately think "I know this stuff". I'd like to highlight the things that are specific to this forum, for example "level of experience". CC  and Angular both have that just tacked on to the other types of discrimination, but I'd like to highlight it more, because I think it's more specific to this forum. I'd also like to elaborate on what it means. Of course it doesn't mean that if two people who are new to a project vote to merge a pull request and one person who has been here forever says no, that that person should be overruled and the PR be merged. Now we don't have to say that we don't mean that, but we should say what we do mean, e.g. "Level of experience: We value the contributions of everyone, and will consider ideas and contributions from all based on their own merit, independent of how much experience a person has with this projects or open-source projects in general." Or something to that effect.

I also really like Django's paragraph about "when we disagree, try to understand why". I'm not sure if I would copy the whole thing, but I do like a lot of the sentiments that go deeper than just "no personal attacks" and really address why these personal attacks happen, namely because of disagreements that get out of hand.

Overall, I agree that conciseness is key. We want people to read this thing. But I really want it to convey how we plan on dealing with some of the types of issues that are specific to these types of projects, and really set the tone for how we want to collaborate. I'd like to go a bit deeper than just saying "treat other people with respect and don't discriminate", because those are things you learn in kindergarten, and anyone who hasn't learned that by now probably won't be swayed by hearing it said one more time in a text file.

**Comment by tbekolay** [comment]
> I'd like to highlight the things that are specific to this forum, for example "level of experience"

I completely agree, along with the rest of your comment! I added a "write our own" option and edited my answer to go with that one. If others are into that, I'll draft something in a few weeks, focusing on brevity and issues specific to these types of forums.

**Comment by ikajic** [comment]
+1 to Eric's comment and the idea of writing our own, which focuses on this project and goes beyond things which should be common sense. I think [Debian's CoC ](https://www.debian.org/code_of_conduct)is also a good example of that.

1. I'm ok with that
2. Instead of saying "that violates our CoC", I would prefer to explain to a person why what they've done/said is wrong and use CoC as a guideline if needed
3. Writing our own

**Comment by jgosmann** [comment]
what Eric said

**Comment by tbekolay** [comment]
Happened upon this engineering code of conduct which might be more along the lines of what we want (or at least have a few things we can steal for ours): https://github.com/digitalocean/engineering-code-of-conduct

**Comment by hunse** [comment]
Oh wow, I really like that engineering code of conduct.

**Comment by Seanny123** [comment]
I agree with Eric again. That code of conduct is super-duper awesome.

**Comment by tbekolay** [comment]
I've made a [PR](https://github.com/nengo/nengo.github.io/pull/13) adding a code of conduct to nengo.github.io. It's based on the DigitalOcean CoC, and therefore is not particularly concise, so please weigh in on that PR whether we're ok with that or if we should try to cut it down.
