### ISSUE TITLE
Memory leak in parameter system.

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1089]
I think there is a memory leak in the parameter system (I haven't verified it yet). We haven't noticed it yet because parameters tend to be small and at least I usually run only one simulation per process. @ikajic however is running more than one simulation and is experiencing severe memory leaks. Also because in those simulations large SPA vocabularies are stored as part of a parameter (on the bleeding-edge branch using the rewritten SPA system).

First look at [`params.py:76`](https://github.com/nengo/nengo/blob/bleeding-edge/nengo/params.py#L76), the assigned parameters are stored in a `WeakKeyIDDictionary`. Note that the `Params` class is not instantiated per object instance, but for each parameter a such an instance is created when the parameter is defined in a class. Thus, the `Params` instance including the `WeakKeyIDDictionary` lives usually for the whole runtime of the script.

Now take a look at the implementation of [`WeakKeyIDDictionary`](https://github.com/nengo/nengo/blob/bleeding-edge/nengo/utils/stdlib.py#L19). It uses two dictionary-like objects `_keyrefs` and `_keyvalues` to map object ids to the "key" and value respectively. `_keyrefs` is a `WeakValueDictionary`. As such the objects used as key (that is the objects on which parameters are be set) will be garbage collected when no other references exist. `_keyvalues` however is a normal dictionary. That means the value assigned to the parameter will never be garbage collected (and that can be large vocabularies as stated at the beginning).

**Comment by tbekolay** [comment]
b4c37d74d19999b1ef43 is the commit that changed this; previously it was a normal `WeakKeyDictionary`, which shouldn't leak memory in this way. I believe the reason for the change (@hunse can correct me if I'm wrong) was to ensure that equality of keys uses an `is` check instead of `==`? Brief example:

```python
l1 = nengo.LIF()
l2 = nengo.LIF()
d = WeakKeyDict()
d[l1] = 'hey'
print(d[l2]) # prints 'hey' because l1 == l2
d = WeakKeyIDDict()
d[l1] = 'hey'
print(d[l2])  # raises KeyError because l1 is not l2
```

The fix is not super straightforward as I think it means we essentially have to implement our own garbage collection ... scan the `_keyrefs` to look for stale entries at some point and remove them from `_keyvalues`. That's an annoying piece of code to write, so I'd be happier if we could switch to something else from `collections`, or subclass `WeakKeyDict` to make it work as above (assuming I haven't missed something about what `WeakKeyIDDict` is doing?)

**Comment by jgosmann** [comment]
> is check instead of ==

I think that is the behaviour we want. (Otherwise setting parameters on one object may overwrite parameters on another.)

> The fix is not super straightforward as I think it means we essentially have to implement our own garbage collection

I don't think it is as bad as you think. I'm working on a fix right now.

**Comment by tbekolay** [comment]
> I don't think it is as bad as you think.

I don't think it's hard to get something working. But I think it's hard to do it such that it's performant and correct in all cases... if it were, there wouldn't be 3 or 4 different garbage collection schemes currently in us by modern programming languages.

**Comment by jgosmann** [comment]
With "not as bad as you think", I was meaning to say, I don't think we need to implement our own garbage collection.

**Comment by tbekolay** [comment]
> I don't think we need to implement our own garbage collection.

Cool, I'll wait patiently for the fix then ;)

**Comment by jgosmann** [comment]
👉 #1090
