### ISSUE TITLE
How to make learning connection between spa.State?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1093]
Is there a straightforward way to make a learning connection between two `spa.State` objects without forcing all of the dimensions into a single ensemble (which causes agonizing build times)? Should a helper function be made?

**Comment by xchoo** [comment]
Uh. This really depends on _what_ you want the learning to do... If the learning needs to take into account all of the dimensions from the `spa.State` object, then you *have* to force it all into one giant ensemble.

**Comment by tcstewar** [comment]
> Uh. This really depends on what you want the learning to do... If the learning needs to take into account all of the dimensions from the spa.State object, then you have to force it all into one giant ensemble.

Yup.  That said, for most situations, I think you can get away with making a Connection from each state Ensemble to the target, and putting a learning rule on all of them (and feeding your error signal to all of them).  It'll still try to do the best job it can, given how the neurons are split up.  So something like this should work:

```python
    for ens in model.pre.state_ensembles.ensembles:
        c = nengo.Connection(ens, post, function=lambda t: 0, 
                             learning_rule_type=nengo.PES())
        nengo.Connection(error, c.learning_rule)
```

**Comment by Seanny123** [comment]
Here's my first draft of the function:
```
def connect_ea_learn(ea_in, ea_out, err_sig, learning_rule_type):
    # TODO:
    # set up the params properly
    # let connection params get passed in
    # check for same amount of ensembles and dimensions
    learn_conns = []
    err_dims = int(err_sig.size_out / len(ea_in.ea_ensembles))
    for e_i, (ens_in, ens_out) in enumerate(zip(ea_in.ea_ensembles, ea_out.ea_ensembles)):
        learn_conns.append(nengo.Connection(ens_in, ens_out, learning_rule_type=learning_rule_type, transform=0))
        nengo.Connection(err_sig[e_i*err_dims:(e_i+1)*err_dims], learn_conns[-1].learning_rule)

    return learn_conns
```

I'll make it into a proper pull request after I finish helping with a summer school project.

**Comment by hunse** [comment]
So the drawback to what you've got above, @Seanny123, is that there can't be any interactions between the different dimensional groups in your EnsembleArrays. For example, the neurons in the first ensemble of `ea_in` can't affect those in the second ensemble of `ea_out`.

If you really want to have those mixing terms, you'd either have to have connections from every input ensemble to every output ensemble, or do something like what I think @tcstewar is suggesting, where you connect all the ensembles to a passthrough node (without slicing on the passthrough node), with learning on those connections. Then you'd connect that node to your target EnsembleArray.

You'll always be a bit limited since you can't learn nonlinear relationships between arbitrary dimensions, but the only way to get around that is to have one giant ensemble like @xchoo suggests.

**Comment by Seanny123** [comment]
Gotchya. I'll switch this from a feature request to a documentation request.

**Comment by jgosmann** [comment]
Moved to nengo/nengo_spa#16.
