### ISSUE TITLE
Log output in Jupyter notebook

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1116]
When activating logging in Jupyter notebook with `nengo.log('info')` each log line gets printed twice like so:

```
INFO:nengo.builder.optimizer:Running OpMergeOptimizer ...
[INFO] Running OpMergeOptimizer ...
INFO:nengo.builder.optimizer:Pass 1: Reduced 6562 to 5558 operators in 7.279264s.
[INFO] Pass 1: Reduced 6562 to 5558 operators in 7.279264s.
INFO:nengo.builder.optimizer:Pass 2: Reduced 5558 to 4554 operators in 7.594478s.
[INFO] Pass 2: Reduced 5558 to 4554 operators in 7.594478s.
```

The lines starting with `INFO:` will have a salmon colored background like warnings.

**Comment by tbekolay** [comment]
So this happens because Jupyter has its own logging handler set up, but sets the log level to WARNING so only warnings and worse get printed. With `nengo.log('info')` we set up our own handler and also set the level to INFO. Setting the level to INFO means both logging handlers will now handle `logger.info` calls.

Not sure what the best resolution is here... some possibilities.

1. Detect if we're in the notebook (by looking at what handlers already exist) and don't add a new handler if the notebook handler already exists. Or remove the Jupyter handler.
2. Detect if _any_ handler that prints to a stream exists and don't add the console handler if it exists.
3. Don't mess with the level of `logging.root`. I seem to remember that this is necessary, but maybe that's not true and if we just don't mess with it then we'll get mostly the desired effect (though warnings and errors will still double-print).
4. Don't change anything and somewhere (somehow!) suggest that in the notebook don't call `nengo.log` and instead do `logging.root.setLevel(logging.INFO)`

**Comment by jgosmann** [comment]
This doesn't seem to happen anymore in recent versions of Jupyter/IPython.
