### ISSUE TITLE
Neurons object (and related) should not use a weak reference to ensemble

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1152]
Try the following code:

``` python
neurons = nengo.Ensemble(10, 1, add_to_container=False).neurons
print(neurons.ensemble)
```

It will print `None` because the only remaining reference to the ensemble is a weak reference. This means the `neurons` object cannot be used in connections anymore. This might seem like an irrelevant case because the ensemble is never added to a network, but this is just the simplest piece of code reproducing the problem. In the tests in #984 (added by @hunse) the same problem occurs because the network reference is not kept around (that's why I found this problem in the first place).

It would be possible to fix the tests to keep around the network reference, but to me it feels like this should not be necessary. I could also see, this crop up and various other place if people make use of copies.

To me it seems better to change the weak reference into a strong reference. This would fix the problem without the risk of running into it again and it probably would simplify the copy code (because it won't have to deal with weak references only with shallow vs deep copies). There is a slight disadvantage, though: The `Ensemble` and `Neurons` objects will have a reference cycle that prevents memory deallocation when all other references to those objects are gone. But this is not a huge problem as the Python garbage collector will dispose of the objects; it's just a later point in time.

Does anyone have objections or did I miss any reasons for using weak references?

The same problem should also be fixed for learning rules and potentially a few other places.

**Comment by tbekolay** [comment]
The point of using the weak reference here is to break the reference cycle and deallocate memory as soon as possible, so you haven't missed anything, but I'm not sure what possible use case there could be for having a `Neurons` object around if the `Ensemble` it is associated with doesn't exist anymore... Really, in the ideal case the `Neurons` object wouldn't have a handle to the `Ensemble` at all, but having it is convenient.

If the only use case is for testing, then I think the test code doesn't reflect actual use cases and should be rethought.

**Comment by jgosmann** [comment]
To me this seems to be premature optimization. I don't think the slightly prolonged life time will affect any program and it definitely increases the complexity of the copy implementation (not just on the test side) which already has some non-trivial and hard-to-miss corner cases.

**Comment by tbekolay** [comment]
I don't see how making this a non-weakref solves anything... to me it seems like it will cause more bugs, because if you were to deepcopy the `Neurons`, which deepcopies the `Ensemble`, but then elsewhere you also deepcopy the `Ensemble`, then your model is in a super weird state that will still build and run, but be undeniably wrong. The fact of the matter is that copying Nengo models is hard, and that's why we didn't do it until now.

> To me this seems to be premature optimization.

I can see how you might think that, but we use `weakref`s because several years ago not using `weakref`s resulted in a simple model build taking several hours. It's not necessarily this particular weakref that solved it, but whenever it _should_ be a weakref we do it now in order to be more careful and reduce the possibility of bugs.

For some more context, we used to rely very heavily on deepcopying networks. Prior to 74ea02053fa557b4ed8300e9a3b1121422fd238f, the builder did a deepcopy of the model at the start of the build process so that the builder could modify any of the Nengo objects without worrying that the user's initial model would be changed. Obviously that seems kind of ludicrous now, but Nengo 1.4 was very different, and the model also kept the simulation state in it, and a lot of why we wrote Nengo 2.0 was to decouple the model creation from the simulator. Anyway, so I had the model be deepcopied before simulating so that if anyone in a Nengo 1.4 mindset modified objects during the simulation it wouldn't affect the model they had created in their script, meaning they could create a new simulator on that model and the two simulators could both run at the same time (which is not something you could do in Nengo 1.4).

Deepcopying worked fine until we were adding more features, building larger models etc, and at one point some combination of features and model size meant that the build was taking essentially forever, and in debugging it I found that there was some reference cycle that was making the deepcopy recuse infinitely, at which point I learned about `weakref`s and put them in where it made sense.

Removing `weakref`s where we decided a `weakref` made sense and have been using problem-free up until now seems like a step backward. I am highly skeptical that it makes the copy code easier while also not causing subtle bugs...

**Comment by jgosmann** [comment]
> I don't see how making this a non-weakref solves anything...

We have do to deal manually with weakrefs because they unpickle as dead references. This requires special `__getattr__`/`__setattr__` functions whereever we use that construct. Furthermore, if we do this manually, we might need to know whether it's a shallow or deep copy which we cannot know in those functions. We don't need to know this, if we don't need to implement these functions as Python should do the right thing. Finally, it seems to be that with the weak reference we have to implement the same things that Python already implements to deal with shared references.

Copy/pickle already handles reference cycles, so in this case we don't need to implement `__getstate__`/`__setstate__` on the `Neurons` object.

> if you were to deepcopy the Neurons, which deepcopies the Ensemble, but then elsewhere you also deepcopy the Ensemble, then your model is in a super weird state that will still build and run, but be undeniably wrong.

I don't follow you here. You'll get three independent copies of Ensemble/Neuron pairs. I don't see what's wrong with that or why this would put your model into a weird state. Also, what would you suggest how the weak reference should be handled when a deep copy of the `Neurons` is done?

> whenever it should be a weakref we do it now in order to be more careful and reduce the possibility of bugs.

It should be a weakref when a strong reference would completely prevent the garbage collection. This case is not as clear cut because to me it seems that the weakref here increases the possibility of bugs (due to more complex copy code). But I don't know how exactly the model taking several hours to build was caused, so maybe there is a possibility of bugs on either side.

> I found that there was some reference cycle that was making the deepcopy recuse infinitely

Python handles reference cycles in deep copies, so this cannot be the sole reason.

**Comment by tbekolay** [comment]
> It should be a weakref when a strong reference would completely prevent the garbage collection.

Can you explain the situations in which garbage collection is completely prevented, and when we _should_ be using weak references?

**Comment by jgosmann** [comment]
The classic example is a global “cache” that persists for the whole interpreter session/program run time. We have that for example in the parameter system because the parameters instances are class variables that exist for the whole run time. But the stored parameter values are for instances that might not live as long and there the associated data should be available to garbage collected once the instance is dead.

**Comment by tbekolay** [comment]
> The classic example is a global “cache”...

That's an example of one instance we might use references... but how should we be making decisions about when we should use references and when we shouldn't? What are Python's rules about what gets garbage collected and what doesn't?

> I don't follow you here. You'll get three independent copies of Ensemble/Neuron pairs.

Here's the situation...

```python
with nengo.Network() as net:
    ens = nengo.Ensemble(10, 1)
    ens_neurons = ens.neurons
my_objects = (net, ens, ens_neurons)
run_model(*my_objects)  # works as intended
my_copies = tuple(obj.copy() for obj in my_objects)
run_model(*my_copies)  # does not work as intended

def run_model(net, ens, ens_neurons):
    ens.radius = 1.5  # Vary some parameter, could be read from file
    with nengo.Simulator(net) as sim:
        sim.run(0.1)
    # Record data
```

This is not at all a contrived example, it's a common use case. I implemented some copying functionality while running models for my thesis because I was running something like `run_model` in parallel, and that requires pickling and unpickling the arguments to that function.

You can argue that people shouldn't write code like this, but they will, so the only thing we can do is either explicitly prevent it (which we did before by saying "this can't be pickled and unpickled) or make sure it works as intended. The `weakref` is there so that Nengo works as we intended... if your intention is different, then I need more concrete details about what is supposed to happen in this case.

**Comment by jgosmann** [comment]
> That's an example of one instance we might use references...

I think you mean *weak* references?

> but how should we be making decisions about when we should use references and when we shouldn't?

Would a strong reference prevent proper garbage collection? If yes, use a weak reference. If no, use a strong reference.

> What are Python's rules about what gets garbage collected and what doesn't?

Python uses reference counting and disposes of any objects that have no (strong) references left. In addition it runs a garbage collector (with some scheduling algorithm) that detects reference cycles that are unreachable and frees those.

I don't think your example is related to weak references at all and would not be fixed by them in any way. You're expecting that copying `ens` and `ens_neurons` will return references to the objects in the copy of `net`. But when copying the `ens` and `ens_neurons` objects, there is nothing that tells us about the copy of `net` or even if, there could be multiple copies of `net` and it would not be clear to which of those copies the `ens` and `ens_neurons` copies should be related. There would be two proper ways to implement your example:

1. You could look up the new `ens` and `ens_neurons` instances on the copy of `net`.
2. You do the copy like this `my_copies = copy.deepcopy(my_objects)` (which works because Python handles shared references).

**Comment by jgosmann** [comment]
Another question is: Why are we storing that Neurons object on the ensemble at all? We could just create a new one whenever we access `Ensemble.neurons` (and have a strong reference in `Neurons`). Then there would be no reference cycle and the copy implementation would be simplified a bit more.

**Comment by jgosmann** [comment]
I'd have to check whether that's an option for the learning rule too ...

**Comment by jgosmann** [comment]
Hm, I see we use the object instance as key in the model signal dictionary.

**Comment by hunse** [comment]
>  Why are we storing that Neurons object on the ensemble at all? We could just create a new one whenever we access `Ensemble.neurons`

I like that idea.

**Comment by jgosmann** [comment]
Me too, the thing with the signal dict was fixed easily by implementing appropriate `__hash__` and `__eq__` functions. Only one failing tests remaining for learning rules.

**Comment by tbekolay** [comment]
> We could just create a new one whenever we access `Ensemble.neurons`

This was done because properties shouldn't be doing any non-trivial processing since properties look like attributes. Making new class instances isn't very expensive, but there might still be corner cases where someone's accessing `.neurons` a lot without realizing that it's making new instances and eating up memory. Yes I know it will get garbage collected eventually.

That said, I'm fine with changing it, just pointing out the reasoning behind it. Also, ideally along with this change, we would make `.neurons` not a property but a method. But, it's not an issue big enough to justify an API change.

**Comment by hunse** [comment]
> This was done because properties shouldn't be doing any non-trivial processing since properties look like attributes

While this is a good rule of thumb, I've never found this to be a clear-cut thing. I also think there are very different considerations when you're talking about the computational parts of a software package (i.e. our simulator), versus the descriptive parts (i.e. our API). Since it's fairly safe to assume that users are always making models to simulate them, and that the time to simulate Neurons objects far outweighs the time to create them, then I'm not too worried about the bit of extra processing that happens when accessing `Ensemble.neurons`. I also think that because we use it like an attribute, I'd keep it as a property, even if the API change wasn't an issue.

That all said, I'd be fine keeping `Neurons` exactly the way it is right now, if we can find a way to copy it properly. I don't think the weak references are a problem in and of themselves (I think I differ with @jgosmann on this), but right now generating a new `Neurons` object each time seems to be an easy way to get the copying/pickling working, and I don't have any other potential solutions.

**Comment by jgosmann** [comment]
> but there might still be corner cases where someone's accessing .neurons a lot without realizing that it's making new instances and eating up memory.

If we really, worry about that we could define `__slots__`. The class has basically just one reference (two for learning rules), so you really need to create a lot of instances. Because there are no cyclic references anymore, we don't even have to rely on garbage collection. The objects get freeed as soon as all references are gone. If references are still around, e.g. from Connection objects, those have probably way more overhead memory-wise.

I think that approach really helps to keep the copy code simple (I am preparing a commit right now).

**Comment by jgosmann** [comment]
> That all said, I'd be fine keeping Neurons exactly the way it is right now, if we can find a way to copy it properly.

If someone wants to try to implement it that way, go ahead ... but don't blame me if you end up sinking a lot of time in it.

**Comment by jgosmann** [comment]
As #984 is merged, this is fixed.
