### ISSUE TITLE
Dynamic configs

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1199]
(Might be somewhat related to #1043.)

To use a config object one has to define the classes to configure like this:
```python
cfg = nengo.Config(nengo.Ensemble, nengo.Connection)
```
or
```python
cfg = nengo.Config()
cfg.configures(nengo.Ensemble, nengo.Connection)
```

What are the reasons for not adding the configured class dynamically as needed to allow something like:
```python
cfg = nengo.Config()
cfg[nengo.Ensemble].radius = .5
```

I'm currently thinking about how the new SPA system can best make use of the config system and this could simplify things.

**Comment by tbekolay** [comment]
Hmm... I'm not 100% certain, but looking at the code, I think the main reason we didn't do this is because we cascade to superclassses when something isn't found. So if you haven't configured `Ensemble` but you have configured `NengoObject`, we'll look things up on the `ClassParam` associated with `NengoObject`.

The reason why we did it this way is for network subclasses. If we were to store parameters on a network, and you make a network subclass and then do `cfg[MyNetworkSubclass].network_prop` it will work because it associates a `ClassParams` instance for `MyNetworkSubclass` based on `Network`, not `MyNetworkSubclass`.

Anyway, if I recall, that was my thinking at the time I wrote that stuff (unless @drasmuss wrote that stuff?) We haven't actually used networks in the way that I described above though, to my knowledge, so it might simplify the config code if we stop the cascading to superclasses and automatically make `ClassParams` when needed.

I easily may have forgotten some other reasons we did that though, so proceed at your own risk!

**Comment by jgosmann** [comment]
That's interesting. It seems to me that cascading to the super class is desired behaviour when reading params, but not when setting them. For example:

```
class A(object):
    my_param = IntParam(...)

class B(A):
    pass

cfg = nengo.Config(A)
cfg[B].my_param = 1.
```
would set `my_param` for all instances of `A` which is misleading. To me it seems this should either raise an error (because cfg is not configuring `B`) or (maybe?) set `my_param` only for instances of `B`.

On the other hand the following is useful:
```
cfg = nengo.Config(A)
cfg[A].my_param = 1
print(cfg[B].my_param)
```

Unfortunately, there is probably no easy way to differentiate between read and write access.

**Comment by jgosmann** [comment]
Decisions from the dev meeting:
* In practice this isn't a problem for core Nengo because we usually don't use subclasses of configurable objects so far.
* It might be a problem in new-spa, but there classes are automatically added to what the `spa.Module` object configures which prevents this from happening.

Thus, we leave Nengo as it is for know, stress test the config with auto-configuring in nengo_spa and if it works well might port the auto-configure to Nengo.
