### ISSUE TITLE
Close figures created in tests.

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1203]
While working on new-spa I discovered this warning being produced by the tests (not sure if this is just for the Jupyter notebook examples or all tests):
```
/home/jgosmann/.pyenv/versions/3.5.2/lib/python3.5/site-packages/matplotlib/pyplot.py:516: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
```

It is probably a good idea to close all matplotlib figures after each test.

**Comment by tbekolay** [comment]
So we do actually close all figures in the `__exit__` method of `Plotter` (see https://github.com/nengo/nengo/blob/master/nengo/utils/testing.py#L116). Originally I did this because if you don't, the unit tests will plot on top of one another in some cases. But it should also deal with this kind of warning -- my guess is that it's one particular example that is creating a ton of figures without closing any.

**Comment by jgosmann** [comment]
Is the plotter used in the Jupyter notebook examples?

**Comment by tbekolay** [comment]
[Yes, we use the `plt` funcarg specifically to close figures](https://github.com/nengo/nengo/blob/master/nengo/tests/test_examples.py#L58).

**Comment by jgosmann** [comment]
[But is that actually used, if the `globals` and `locals` dict are empty?](https://github.com/nengo/nengo/blob/master/nengo/tests/test_examples.py#L67)

**Comment by jgosmann** [comment]
Seems so. I think the problem might be that if `self.record` is `False`, [`self.plt` is assigned a `Mock()` object](https://github.com/nengo/nengo/blob/master/nengo/utils/testing.py#L89). Then instead of calling the actual Matplotlib close, [we call it on the mock object](https://github.com/nengo/nengo/blob/master/nengo/utils/testing.py#L96) which has no effect. In the Jupyter notebook the `plt` fixture is also not used, instead they import `matplotlib` and thus do the actual plotting instead of using the mock object.

**Comment by jgosmann** [comment]
Not entirely sure, if what I said in the last comment is actually part of the problem, but foremost `plt.close` is never called (neither on matplotlib nor on the mock) as long as `self.record` is False.

**Comment by tbekolay** [comment]
Yeah, `self.record` is False when `--plots` isn't passed. This is so people can run the test without matplotlib installed -- if we try to close figures regardless, then it'll fail if matplotlib isn't installed.

Since the examples use `matplotlib` directly, probably we should have a `pytest.importorskip` for mpl there, and manually call `plt.close('all')` in `assert_noexceptions`.
