### ISSUE TITLE
Plot doesn't match description in combining.ipynb example

### ISSUE THREAD

**Issue by mgserafi** [nengo/nengo#1247]
In `examples/basic/combining.ipynb`, the colors of the plot output at the end don't match the description. 

Plot:
![image](https://cloud.githubusercontent.com/assets/18017580/21438743/9292b418-c858-11e6-9830-1d6b583b7062.png)

The description says: 

> The graph shows that the input signal (Sine), the output from the 1D population (A output), and the 2D population (blue line) are all equal. The other dimension in the 2D population is shown in green.

but the line that matches the Sine and A output is in green. (Also visible on the documentation site, [here](https://pythonhosted.org/nengo/examples/combining.html)).

**Comment by jgosmann** [comment]
We should not rely implicitly on the the matplotlib color cycle because it can change. In fact [it will in in Matplotlib 2.0](http://matplotlib.org/2.0.0rc2/users/dflt_style_changes.html). Probably it is best to explicitly state the colour in the plot command? (Minor disadvantage: The default colour cycle is not respected.)
