### ISSUE TITLE
Consistency using defaults in parameters & constructors

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo#1272]
Noticed that in [`ensemble.py`](https://github.com/nengo/nengo/blob/master/nengo/ensemble.py#L109) the parameters use the `default` argument which is then used in the constructor as `<param>=Default` but in [`learning_rules.py`](https://github.com/nengo/nengo/blob/master/nengo/learning_rules.py#L165) the `default` argument is not used and the constructor uses `<param>=<value>`. 

Is there a reason for this? do we want to make things consistent?

**Comment by tbekolay** [comment]
`Default` is only designed to work with `NengoObject`s, which [`Ensemble` is](https://github.com/nengo/nengo/blob/master/nengo/ensemble.py#L8) but [`LearningRuleType` is not](https://github.com/nengo/nengo/blob/master/nengo/learning_rules.py#L18). This is mostly because there are two interacting systems (what's in `params.py` and what's in `config.py`) that we've tried to keep as separate as possible (coupling is bad) but they nevertheless interact (`config.py` depends on `params.py`, but not the other way around), so it's not always obvious whether you're dealing with param stuff or config stuff.

I suspect if this were to change, it would be part of a larger param/config system refactoring.

**Comment by jgosmann** [comment]
There is `nengo.config.SupportDefaultsMixin` then non-Nengo-objects can derive from to support the `<param>=Default` assignment. But the learning rules are not in the `configures` list of the `Network.config` which makes it maybe somewhat moot to have learning rules derive from `SupportDefaultsMixin`. To be able to set the default one has to create a config that actually configures those classes first.

**Comment by bmorcos** [comment]
Interesting. Thanks for the explanation!
