### ISSUE TITLE
API for spikes2events

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#1396]
I have a few questions/concerns about [`spikes2events`](https://github.com/nengo/nengo/blob/master/nengo/utils/neurons.py#L12).

1. Was there a reason this wasn't moved to `nengo_extras`?
2. Why does this return a list of arrays instead of a 2D `np.ndarray`?
  2.1 Would it be a good idea to commit to returning an `np.ndarray` whenever possible to reduce the amount of API surprises in Nengo?
3. If I wanted to change the API to `np.ndarray`:
  3.1 Would it have to wait until Nengo 3.0?
  3.2 Would I have to make an NEP?

**Comment by tbekolay** [comment]
This was actually [copied to `nengo_extras`](https://github.com/nengo/nengo_extras/blob/d63e12aa787419fcafed32027105583d614e9e6d/nengo_extras/neurons.py#L124) but not removed yet; removing it is done in #1187 so we should revisit that PR.

As for why it returns a list of arrays, it's because the number of spikes for each neuron can be different from other neurons. In other words, it's a list of vectors with different lengths, which can't be made in a dense 2D `np.ndarray`; instead, it becomes a 1D `np.ndarray` of type `object`, which is in some ways better than a list, but I think is kind of misleading to the end user, since they might think it's a dense 2D array and treat it as such.

**Comment by Seanny123** [comment]
> As for why it returns a list of arrays...

Duh. This is what happens when I try to read code while sick...
