### ISSUE TITLE
Got " 'activities' matrix is all zero " BuildError

### ISSUE THREAD

**Issue by dongniu0927** [nengo/nengo#1458]
Hello, I use EnsembleArray to solve the [issue](https://github.com/nengo/nengo/issues/1457). And I build a connection as follows:
```python
nengo.Connection(pre=self._enses.ea_ensembles[i], post=self._enses.ea_ensembles[j],
                                         transform=[[self._weights[i][j]]], learning_rule_type=nengo.Oja(),
                                         solver=nengo.solvers.NoSolver(weights=True))
```
But when the scale of net become bigger, I got the following error:
```bash
nengo.exceptions.BuildError: Building <Connection from <Ensemble "278"> to <Node "output">[278:279]>: 'activities' matrix is all zero for <Ensemble "278">. This is because no evaluation points fall in the firing ranges of any neurons.
```
I don't quite understand this mistake description. 
Hope to get a little hint! Thanks!

**Comment by arvoelke** [comment]
@bmorcos doesn't `NoSolver` bypass `build_decoders` -- by calling `build_no_solver` instead -- which should avoid the above `BuildError`? How is this error even possible with `NoSolver`?

@dongniu0927 it may help to provide a complete minimal example and include the stack-trace? In general what is happening is that it's trying to solve for decoding weights by using the ensemble's `eval_points`. I'm not sure what you are trying to do, but you may want to be aware that connecting from `self._enses.ea_ensembles[i].neurons` to `self._enses.ea_ensembles[j].neurons` (note the `*.neurons`) instead will allow you to specify the matrix of weights between the two ensembles of neurons, without having Nengo solve for the decoders. Otherwise, the `transform` will be applied to the decoded vector space between ensembles, and the weights will be learned (offline) via some decoder solver.

**Comment by arvoelke** [comment]
The above code does not reproduce the issue. There were some indentation errors that I needed to fix (and I also needed to remove the label and import some libraries). After fixing these problems, I get a different error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-13-2042c91c7e07> in <module>()
     11         for j in range(col*row):
     12               if i != j:
---> 13                     nengo.Connection(pre=enses.ea_ensembles[i], post=enses.ea_ensembles[j],
     14                                                transform=[[weights[i][j]]], learning_rule_type=nengo.Oja(),
     15                                                solver=nengo.solvers.NoSolver(weights=True))

IndexError: list index out of range
```

Nevertheless, I think you may wish to revisit what it is that you are trying to do. If you want to specify the connection weights between two populations of neurons, then you can do that via `nengo.Connection(ens1.neurons, ens2.neurons, transform=weights)` where `ens1` is an ensemble of `n` neurons, `ens2` is an ensemble of `m` neurons, and `weights` is an `(m, n)`-shaped numpy array. But above you are doing a strange combination of things:
 - Asking for all zero decoders (by using `NoSolver` without giving it a matrix)
 - Providing a scalar transform in the decoded vector space
 - Representing each vector space using only a single neuron

I'd suggest moving this over to http://forum.nengo.ai which is a more suitable forum for discussing what it is that you are actually trying to do. We might be able to help you find a much more elegant solution that avoids the weirdness you are seeing (and that I cannot currently reproduce).

**Comment by dongniu0927** [comment]
Thanks @arvoelke
