### ISSUE TITLE
Support for hierarchical timing

### ISSUE THREAD

**Issue by jaberg** [nengo/nengo#15]
It is natural to want to simulate different parts of the model at different speeds, right? Especially when building larger systems, with a greater variety of components, this seems essential for good performance. Not all motor and visual processes need to be updated at 1 KHz. Probes also don't need to run that fast.

For the API, this means establishing rules for specifying
* what clocks does the simulator have to provide (or how does the user set up a clock)
* how do you specify which clock a component should use
* how should components with different clocks be connected?

For RatSLAM and vision stuff this is important, and if we have such a mechanism then the probes should use it.

**Comment by tbekolay** [comment]
This issue was discussed at yesterday's dev meeting. This hasn't been pinged in three years, so we concluded that there isn't much demand for this issue, especially as workarounds are possible.

One possible workaround is to put the part of the model that should be simulated at a different timescale in a node. In the case where the node's clock is faster than the rest of the simulation, the node can either emit all of the values (i.e., `size_out = dimensions * node_dt / sim_dt`) or a subset of them. In the case where the node's clock is slower than the rest of the simulation, the value can remain the same for several simulation timesteps, or some more intelligent interpolation could happen, anticipating the next value before it comes.

In some work I did with audio filters, the audio filter needed to be simulated with a much faster clock than the rest of the simulation. In this case, I ran the filter in a node, and only kept the [last sample](https://github.com/tbekolay/phd/blob/master/phd/processes.py#L33); this meant that the internal state of the audio filter was correct even though the network sampled a tiny amount of the actual filter state. Worked well enough!
