### ISSUE TITLE
PES notebook example should say `pre_synapse` not `post_synapse`

### ISSUE THREAD

**Issue by chatterboy** [nengo/nengo#1560]
I've studied for learning rule with [documentation](https://www.nengo.ai/nengo/examples/learning/learn_communication_channel.html#)  and through debugging for myself. After debugging, I got a question that whether they point to the same thing. In the documentation, first, the last section says to us what post_synapse is. On debugging, however, the PES learning rule indicates [pre_synapse](https://github.com/nengo/nengo/blob/master/nengo/builder/learning_rules.py#L712) to filter encoding of pre ensemble. Are there any different from them?

Thank you.

**Comment by arvoelke** [comment]
I believe this is a typo in our documentation. This [PES example section](https://www.nengo.ai/nengo/examples/learning/learn_communication_channel.html#What-is-post_synapse?) should refer to `pre_synapse` rather than `post_synapse`. The `post_synapse` is only relevant for some of the other learning rules, such as `BCM`, `Oja`, and `Voja`. Thank you for catching this and letting us know!
