### ISSUE TITLE
nengo.Connection  transformation

### ISSUE THREAD

**Issue by liumingchen1** [nengo/nengo#1664]
Hello, how do I use the transform parameter in nengo.Connection()?How does the transform parameter work on pre and post?Or where can I find relevant information?

**Comment by liumingchen1** [comment]
n_neurons = 30
model = nengo.Network(label='Inhibitory Gating')
with model:
    A = nengo.Ensemble(n_neurons, dimensions=1)
    inhib = nengo.Node(Picewise({0: 0, 2.5: 1, 5: 0, 7.5: 1, 10: 0, 12.5: 1}))
    nengo.Connection(inhib, A.neurons, transform=[[1]] * n_neurons)
    nengo.Connection(inhib, A, transform=[1])

What is the difference between the tranform parameter in nengo.Connection(inhib, A.neurons, tranform=[[-2.5]] * n_neurons) and nengo.Connection(inhib, A, transform=[1])?

**Comment by hunse** [comment]
Hello,

The best place to find relevant information is [the documentation](https://www.nengo.ai/nengo/). Here's the [docstring for Connection](https://www.nengo.ai/nengo/frontend-api.html#nengo.Connection), where the `transform` argument is described.

If you have questions, the best place to ask is [the forum](https://forum.nengo.ai/). We use this site (Github) for reporting issues and bugs with the code.

In your example, the difference between `transform=[[-2.5]] * n_neurons` and `transform=[1]` is the value of the elements in the transform matrix (-2.5 in one case, and 1 in the other), and also the shape of the transform. In the first case, the shape is `(n_neurons, 1)`, and in the second case, it's `(1,)`. Arguments to `transform` always get passed through `np.asarray`, so if you want to know the shape, you can do e.g. `np.asarray([[-2.5]] * n_neurons).shape`, which will return the shape of `(n_neurons, 1)` (with the value of `n_neurons` substituted in for `n_neurons`). 

Looking at the transform docstring, you'll see that its shape should be `(size_out, size_mid)` (and since you don't have any `function` argument on your connections, `size_mid == size_in`). For the first connection, the size of `inhib` (as shown by `inhib.size_out`) is 1, and the size of `A.neurons` (as shown by `A.neurons.size_in`) is `n_neurons`. Therefore, your transform has to have shape `(n_neurons, 1)`. In the case of the second connection, the size of `A` is 1 (as shown by `A.size_in`, which is also equal to `A.dimensions`), so the shape of the transform should be `(1, 1)`. (We also allow a vector of length `n` to stand in for a diagonal matrix of shape `(n, n)`, which is why it's OK for `transform` to just have a shape of `(1,)` in this case.)

In practice, the difference between the two connections is that the connection to `A.neurons` connects directly to the neurons, meaning that a negative value coming in to the neurons will inhibit them (stop them from firing). With the connection to `A` though, `A` is being asked to "encode" the incoming value. So in that case, if you have a negative incoming value, the neurons that are sensitive ("tuned") to positive values will stop firing, but the neurons that are sensitive ("tuned") to negative values will fire more. For more details on representation, see the tutorials on [representing values](https://www.nengo.ai/nengo/examples.html#representing-values).

**Comment by liumingchen1** [comment]
> Hello,
> 
> The best place to find relevant information is [the documentation](https://www.nengo.ai/nengo/). Here's the [docstring for Connection](https://www.nengo.ai/nengo/frontend-api.html#nengo.Connection), where the `transform` argument is described.
> 
> If you have questions, the best place to ask is [the forum](https://forum.nengo.ai/). We use this site (Github) for reporting issues and bugs with the code.
> 
> In your example, the difference between `transform=[[-2.5]] * n_neurons` and `transform=[1]` is the value of the elements in the transform matrix (-2.5 in one case, and 1 in the other), and also the shape of the transform. In the first case, the shape is `(n_neurons, 1)`, and in the second case, it's `(1,)`. Arguments to `transform` always get passed through `np.asarray`, so if you want to know the shape, you can do e.g. `np.asarray([[-2.5]] * n_neurons).shape`, which will return the shape of `(n_neurons, 1)` (with the value of `n_neurons` substituted in for `n_neurons`).
> 
> Looking at the transform docstring, you'll see that its shape should be `(size_out, size_mid)` (and since you don't have any `function` argument on your connections, `size_mid == size_in`). For the first connection, the size of `inhib` (as shown by `inhib.size_out`) is 1, and the size of `A.neurons` (as shown by `A.neurons.size_in`) is `n_neurons`. Therefore, your transform has to have shape `(n_neurons, 1)`. In the case of the second connection, the size of `A` is 1 (as shown by `A.size_in`, which is also equal to `A.dimensions`), so the shape of the transform should be `(1, 1)`. (We also allow a vector of length `n` to stand in for a diagonal matrix of shape `(n, n)`, which is why it's OK for `transform` to just have a shape of `(1,)` in this case.)
> 
> In practice, the difference between the two connections is that the connection to `A.neurons` connects directly to the neurons, meaning that a negative value coming in to the neurons will inhibit them (stop them from firing). With the connection to `A` though, `A` is being asked to "encode" the incoming value. So in that case, if you have a negative incoming value, the neurons that are sensitive ("tuned") to positive values will stop firing, but the neurons that are sensitive ("tuned") to negative values will fire more. For more details on representation, see the tutorials on [representing values](https://www.nengo.ai/nengo/examples.html#representing-values).

Oh, think you very much! It's the best answer!

**Comment by hunse** [comment]
Glad I could help! I'm going to close this issue, but if you have follow-up questions (or other questions), feel free to ask on [the forum](forum.nengo.ai).
