### ISSUE TITLE
ability to specify radii per dimension?

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo#257]
It's come up that on this function I'm trying to compute one, one of the dimensions is large, but the others are small. And so when I increase the radii to handle this the whole thing loses accuracies to noise in the dimensions where the input is small. So, it's probably the case that it's better for me to just scale down the large dimension on input and account for it in my output function, but I thought I would see if this would be a thing of interest.

**Comment by tbekolay** [comment]
At a previous dev meeting, we decided that this would not be worth doing (at least not without some additional work figuring out what happens with multidimensional radii). I made https://github.com/nengo/enhancement_proposals/pull/6 to formalize that decision, since it's come up in the past and was a feature (albeit a broken one in Nengo 1.4).
