### ISSUE TITLE
Specifying a function with data points, rather than a callable

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#323]
Sometimes you just have a set of input and output data points for the function we want to approximate, rather than an explicit function.  It'd be nice to be able to do this:

```python
points = [[1,1], [1, -1], [-1, 1], [-1, -1]]
result = [[1], [-1], [-1], [1]]

with model:
    a = nengo.Ensemble(neurons=100, dimensions=2)
    xor = nengo.Ensemble(neurons=50, dimensions=1)
    nengo.Connection(a, xor, eval_points=points, decoder_result=result)
```

or possibly this, which is closer to the old syntax for doing this:

```python
with model:
    a = nengo.Ensemble(neurons=100, dimensions=2)
    xor = nengo.Ensemble(neurons=50, dimensions=1)
    nengo.Connection(a, xor, eval_points=points, function=result)
```

I'm not sure which approach would be preferred (allowing function to be either a callable or an array versus adding a new parameter).

Either way, this type of Connection would need to raise an Exception if pre is a Node or is an Ensemble running in Direct mode.

**Comment by hunse** [comment]
Reopening this exactly two years later! I'm starting to do some stuff with MNIST in Nengo, and using the dictionary approach, it's not super fast (6 seconds with 10000 training images, 32 seconds with 60000, just for turning the eval points back into an array of target points that I already had to start with). If we scale up to larger data sets (possibly with greater than 1 million data points) with larger dimensionality (so hashing the tuple will take longer), this could become burdensome. So I think it's worth it to build something like this in. It might make Nengo an easier sell to the ML crowd, too, since this is the kinda thing they love to do, and it would great to have it be easy and fast.

**Comment by drasmuss** [comment]
This is in master now.
