### ISSUE TITLE
Fixing setup.py's .egg file

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#439]
Right now, the .egg file produced by doing `python setup.py bdist_egg` is broken.  One issue is that the `packages=` line should include `nengo.utils` and `nengo.spa` (and possibly their tests).

The other issue that I'm not sure how to fix is this:

```
terry@terry-Ubuntu1310:~/Downloads$ sudo easy_install nengo-2.0.0-py2.7-2014-07-01.egg 
Processing nengo-2.0.0-py2.7-2014-07-01.egg
creating /usr/local/lib/python2.7/dist-packages/nengo-2.0.0-py2.7-2014-07-01.egg
Extracting nengo-2.0.0-py2.7-2014-07-01.egg to /usr/local/lib/python2.7/dist-packages
Adding nengo 2.0.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/nengo-2.0.0-py2.7-2014-07-01.egg
Processing dependencies for nengo==2.0.0
Searching for nengo==2.0.0
Reading http://pypi.python.org/simple/nengo/
No local packages or download links found for nengo==2.0.0
error: Could not find suitable distribution for Requirement.parse('nengo==2.0.0')
```

What happens is that it seems to install fine, but then dies trying to recognize itself.  I'm not sure what's happening here.

(Also, the `license="GPLv3"` line should be changed to something...)

**Comment by tbekolay** [comment]
OK, following up from the dev meeting, I built a Nengo wheel and can confirm it works. Here's what I did:

```bash
workon nengo
pip install --upgrade pip
pip install wheel
mkdir ~/.wheels
pip wheel --wheel-dir="$HOME/.wheels"
```

The `.wheels` directory then contained `nengo-2.2.1.dev0-py2-none-any.whl` (note that it's `none` because Nengo is pure Python and doesn't require a compilation step) and `numpy-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl`.

To test that the wheels actually worked I did:

```
mkvirtualenv tmp
pip install --no-index --find-links="$HOME/.wheels" nengo
```

NumPy and Nengo installed in no time; when I started up an interpreter I could import `nengo.spa.tests` and any other module that I would expect to be there, so I think everything worked out. Also, `nengo.__version__` was `'2.2.1.dev0'`, so it was actually using the wheel, not a version downloaded from PyPI.

So, I think our `setup.py` is set up correctly at the moment! We might consider releasing wheels in the future, though since we are pure Python it's likely not critical.
