### ISSUE TITLE
Run PEP8 on iPython notebook examples

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#495]
Apparently, it's not that hard to run PEP8 [inside an iPython notebook](https://stackoverflow.com/questions/26126853/verifying-pep8-in-ipython-notebook-code) or even [after it's been exported](https://stackoverflow.com/questions/26205629/verifying-pep8-in-exported-ipython-notebook-code). It would be a good exercise for a noob to walk through the examples and fix some of the weird uses we have of reserved keywords. That being said, I am aware of #283 where it was concluded that some words were necessary.

**Comment by mgserafi** [comment]
@Seanny123 , I see it's been 2 years since this PR was open. Have you tried running `pep8_magic` since then (the first link for running PEP8 inside a notebook)? I get a permission error when trying to use it.

**Comment by jgosmann** [comment]
Does the error message give any other details? (like a filename or what kind of permission is required)

**Comment by mgserafi** [comment]
When I have `%%pep8` in a cell, I get this error:

`INFO:pep8: ...\AppData\Local\Temp\tmp67jjo44b:1:1: E902 PermissionError: [Errno 13] Permission denied: '...\\AppData\\Local\\Temp\\tmp67jjo44b'`

I'm currently using Jupyter 4.1.0 and ipython 5.1.0

**Comment by mgserafi** [comment]
Managed to get another method for running pep8 on notebooks to work. However, there don't seem to be anymore reserved keyword errors.
All the pep8 errors are based on spacing issues (i.e. blank lines with white spaces, trailing white spaces, missing spaces around operators, etc). Not sure if it's worth fixing all of these...

**Comment by Seanny123** [comment]
So it turns out `pep8` doesn't catch using reserved keywords and that actually has to do with `pylint`. If you check the `.pylintrc` file, you see that we don't even warn on that. @tbekolay what do you think about changing the `.pylintrc` file to also catch use of built-ins?

That being said, I still think it's worth fixing the spacing issues. If this is tedious to do, there should be a way to just automatically fix it and review the results.

**Comment by jgosmann** [comment]
> If you check the .pylintrc file, you see that we don't even warn on that.

I think, we're only checking for missing `super` calls in constructors. At some point one should go through and figure out the set of pylint warnings that is useful for us. But until then it should be fine to add more rules on a case by case basis. So the question is if we want to have a hard rule prohibiting built-in names? In networks we're doing things like `self.input` were at least my syntax highlighter thinks the `input` part is a built-in. I don't think we should warn about those cases because we're not actually overwriting a built-in.

> That being said, I still think it's worth fixing the spacing issues. If this is tedious to do, there should be a way to just automatically fix it and review the results.

That should only be a matter of writing the correct regex. I could take a stab at it when I have some free time.
![xkcd](https://imgs.xkcd.com/comics/regular_expressions.png)

**Comment by Seanny123** [comment]
> So the question is if we want to have a hard rule prohibiting built-in names? In networks we're doing things like self.input were at least my syntax highlighter thinks the input part is a built-in. I don't think we should warn about those cases because we're not actually overwriting a built-in.

That's a syntax highlighter quirk that wouldn't be caught by `pylint` which allows for things like `self.input` according to my tests.

> That should only be a matter of writing the correct regex.

There's a tool called `autopep8` that does this for you.

**Comment by jgosmann** [comment]
> There's a tool called autopep8 that does this for you.

But does it work on the notebooks?

**Comment by mgserafi** [comment]
Found a [jupyter-autopep8 extension](https://github.com/kenkoooo/jupyter-autopep8), which i'll try.

**Comment by mgserafi** [comment]
So this extension works really well. There's some cases where I'm wondering if anyone has a preference. Here's what one of the cells currently looks like:

![image](https://cloud.githubusercontent.com/assets/18017580/22756787/522fccce-ee16-11e6-8a39-1a3f30c6104b.png)

Some of the lines here are longer than the x characters length for PEP8. After using autopep8 on it:
![image](https://cloud.githubusercontent.com/assets/18017580/22756802/6062cb3e-ee16-11e6-9d7d-e4d27297c006.png)

Only the cells that are longer than x characters are adjusted. I was wondering if anyone has objections to me leaving cases like this unfixed, keeping the format of these lines consistent instead of using the autofixed version. Alternatively I could change the shorter lines to have the same format, as seen below:
![image](https://cloud.githubusercontent.com/assets/18017580/22756836/7784b23c-ee16-11e6-9c56-8ec7e48731a3.png)

**Comment by tbekolay** [comment]
For long lines, I do the following until one of them results in all lines less than however many characters:

1. Line break after the first parenthesis:

   ```python
   plt.plot(
       sim.trange(), sim.data[input_a_probe], label="Input A", color='k', linewidth=2.0)
   ```

2. Line break after the first argument, then after all other arguments:

   ```python
   plt.plot(sim.trange(),
            sim.data[input_a_probe],
            label="Input A",
            color='k',
            linewidth=2.0)
   ```

3. Line break after the first parenthesis and after each argument:

   ```python
   plt.plot(
       sim.trange(),
       sim.data[input_a_probe],
       label="Input A",
       color='k',
       linewidth=2.0)
   ```

Seems like `autopep8` goes straight for 3 without checking the other two... probably that's better than super long lines though!

**Comment by jgosmann** [comment]
Vertical scrolling can also get annoying ... but it's still better than horizontal scrolling.

**Comment by Seanny123** [comment]
The next step to resolve this issue is to run the PEP8 validation automatically as a part of TravisCI.

**Comment by drasmuss** [comment]
This was done in https://github.com/nengo/nengo/commit/fd5066c39bc684cda022f8a722dcecd225e8174c
