### ISSUE TITLE
Syntax for "modulatory" connections

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#531]
To implement Gruber neurons (see #530 ), we need a way to form a connection into an Ensemble that will affect its dopamine input.  I can't remember a decision on the syntax for this....

One possible option:

``` python
a = nengo.Ensemble(n_neurons=100, dimensions=1, neuron_type=nengo.Gruber())
b = nengo.Ensemble(n_neurons=100, dimensions=1)
nengo.Connection(b, a.dopamine) 
```

This might also lead to syntax that lets you control the dopamine levels per-neuron:

``` python
a = nengo.Ensemble(n_neurons=100, dimensions=1, neuron_type=nengo.Gruber())
b = nengo.Node([0]*100)
nengo.Connection(b, a.neurons.dopamine) 
```

Thoughts?

**Comment by tbekolay** [comment]
At the dev meeting today, we concluded that this issue is essentially the same core issue as is currently being discussed in https://github.com/nengo/nengo/issues/427#issuecomment-255850317. In that issue, changing the `learning_rate` of `LearningRule` is being discussed, which is essentially the same as changing the `dopamine` level of a `Neurons` object.

 If you're interested in this issue, then please go there and weigh in.
