### ISSUE TITLE
Adaptive neurons don't give a custom rate approximation

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#540]
Right now, when nengo computes decoders, it uses the rate approximation of the neuron model.  For AdaptiveLIF neurons, this means that it falls back on using the LIF rate approximation.  This means that the decoder will assume no adaptation occurs.  In Nengo 1.4, the AdaptiveLIF neuron had a rate approximation that indicated what the steady-state firing rate would be after adaptation, and the decoders were trained using that.  This meant that Ensembles would have a good steady-state response.

**Comment by fragapanagos** [comment]
I have a [notebook](http://nbviewer.ipython.org/github/fragapanagos/notebooks/blob/master/neuron/adaptive_LIF_neuron.ipynb) in progress that examines the adaptive neuron. @tcstewar indeed there is no analytic solution as shown [here](http://nbviewer.ipython.org/github/fragapanagos/notebooks/blob/master/neuron/adaptive_LIF_neuron.ipynb#Steady-state-firing-rate).  Besides the magical "20" constant, there's also a problem with the magical "0.1" constant. It will lead to incorrect firing rates near threshold as shown [here](http://nbviewer.ipython.org/github/fragapanagos/notebooks/blob/master/neuron/adaptive_LIF_neuron.ipynb#Do-not-use-this-method-to-find-the-firing-rate-with-mean-feedback-approximation). Instead of iterative approximation using the mean feedback value approximation, you can use the bisection method  (binary search, also iterative) to find the exact firing rate as written [here](https://github.com/fragapanagos/notebooks/blob/master/neuron/utils/neuron.py#L118) (below it, [here](https://github.com/fragapanagos/notebooks/blob/master/neuron/utils/neuron.py#L189) is a version that uses scipy's bisection method).

**Comment by fragapanagos** [comment]
The neuron model at https://github.com/Stanford-BIS/nengo_alif_steady_state addresses this issue. Should this issue be closed now?

**Comment by fragapanagos** [comment]
@tcstewar for the neuron model at the above repository to work, it requires the membrane voltage clip parameter in the LIF math. Could that be introduced in the standard nengo LIF?

**Comment by tcstewar** [comment]
> it requires the membrane voltage clip parameter in the LIF math. Could that be introduced in the standard nengo LIF?

Oops, I missed that...  I'll go poke at that (although it'd also be nice to have a test that would fail if the clipping wasn't happening). :)

**Comment by fragapanagos** [comment]
Good point. I added a test in https://github.com/Stanford-BIS/nengo_alif_steady_state/commit/cc5f56818d2566e2e68d79d35fb7b414977eb954 to check that membrane voltage is allowed to go negative.

**Comment by fragapanagos** [comment]
https://github.com/Stanford-BIS/nengo/blob/ss_alif/nengo/neurons.py implements the clipping parameter. Specifically, in LIF.__init__ and AdaptiveLIF.__init__

**Comment by tbekolay** [comment]
I can confirm that https://github.com/Stanford-BIS/nengo_alif_steady_state still works with the the current version of Nengo. I'm going to close this, as it's been implemented, but with the `document this` label added so that eventually we'll point to https://github.com/Stanford-BIS/nengo_alif_steady_state somewhere in documentation.
