### ISSUE TITLE
Behaviour of synapse=None on other backends

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#544]
Reference nengo implements synapse=None differently than synapse=0.  synapse=None is a zero-time-step delay, while synapse=0 is a one-time-step delay.  This is extremely cool, and is what allows us to use passthrough Nodes correctly.

However, this feature is not something that is possible on all backends.  Currently on SpiNNaker and Neurogrid (and BrainStorm) we get almost the same behaviour by doing the "remove_passthrough_nodes" trick, which eliminates passthrough nodes, collapsing together most of the Connections with synapse=None.

After removing passthrough nodes, there may still be Connections with synapse=None on them.  Most of the time these will be connections to/from Nodes.  In those situations, I think it is valid for a backend to treat synapse=None like synapse=0 (or whatever is most appropriate for that backend).  Whether or not there's a one-time-step delay on a synapse should be something that backends are free to set for themselves, since it's something that's very hardware-dependent.

However, there's one very odd case that I'm not sure how to handle: cycles with synapse=None.  Reference Nengo raises an Exception at build-time in these cases:

``` python
with model:
    a = nengo.Ensemble(10, 1)
    nengo.Connection(a, a, synapse=None)

with model:
    a = nengo.Ensemble(10, 1)
    b = nengo.Ensemble(10, 1)
    nengo.Connection(a, b, synapse=None)
    nengo.Connection(b, a, synapse=None)
```

Right now, neither the SpiNNaker nor the Neurogrid backends raise an Exception here, and, indeed, it would be pretty hard for them to do so.  Instead, they just treat those exactly like synapse=0.

So, the question is what is the desired behaviour here?  Should backends be free to decide raise an Exception or not in this scenario?  That feels a little weird, since we could end up with models that only run on one backend but not another.  But does that then mean that every backend needs to do this graph loop check and raise an Exception, even if they're perfectly capable of implementing it?  Or should we change reference nengo to notice these loops and change synapse=None to synapse=0 on one of the Connections in the loop?  If so, which one?

**Comment by tbekolay** [comment]
It was decided at the dev meeting that this isn't a serious issue at the moment (as SpiNNaker now deals with `synapse=None` in a similar way as the reference sim), but there is an inconsistency since reference Nengo disallows cycles, but SpiNNaker is okay with them.

This will hopefully be rectified in the future when the builder is refactored. I couldn't find an existing issue for the builder refactoring stuff, so it's possible it's just something we all have in our heads but isn't in the repo... I made #1189 so that we have something to point to now. So go there if you want to add anything to that discussion!
