### ISSUE TITLE
Probe of Connection to slice returning all of target's dimensions

### ISSUE THREAD

**Issue by fragapanagos** [nengo/nengo#549]
The following script probes a connection which only connects to a single dimension of a target.  

```
import nengo

model = nengo.Network()
with model:
    ens = nengo.Ensemble(10, 3)
    node = nengo.Node(lambda t, x: x, size_in=3)
    conn = nengo.Connection(ens, node[0], function=lambda x: x[0]*x[1]*x[2])
    p = nengo.Probe(conn)

sim = nengo.Simulator(model)
sim.run(.005)
print sim.data[p]
```

I would expect the probe to only contain the Connection's single dimensional output, but the Connection Probe output is 

```
[[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.00673963  0.          0.        ]
 [-0.01006207  0.          0.        ]
 [-0.00823812  0.          0.        ]]
```

**Comment by tbekolay** [comment]
We've made some under-the-hood changes and improved connection probing significantly since this issue was made two years ago. Running the snippet above now gives what @fragapanagos wanted:

```
[[ 0.        ]
 [-0.01395269]
 [-0.01142349]
 [-0.00935277]
 [-0.0076574 ]]
```

This is because by default we probe the output of the connection now. `nengo.Probe(conn)` is equivalent to `nengo.Probe(conn, "output")`.

With that I think this can be closed!
