### ISSUE TITLE
Passing Config object to Simulator

### ISSUE THREAD

**Issue by fragapanagos** [nengo/nengo#561]
The user can pass a pre-configured Config object to the Simulator in the neurogrid and spinnaker backends for them to use during their build process. 
Is there a way to do something similar in the standard nengo backend? I would like to run multiple simulations using different Config objects (to say, set different defaults) instead of changing the Network's Config attribute with each simulation.

**Comment by tbekolay** [comment]
The suggested solution above was implemented in `nengo_spinnaker` over a year ago now ;) (see https://github.com/project-rig/nengo_spinnaker/commit/c0c7edc57c38bf297208239de8ca5685151cee79) I'm going to close this issue with the `document this` label so that we include this standard in the backend developer documentation that we will probably one day eventually write.
