### ISSUE TITLE
References for builder

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#572]
The builder code is a pretty intense piece of code. Documentation for it's basic flow and general background would be pretty cool to include in the dev docs. I would add them myself, but having not read Neural Engineering yet, I wouldn't know where to start.

As for the reference, is the only acceptable reference the whole book or are there parts of it (or Terry's notes) that are particularly relevant?

**Comment by tbekolay** [comment]
What is currently in the builder has [some documentation now](http://pythonhosted.org/nengo/backend_api.html#the-build-process); more documentation and prose will be added in the builder refactoring PR #1189. As for adding references, I think the builder code can safely assume that the reader is familiar with the NEF... if they aren't, looking through the builder is not likely a good place to start. There are a few good starting places for learning NEF stuff, which we should maintain a list of in in nengo.github.io (see https://github.com/nengo/nengo.github.io/issues/9). When that list exists we could consider pointing to it in the builder, but I don't consider it a high priority.

Closing this now since I referenced #1189, effectively merging this issue with it!
