### ISSUE TITLE
Document official API spec

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo#614]
This occurred to me in #613; we should probably have a document laying out exactly what the Nengo API is (the syntax that every backend should support).  I think the idea was originally that Nengo reference would serve as that documentation, but it has expanded to the point now where there are a lot of "extras" in there, and it's not immediately obvious which features are core and which are not.  With the official release, this seems like a good time to lock this down (since hopefully the API won't be changing very much from now on).  

An ipython notebook would probably be a good way to do this, since we could include examples of the syntax.  The notebook would also serve as a test that people could run to make sure they're supporting all the required syntax.

**Comment by tcstewar** [comment]
+1 

One thing that would be very nice would be to have sets of things that are optional for a backend to support (like learning rates, or particular neuron models), and some way of asking a backend which of those things it supports.

**Comment by tbekolay** [comment]
Hmm... What do you think about adding this information to docstrings instead? We will already be generating autodocs of all of the classes/functions; it seems to me to be less work (since we'll be updating docstrings anyway) to add something to all backend-specific stuff that this particular thing may not work in all backends.

**Comment by tcstewar** [comment]
Other things backends might not support (based on things that have come up with SpiNNaker and Neurogrid):
 - Connections from Neurons (bypassing decoder)
 - Connections to Neurons (bypassing encoder)
 - Probing voltage or other Neuron details (or the input to Ensembles, or other such things)
 - Synapses other than Lowpass()
 - Connections into an Ensemble with synapse=None (or outside of some range)

**Comment by drasmuss** [comment]
Yeah if we could generate this information automatically that would be ideal, so that it's all kept in sync.  But I think our core API is pretty small, relative to the overall Nengo documentation.  So it would be nice to have some compact "core" documentation, so that people don't have to hunt through everything trying to pick out the core features.

**Comment by hunse** [comment]
I like the idea of being able to query a backend to see exactly what it supports (though I'm not quite sure how this would actually work). It would be cool to do things like skip tests for things that aren't supported by a backend.

**Comment by tbekolay** [comment]
> I think our core API is pretty small, relative to the overall Nengo documentation

Possibly! In that case, rather than point out backend-specific things, we should have a section for what all backends are assumed to support. We could make a doc page that accumulates all of those sections into one place, I think...

**Comment by tcstewar** [comment]
> > I think our core API is pretty small, relative to the overall Nengo documentation
> Possibly! In that case, rather than point out backend-specific things, we should have a section for what all backends are assumed to support. We could make a doc page that accumulates all of those sections into one place, I think...

That feels right to me.  It also kind of echoes the process I've been going through writing backends: Start with the very core functionality of Ensembles, Nodes, and Connections (with no Neurons and no Probes) and build up from there (or add things to the builder that take the more complex things in the API and converts them into these basic things).

**Comment by drasmuss** [comment]
I think it might be difficult to do this just through docstrings.  The problem is that we would have two competing goals.  For the core API documentation, we want to describe things in a general fashion, without reference to the non-core features.  The `nengo` docstrings, on the other hand, should describe that specific backend implementation.  So we either end up with overly general or overly specific docstrings, depending on which we try to fit.

**Comment by hunse** [comment]
> we should have a section for what all backends are assumed to support

Isn't this what @drasmuss initially proposed, but with a notebook? I think I prefer the notebook idea.

**Comment by tcstewar** [comment]
One other thing that would fit well in this spec is an indication as to what backends are expected to do.  For example, I think that:

 - If a backend is asked for a particular neuron_type, it should just treat that as a suggestion and if it can't do that exact neuron_type it can fall back on whatever it chooses as the closest equivalent (e.g. Neurogrid)
 - Nodes are expected to be called as fast as possible, but backends do not guarantee that they will be called every timestep (e.g. SpiNNaker)

**Comment by tbekolay** [comment]
Hm. I think it's not clear to me what would be in this notebook, and who the audience is. There isn't a nice, clear cut distinction between things in and out of the API; is anything that is not backend-specific part of the "core API"? Because if so, there are a lot of things in the core API. If it's not all backend-specific stuff but things like `Ensemble`, `Connection`, then are we unintentionally recommending that people not use things like `nengo.utils.probe.probe_all`, even though it would work on any backend that implements probes?

If this is a notebook aimed at backend designers, then I misunderstood this thread from the start!

**Comment by tcstewar** [comment]
> Hm. I think it's not clear to me what would be in this notebook, and who the audience is.

For me, it's about indicating that there's a lot of things that can be built with the nengo API (i.e. everything that you do to define the model before passing it to the Simulator for whatever backend you're using).  Not all of those things are supported by every backend.  It'd be nice to indicate that there is a core set of features that we expect every backend to support, and a set of optional features that might not work on every backend.  This would be useful information both for someone using the nengo API to build networks (since they may be wanting to run them on some particular backend), and it would be useful for backend developers (so they can decide what features to target).  

For example, I'd expect every backend to support this:

```python
model = nengo.Network()
with model:
    stim = nengo.Node(np.sin)
    ens = nengo.Ensemble(100, 1)
    nengo.Connection(stim, ens)
```

but I wouldn't expect every backend to support something with a LearningRule, or an Izhikevich neuron, or a Probe on an Ensemble's voltage.  But we should specify what would happen when a backend encounters something it can't support.  If asked to do a LearningRule it can't do, it should probably throw an Exception.  For an Izhikevich neuron, it might fall back on a simpler model.  For a Probe on voltage, maybe it should just do an empty probe (i.e. no data appears).

**Comment by drasmuss** [comment]
Yeah, to me this document would specify two things
1) What syntax is guaranteed to work on any backend.  This would be useful for model designers, so that if they want their model to be able to run cross-platform they know what syntax to restrict themselves to.
2) What syntax must every backend support.  This is useful for backend designers, so they know the minimal structure they need to implement.

I think I would leave out the "recommended" or "optional" things that @tcstewar mentions, just so that this document can be as bare bones and concise as possible.  We should document those things as well of course, I'm just thinking of this piece more as the minimum requirements document.

**Comment by hunse** [comment]
For me, the notebook would show most of the things that can be done with the core Nengo objects (Network, Node, Ensemble, Connection, Probe, and probably EnsembleArray too). It wouldn't go into much if any of the stuff in `nengo.utils`.

The notebook would serve as a combination API-spec and demo of what can be done with basic Nengo. So the audience would be anyone new to Nengo, and wanting to get an idea of what it can do, without going into detail on how things are done or what everything means (i.e. no NEF). 

It would also be useful for someone starting to design a backend to say "this is what we need to support", and possibly use the notebook as a basic test of the backend. I would like to make it difficult to support the things in the notebook while not supporting some core API feature (since it **will** be impossible to put every core API thing in the notebook, including every possible type of connection, etc.). It may be possible to run the notebook error-free but still have bugs with core API features (that's what the unit tests are for), but I don't want someone to make a backend that supports the notebook and then realize "oh, I forgot about that feature, it's going to be annoying to add that in now."

Maybe this is trying to kill too many birds with one stone, but that's what I have envisioned.

**Comment by tbekolay** [comment]
Hmm... to me @drasmuss's 1 and 2 don't overlap very much; mostly, because whether something works on a backend or not isn't typically an issue of syntax and API calls, but on the content of those API calls. E.g., all backends can make connections between ensembles, but not to neurons, etc.

I wonder if what you guys want already exists? There's a [getting started](https://dl.dropboxusercontent.com/u/6182929/nengo/getting_started.html#usage) section in the updated docs... If these are very introductory things that you want mentioned, then it's more appropriate in the docs than in some example notebook.

**Comment by drasmuss** [comment]
I was thinking my 1 and 2 were synonymous, just different ways of saying the same thing.  I would include "the content of the API calls" as part of the syntax.  E.g., if `nengo.Connection(a.neurons, b.neurons)` is not something that every backend has to support, then it wouldn't be part of this document.  And modellers would know that if they have a `nengo.Connection(a.neurons, b.neurons)` line in their model, that may not work on every backend.

And yeah, I think the "getting started" guide fits what @hunse has in mind, but I would say that is different than what I was thinking.  That is, this isn't a document we would necessarily direct new users to; we would be omitting a lot of the "convenience" features (e.g. `utils`) from this document, that are designed to make things easier for new users but are not necessarily something available in every backend.

**Comment by tcstewar** [comment]
> For me, the notebook would show most of the things that can be done with the core Nengo objects (Network, Node, Ensemble, Connection, Probe, and probably EnsembleArray too). It wouldn't go into much if any of the stuff in nengo.utils.

Ah, that's completely not what I was thinking for this spec.  After all, things like EnsembleArray don't even exist by the time the backend gets involved, so there's absolutely no dependency between EnsembleArray and backends.  The same is true for a lot of the stuff in nengo.utils.  

It feels to me like the sort of thing you're describing would be more of a "getting started" guide, as @drasmuss suggests.

**Comment by tcstewar** [comment]
> That is, this isn't a document we would necessarily direct new users to; we would be omitting a lot of the "convenience" features (e.g. utils) from this document, that are designed to make things easier for new users but are not necessarily something available in every backend.

One thing to keep in mind is that *everything* in ```utils``` is available in every backend, since they get it all by doing ```import nengo```.  So, for instance, every backend can automatically use ```utils.connection.target_function()```, since as far as the backend is concerned it's just another function.  There are a few things in there that are specific to the reference simulator (which maybe should get moved), but those seem like the exception to me.  Still, we certainly don't have to specify in this document that backends need to support Connections with ```function=support utils.connection.target_function()```; we just say that we expect all backends to support Connections with whatever function is specified.

**Comment by drasmuss** [comment]
I think `utils` is kind of a hodgepodge of utility functions now, with no guarantees about platform independence and minimal organization (that's why they're being stuck in `utils` in the first place).  E.g., there's stuff in there for the cache, progress bar, and so on that we wouldn't expect to work on every backend I don't think.  I would probably just say everything in `utils` is "unofficial", and leave it up to the user (or a separate `utils` documentation) to figure out which ones are safe since they are invisible from the backend's perspective.  But anyway, these are the kinds of questions that this document would hope to clarify.

**Comment by drasmuss** [comment]
>Still, we certainly don't have to specify in this document that backends need to support Connections with function=support utils.connection.target_function(); we just say that we expect all backends to support Connections with whatever function is specified.

Basically that's what I mean, you just said it more concisely :stuck_out_tongue_winking_eye:

**Comment by hunse** [comment]
> so there's absolutely no dependency between EnsembleArray and backends

That doesn't mean that there aren't things that are easier to test with EnsembleArrays. For example, EnsembleArrays use advanced slicing, which could just be shown by itself, but it might be easier to test as part of an actual EnsembleArray. I'm not saying it's necessary that we put them in; it's definitely not.

What I'm suggested is different from a "Getting Started" document, since that will go through step-by-step and explain things more. I was thinking of this more as a "this is what you can do with Nengo" document, that will produce some pretty plots, and be something that you could show to someone in a few minutes to highlight the things that Nengo can do. It wouldn't really teach the user *how* to do anything, just show off what they will be able to do once they learn Nengo (a demo).

As I said, perhaps it's too much to try and do this in the same document that is also supposed to be the core API spec. When I was thinking about what would go in the API spec, a lot of the examples that came to mind also seemed like good "demos" of Nengo's functionality. For example, we'll want to show that we can do neuron-neuron connections as well as decoded connections. But maybe the API spec will end up being too long and containing things that don't really fit in a demo, so it might be easier to build a demo notebook separately, or steal a few key examples from the API spec. A demo notebook just seems like a good thing to have.

**Comment by tcstewar** [comment]
> But maybe the API spec will end up being too long and containing things that don't really fit in a demo, so it might be easier to build a demo notebook separately, or steal a few key examples from the API spec. A demo notebook just seems like a good thing to have.

I definitely agree with this.  A demo notebook like that would be great, but separate from this spec.

**Comment by Seanny123** [comment]
Is this resolved by the creation of [Nengo Distilled](https://github.com/nengo/nengo_distilled)?

**Comment by tbekolay** [comment]
> Is this resolved by the creation of Nengo Distilled?

Hmm... I would say no, as a source tree isn't super easy to refer to as documentation. I could envision an annotated source code-style documentation growing out of Nengo distilled though (a la [backbone.js](http://backbonejs.org/docs/backbone.html)).

**Comment by tbekolay** [comment]
Reminder: do in #1189

**Comment by drasmuss** [comment]
After some internal discussion, our plan for this is to have backends clearly document the features that they don't support (relative to nengo core).  That is a smaller and more well-defined list, rather than trying to predict and document all the possible features of nengo core that backends may or may not support.  So I'll close this issue in favour of those more specific documentation issues we've created for other repos.
