### ISSUE TITLE
Suggest installing numpy manually on windows

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#637]
Following the instructions at https://pypi.python.org/pypi/nengo on a windows machine without numpy doesn't work.  You get an error message like

http://imgur.com/kiDZGmG

Instead, we should say that Windows users should manually install numpy (and scipy) by downloading them from http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by Seanny123** [comment]
Is editing the README a good enough solution to this issue for the next release or where you hoping for something fancier?

**Comment by tcstewar** [comment]
And making it clear on nengo.ca and anywhere else we have instructions.  :)

**Comment by Seanny123** [comment]
It's already been added to Nengo.ca and I've tried to address this as part of #683

**Comment by tcstewar** [comment]
Hmm... looking at the instructions you have in #683 and the instructions at https://pythonhosted.org/nengo/getting_started.html#installation I'd say both of those should be changed to give the same sort of instructions as are currently at nengo.ca.

**Comment by Seanny123** [comment]
Just to make sure I understand, you don't like the idea of installing Numpy
manually as a backup plan and would rather it was mentioned as a
pre-requisite as it is at Nengo.ca?

**Comment by tcstewar** [comment]
> Just to make sure I understand, you don't like the idea of installing Numpy
> manually as a backup plan and would rather it was mentioned as a
> pre-requisite as it is at Nengo.ca?

Sorry, I wasn't very clear on this.  Basically, right now the instructions on nengo.ca are meant to be followable both for Python experts and Python novices.  For an expert who already has python and numpy installed, you just do pip install.  For a novice, you install Anaconda, go to the anaconda command prompt, and then do the pip installing.

In the README that you've got as #683, you say:

```
If you're on Windows, you'll need to install Numpy first. Using Anaconda or
the official installer and unofficial binaries <http://www.lfd.uci.edu/~gohlke/pythonlibs/>
```

For a Python novice, this doesn't help much (aside from it being grammatically incorrect).  For example, if a novice installs Anaconda and then tries to do "pip install nengo", where do they type that in?  It's not obvious that you have to go to the Anaconda Command Prompt first.  That sort of thing is what I was trying to make clear in the nengo.ca instructions.

As for installing numpy manually, I think I'd prefer something that makes it clear that approach is for people who know what they're doing.  Even trying to use the unofficially binaries on windows is problematic now, because you no longer do it by downloading an .exe and running it.  Now you download a .whl file and then open a command prompt, go to that directory, and then do ```pip install <filename.whl>```, which is much more complicated for novices.  So I'd stick with just instructions for two cases:

1) If you already have Python and NumPy installed (or know how to install them on your computer yourself), then just do

```
pip install nengo
pip install nengo_gui
```

and then ```nengo_gui``` to run it.

2) If you don't have Python and NumPy already installed, then download Anaconda, install it, go to the "Anaconda Command Prompt" and do the same thing.

**Comment by hunse** [comment]
Installing Numpy isn't really our business. Ideally, there would be good install instructions for all platforms hosted on the Numpy documentation, which we could link to. In lieu of that, we could either find some other good comprehensive instructions, or host our own on `nengo.ca`. In any case, I think the README should just link to those instructions, where-ever they are.

Since it sounds like there might be other dependencies that need some instructions, as well as some general instructions about Anaconda if people go that route, perhaps it's best to have a "Installing Nengo dependencies" in our docs (which would of course appear on `pythonhosted.org`), which we can then link to from the README and `nengo.ca`. I think the biggest thing is to keep everything in one place, otherwise we'll probably forget to update one location or the other. The other nice thing is if it's in the docs then it's easy to distribute as an offline HTML or PDF, if we're installing without internet.

On a mildly related note, is it possible to have our release ZIP files contain built versions of the docs, and maybe even versions of the notebooks converted to `.py` files?

**Comment by tbekolay** [comment]
> is it possible to have our release ZIP files contain built versions of the docs, and maybe even versions of the notebooks converted to .py files?

Possible! Make a separate issue perhaps?

**Comment by tbekolay** [comment]
Done in #683.
