### ISSUE TITLE
Cleanup network

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#646]
Looking through #79, I think we have networks for everything that was in 1.4 now. But, in that issue there was a request for a cleanup network, which we don't have in `nengo.networks`. If I understand `nengo.spa` correctly, the `AssociativeMemory` is essentially a cleanup network; does it make sense to make a generic version of this that doesn't require the cognitive load of SPA? Or do cleanups not make a whole lot of sense outside of SPA?

**Comment by jgosmann** [comment]
I think, in most cases you want to do cleanup in the context of SPA where you actually have a vocabulary of target vectors. But maybe there are some cases where some wants to cleanup some other vectors?

I wonder, how well is the `AssociativeMemory` tested in actual models? Whenever I tried to use it, I stopped using it because despite all tweaking it was just not working well (way too noisy, not sensitive enough). Afaik, @xchoo is also using a modified version I came up with to address at least the noisyness. During the last week I came up with another (recurrent) version which seems to be the best version yet, but I did only some quite basic (but promising) tests.

**Comment by jgosmann** [comment]
Some plots of WTA cleanup (works also without WTA):

Input:
![index](https://cloud.githubusercontent.com/assets/850157/6067447/a765bfee-ad42-11e4-9fbc-d835400f3f6b.png)

`AssociativeMemory`
![old](https://cloud.githubusercontent.com/assets/850157/6067458/b94067d2-ad42-11e4-98a8-b945941a6d3c.png)

New approach:
![new](https://cloud.githubusercontent.com/assets/850157/6067467/c83f5b26-ad42-11e4-9790-9c67e769fd40.png)

**Comment by celiasmith** [comment]
sweet! :smiley:

**Comment by jgosmann** [comment]
In the meantime [there appeared a more generic version of the associative memory](https://github.com/nengo/nengo/blob/master/nengo/networks/assoc_mem.py) as requested. So I'll close this issue.
