### ISSUE TITLE
py.test fails with existing build dir

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#650]
My `py.test` was failing with the following error:
```
(nengodev)ctn02:nengo|better-product> py.test                                                                                            ? d31f153795
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.9 -- py-1.4.26 -- pytest-2.6.4
collected 0 items / 1 errors 

======================================================================= ERRORS =======================================================================
_________________________________________________________________ ERROR collecting . _________________________________________________________________
../../../.pyenv/versions/2.7.9/lib/python2.7/site-packages/py/_path/common.py:334: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
../../../.pyenv/versions/2.7.9/lib/python2.7/site-packages/py/_path/common.py:380: in gen
    for p in self.gen(subdir):
../../../.pyenv/versions/2.7.9/lib/python2.7/site-packages/py/_path/common.py:370: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
../../../.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/main.py:628: in _recurse
    ihook.pytest_collect_directory(path=path, parent=self)
../../../.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/main.py:166: in call_matching_hooks
    plugins = self.config._getmatchingplugins(self.fspath)
../../../.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/config.py:688: in _getmatchingplugins
    plugins += self._conftest.getconftestmodules(fspath)
../../../.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/config.py:521: in getconftestmodules
    mod = self.importconftest(conftestpath)
../../../.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/config.py:545: in importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: (local('/home/jgosmann/Documents/projects/nengo/nengo/tests/conftest.py'), (<class 'py._path.local.ImportMismatchError'>, ImportMismatchError('nengo.tests.conftest', '/home/jgosmann/Documents/projects/nengo/build/lib/nengo/tests/conftest.py', local('/home/jgosmann/Documents/projects/nengo/nengo/tests/conftest.py')), <traceback object at 0x7f5ed0553b48>))
```
After I did `rm -r build` it was working again. I think, the existence of that directory should make no difference (and if it has to, the error message is not helpful at all).

Not sure if it has something to do with me using `pyenv` and `virtualenv`.

**Comment by tbekolay** [comment]
This always happens when you've actually installed `nengo`. Basically, when you start up `py.test`, it doesn't actually know what tests you want to run until you tell it. By default, it'll start from the current directory and scan all of the folders for `conftest.py` files, and then anything that matches the regex defined in `conftest.py` (or the default one, `test_*.py` or something like that).

What's happening here is that it's finding `conftest.py` in `build/lib/nengo/tests/` and `nengo/tests/`, and they're identical so it kind of blows up I guess.

The fix is to be explicit about what tests you want to run. I typically do `py.test nengo`. But if you want an invocation that works everywhere (you could be in `/tmp` for example) you can do `py.test --pyargs nengo` which will essentially look in you sitepackages for `nengo` and then collect tests from there.

**Comment by hunse** [comment]
This seems like a feature of pytest (searching all subdirectories for tests) that leads to problems when the build directory is there. I'm not sure if there's any fix beyond what @tbekolay suggests, so I'm going to close this as resolved.

Also, if you use `python setup.py develop`, the build directory never gets created, so this is not an issue. It's only when you use `python setup.py install`.

**Comment by jgosmann** [comment]
I found out that there is a fix. I'll reopen the issue and prepare a PR.
