### ISSUE TITLE
Plotter/Analytics fixture do not handle prametrized test functions properly

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#669]
Currently (I think, independent of whether PR #647 is merged) the plots or analytics files will be overwritten by a parametrized test function (`@pytest.mark.parametrize`). It would be nice to get different files for each parametrization. But I'm not sure how much effort we want to put into this as producing a sane filename from the parameters (which could be any Python object in theory) could be complicated.

In easy cases it might be easier to do individual test functions for each parameter set calling the actual implementing function. At least that's what I am doing for now (it's just three cases).

**Comment by hunse** [comment]
Currently for plots, we just manually name these files so they include the parameters and are therefore unique. I'd like to avoid individual test functions, since this seems even more manual than what we do now, and it could be difficult for tests that have a number of parameters. Something automatic would be great, but I can't think of an easy way to do it.

**Comment by jgosmann** [comment]
Can you link an example of what we do now?

**Comment by hunse** [comment]
[Here's an example](https://github.com/nengo/nengo/blob/master/nengo/tests/test_learning_rules.py#L194). You can grep for "saveas" in the tests to see more examples.

**Comment by jgosmann** [comment]
Nice, I didn't realize that this is possible. I'm satisfied with that. :cake:
