### ISSUE TITLE
How to reference a non-release version

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#694]
I am in the process of making my n-back model code public. I didn't run this model with an official Nengo release, but the `spaopt-v2` branch, more precisely with revision 8fb4eccb6bf5df6149988d0f251e73645347eb71.

1. What is the best way to reference this particular revision?
2. How do we ensure that it doesn't disappear (e.g., through history rewrites, rebasing, merging, etc.)?

Probably assigning a tag to that revision is the best option? Should we use a particular naming scheme?

**Comment by jgosmann** [comment]
Seems like no one cares :sleeping: 

I guess, I'll go with tags. But should I do that in the main repo? Or should I create a fork of Nengo in ctn-archive for this purpose?

**Comment by tcstewar** [comment]
Hmm..  I was at a talk at ICCM where someone commented that you can generate a DOI for a particular commit of a particular branch of a particular github repository, so I think that would be best...

Ah, here's the instructions:

https://guides.github.com/activities/citable-code/

**Comment by tbekolay** [comment]
Sorry, I started a reply to this but apparently didn't finish :P 

For a different repo, I've used a tag and a release to make it easy to find that tag. Technically, however, it's entirely possible to switch the commit that a tag refers to. If you think a reviewer would care, then you could reference the commit hash instead.

Another thing I've done (for a repo I didn't have commit access to) was to use a release version, and then monkey-patch the changes I needed to make in my own paper repository. So that could be an option.

But yeah, you could also just upload the code to figshare, or the thing that Terry linked to, as an alternative.

**Comment by jgosmann** [comment]
I don't think that just a DOI (or commit hash) is sufficient. It won't prevent me from rebasing the branch and making that particular commit disappear. With a tag that tag would still persist as long as I do not mess around with the tag.

But monkey-patching might be the best option here because it is not even monkey patching. I just have to copy the `spaopt` module and change my imports. :yum:

**Comment by hunse** [comment]
Shouldn't there be a way to tag a particular commit, such that if the commit gets orphaned (e.g. the branch is rebased), the tag still points to that commit and `git gc` won't remove it?

**Comment by jgosmann** [comment]
That's what I said:
>  With a tag that tag would still persist as long as I do not mess around with the tag.

But a DOI wouldn't ensure that.

**Comment by tcstewar** [comment]
> But a DOI wouldn't ensure that.

The link I gave does it by archiving the branch via http://zenodo.org/ , which is for sharing research.  Then you generate a DOI for that archive.

**Comment by hunse** [comment]
So I don't see what's wrong with a tag, then. You're not worried about this from a citing standpoint, right (i.e. it doesn't have to be guaranteed that it is unchanged since the time of publication)? You just want people who read your paper to be able to consistently find the right version of Nengo to run your model, which they should be able to do with a tag. While the tag could still be purposely overwritten, it's pretty much impossible to accidentally overwrite it. So go with a tag.

I think you can name it whatever you want, but it might help to connect to the name of your ctn-archive repo. The simplest might just be to name it "gosmann-cogsci2015".

**Comment by tbekolay** [comment]
The monkey-patch (or rather, including the code in the paper repository) approach has the benefit of being easier for the end-user (they don't have to clone / checkout / install a particular tag). Either way's fine with me though.

**Comment by hunse** [comment]
That's true, the monkey-patch is easier in that respect.

**Comment by jgosmann** [comment]
Yeah, I'm just including the code in the repository. That seems to be the easiest and cleanest solution. But I'll keep the other ideas in mind. Maybe they will be the better approach for some future project.
