### ISSUE TITLE
Node API redux

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#723]
To follow up on the discussion in #622 now that we have the Process stuff merged in, here's where we currently stand.

You can currently use the Process interface to define a nicely resettable Node that behaves nicely.  Here's what that looks like for making two Nodes: a Delay node and a Steps node that outputs a random sequence of values where each value is kept for a fixed amount of time:

```python
class Steps(nengo.processes.Process):
    def __init__(self, width):
        self.width = width
    def make_step(self, size_in, size_out, dt, rng):
        last_index = np.array([-1])
        last_value = np.zeros(size_out)        
        
        def step(t):
            index = int(t / self.width)
            if index != last_index:
                last_value[:] = rng.uniform(-1, 1, size_out)
                last_index[:] = index
            return last_value
        return step
            
class Delay(nengo.processes.Process):
    def __init__(self, delay):
        self.delay = delay
    def make_step(self, size_in, size_out, dt, rng):
        timesteps = int(self.delay / dt)
        history = np.zeros((timesteps + 1, size_out))
        
        def step(t, x):
            history[:] = np.roll(history, -1)
            history[-1] = x
            return history[0]
        return step
    
model = nengo.Network()
with model:
    stim = nengo.Node(Steps(width=0.1), size_out=1)
    delay = nengo.Node(Delay(delay=0.05), size_in=1, size_out=1)
    nengo.Connection(stim, delay, synapse=None)
    probe1 = nengo.Probe(stim)
    probe2 = nengo.Probe(delay)
```

The question is whether this is the syntax we want people to use to define custom Nodes like this.  The steps with this approach are:
 - you must inherit from ```nengo.processes.Process```
 - you must define a ```make_step(self, size_in, size_out, dt, rng)``` method
 - that method must create state variables and return a function that uses those state variables via the Python closure system (i.e. you are allowed to modify the contents of those variables but you are not allowed to overwrite them)
    - notice that in the Steps case this means doing slightly weird things like ```last_index = np.array([-1])``` instead of ```last_index = -1``` (or the even better ```last_index = None```).

## alternative 1: Use closures, but simplify the syntax a bit

One thing we could do is keep this closure approach, but adjust the syntax so there's fewer things to remember.  The two things that come to mind are:
 - we don't need to inherit from nengo.processes.Process, since we're not using anything from that.  And no one's come up with a good name for what these things should be (```NodeOutput``` is horrible).  
 - ```make_step``` is a bit weird: maybe ```build``` would be easier to remember
 - instead of ```size_in``` and ```size_out``` we can just pass the ```node``` in  (but ```dt``` and ```rng``` seem useful enough to me that we should keep them).

This makes the same model above look like this:

```python
class Steps:
    def __init__(self, width):
        self.width = width
    def build(self, node, dt, rng):
        last_index = np.array([-1])
        last_value = np.zeros(node.size_out)        
        
        def step(t):
            index = int(t / self.width)
            if index != last_index:
                last_value[:] = rng.uniform(-1, 1, node.size_out)
                last_index[:] = index
            return last_value
        return step
            
class Delay:
    def __init__(self, delay):
        self.delay = delay
    def build(self, node, dt, rng):
        timesteps = int(self.delay / dt)
        history = np.zeros((timesteps + 1, node.size_out))
        
        def step(t, x):
            history[:] = np.roll(history, -1)
            history[-1] = x
            return history[0]
        return step
```

## alternative 2: don't use closures

Instead of closures, we can have the ```build``` function set our variables and have the build system itself do a shallow copy of the object.  This allows the function to store data in ```self```, as in normal classes.  This means the object itself is ```callable```, so this use of a Node is somewhat similar to just defining a function.

```python
class Steps:
    def __init__(self, width):
        self.width = width
    def build(self, node, dt, rng):
        self.last_index = None
        self.rng = rng
    def __call__(self, t):
        index = int(t / self.width)
        if index != self.last_index:
            self.last_value = self.rng.uniform(-1, 1, self.last_value.shape)
            self.last_index = index
        return self.last_value
            
class Delay:
    def __init__(self, delay):
        self.delay = delay
    def build(self, node, dt, rng):
        timesteps = int(self.delay / dt)
        self.history = np.zeros((timesteps + 1, node.size_out))
    def __call__(self, t, x):
        self.history[:] = np.roll(self.history, -1)
        self.history[-1] = x
        return self.history[0]
```

Notice that if you don't need anything in the ```build``` step, you can leave it out, and everything just behaves like normal.  

However, one weirdness is that if someone does ```print self``` inside ```__call__```, they will not get the same object that they created.  That's because the builder has to make a shallow copy of the object so that the state can be kept distinct.

# decisions to make

To go forward on this, I think these are the basic decision points:

1) Should we subclass?  If so, what should we subclass from?  ```nengo.NodeOutput```? 
2) Should we use closures or not?
3) What should the ```build```/```make_step``` function be called?
4) What parameters should be passed in to ```build```?

My vote and reasoning are as follows:

1) We should not subclass.  We're just using it as a marker, and it's something that's easy to forget to do.  Inspecting the object for a ```build``` method seems good to me, and I can't think of a good name for what to call the base class
2) We should not use closures.  I keep going back and forth on this one, but being forced to do weird things like ```last_index = np.array([-1])``` instead of ```last_index = None``` changed my mind back again.  Having to remember to only modify variables rather than overwrite them is annoying and hard to explain, and is in addition to having to explain the idea of returning a function.
3) The function should be called ```build```.  It's short and easy to remember.  I could also see ```reset``` working (although it's less clear that it's also called at the beginning of the simulation).
4) The parameters should be ```node, dt, rng```.  That's the minimal set I can think of.  I could also see going with ```size_in, size_out, dt, rng``` but that's longer and I think there'd be cases where I'd like to have a handle to the node object.  My only worry is whether that causes a circular reference anywhere.

If people want to try it out, both of the above alternatives have been implemented in the https://github.com/nengo/nengo/tree/nodeoutput branch.  The implementation is really pretty short and easy, although I'm not sure what the Node.output setter validation should be for the closure approach without subclassing (if we decide on that approach).

Thoughts?

**Comment by tbekolay** [comment]
I have to admit that I'm happier with the current state of affairs than I thought I would be. If you look at the example processes (the first `Steps` and `Delays`), it looks like they're quite complicated, but these minimal examples are pretty compact for what it's doing, to my eyes. I'm also not too keen on forcing users to subclass, but we could easily remove that restriction and do a duck-typing check instead (i.e., make sure it has a `make_step` with the right args). I don't think that actually buys us much though, as either way the user is going to have to look up examples.

----

I am very against alternative 2, because of the shallow copy. The only real benefit to this approach is a slightly nicer syntax, but it's not a significant enough difference to deal with all the issues that the shallow copy introduces. I'm pretty unlikely to be swayed from this.

I'm also against alternative 1, but for less concrete, more sway-able reasons. Mostly, I feel uncomfortable having the node in the argument list. I think this is because of my mental model of nodes, which I will attempt to explain...

In my mind, the node is "in charge" of how this output that I'm passing will be treated. I pass a value into the node, and I'm expecting the node to provide that value when appropriate. I pass a function to the node, and I'm expecting the node to call it at the appropriate time with the right arguments when appropriate. Impressively, it actually does this, including figuring out the dimensionality of my output (except for the few edge cases where I have to specify it manually). Similarly with processes, I now have to give much more help to the node, but it's still the one that's doing the heavy lifting; it's calling the `make_step` function when it feels it needs to, it's passing in `t` to the step function, it's dealing with the backend simulator-y stuff that I don't want to deal with.

Seeing `node` in the argument list really messes with that mental model. If I want to pass in a stateful function, then I have to put `node` in the argument list. Why? What would I want to do with it? There must be some reason for it, if you're making me do it. Do I have to tell the node something about what I want it to do with my function in the simulation? I feel like having it in the argument list is Nengo telling me that there's something about nodes that I don't understand. It's available to me for a reason, so I should be doing something with it, but I have no reason to use it, so I must be doing something wrong. It makes me feel like I don't know how nodes work.

## Alternative 3: Make your own closures

Let me propose an alternative 3, before answering the more pointed questions directly. I'm personally fine with forcing people to deal with the weirdness that is closures, but if we really want to avoid closures, then here's one way to avoid them. We basically make our own closures, explicitly. Note that I think this example would work without any backend modifications to what we have now. It's also not necessarily something we have to force users to do, but it's something we could do in examples, and that we could recommend as best practice.

```python
class Steps(nengo.processes.Process):
    def __init__(self, width):
        self.width = width
    def make_step(self, size_in, size_out, dt, rng):
        return StepsFunction(self.width, rng)

class StepsFunction(object):
    def __init__(self, width, rng):
        self.width = width
        self.rng = rng
        self.last_index = None
    def __call__(self, t):
        index = int(t / self.width)
        if index != self.last_index:
            self.last_value = self.rng.uniform(-1, 1, self.last_value.shape)
            self.last_index = index
        return self.last_value

class Delay(nengo.processes.Process):
    def __init__(self, delay):
        self.delay = delay
    def make_step(self, size_in, size_out, dt, rng):
        return DelayFunction(self.delay, dt, size_out)

class DelayFunction(object):
    def __init__(self, delay, dt, size_out):
        self.timesteps = int(self.delay / dt)
        self.history = np.zeros((self.timesteps + 1, size_out))
    def __call__(self, t, x):
        self.history = np.roll(self.history, -1)
        self.history[-1] = x
        return self.history[0]


model = nengo.Network()
with model:
    stim = nengo.Node(Steps(width=0.1), size_out=1)
    delay = nengo.Node(Delay(delay=0.05), size_in=1, size_out=1)
    nengo.Connection(stim, delay, synapse=None)
    probe1 = nengo.Probe(stim)
    probe2 = nengo.Probe(delay)
```

Full disclosure, I haven't run this to ensure that it works.

The main downside of this is that now to get this working, you need to define two classes, which is honestly a lot of classes do something that, at the outset, seems like it should be straightforward (but isn't for what I think are good reasons).

The big advantage here, in my opinion, is that the closure classes that people would make are pretty close to what I think they would come up with by themselves without using Nengo; the actual `Process` subclass is a tiny little adapter class that is, yes, a little annoying to have to deal with the first time you see it, but after that is super easy to just copy and paste to another script because it's honestly tiny and simple (it's **just** the boilerplate that we need to make things resettable and usable in multiple models). For example, you could take Travis's arm model from the REACH repo, add a `__call__` to it, and write a four-line `Process` subclass to get it working robustly in Nengo. I think that's a pretty good state of affairs, and will annoy expert users the least (because they already know the stateful function they want to write; they just don't know how to hook it up to Nengo).

----

Okay, finally, responding to specific questions.

1) We have to either subclass, or use a magic function. They're kind of equivalent in my mind, so I'm cool with subclassing. I personally like the existing `Process` superclass, though I'm very open to alternatives.

2) I'm super opposed to the shallow copy. So it's either Python closures, or user-created closures with callable classes. I'm fine either way, though writing out alternative 3 made me like it more than I liked it when it was just in my head.

3) I could also be swayed here, but I think whatever we choose, we should keep consistent with the rest of Nengo. `make_step` made sense for `Process`, because that's the same name that we use in `Synapse`, and in all of our `Operator`s. All of these functions do very similar things, so I think keeping the names the same maintains that same-ness of what these functions do. I like `make_step` over `build`, as I feel `build` is a bit ambiguous (What are we building? Step functions? Then it's `build_step`, which seems pretty much the same as `make_step`)

4) I've made my case above for not having `Node` in the argument list. Without `node`, we need `size_in` and `size_out`, so we should have those in there. I actually think what we have in the existing `make_step` is pretty good.

**Comment by jgosmann** [comment]
1. I am slightly in favor of the magic function. It seems to be more in line with dynamic typing where usually one tests for behavior instead of relying on the specific inheritance.
2. Also, super opposed to the shallow copy. I have the feeling I can't even imagine all the ways in which this might go horribly wrong which frightens me. :fearful: 
3. I favor `make_step`. I think, everything `build...` has a different connotation in the code base.
4. `node` seems a little bit weird to me as argument.

### Alternative 3.5: Abstract boiler plate away
```python
# This class would be provided by Nengo
class Stateful(nengo.processes.Process):
    def __init__(self, fn_cls, **kwargs):
        self.fn_cls = fn_cls
        self.kwargs = kwargs

    def make_step(self, size_in, size_out, dt, rng):
        return self.fn_cls(size_in=size_in, size_out=size_out, dt=dt, rng=rng, **self.kwargs)

class Steps(object):
    def __init__(self, width, size_in, size_out, dt, rng):
        self.width = width
        self.rng = rng
        self.last_index = None
    def __call__(self, t):
        index = int(t / self.width)
        if index != self.last_index:
            self.last_value = self.rng.uniform(-1, 1, self.last_value.shape)
            self.last_index = index
        return self.last_value

class Delay(object):
    def __init__(self, delay, dt, size_in, size_out, rng):
        self.timesteps = int(self.delay / dt)
        self.history = np.zeros((self.timesteps + 1, size_out))
    def __call__(self, t, x):
        self.history = np.roll(self.history, -1)
        self.history[-1] = x
        return self.history[0]

model = nengo.Network()
with model:
    stim = nengo.Node(Stateful(Steps, width=0.1), size_out=1)
    delay = nengo.Node(Stateful(Delay, delay=0.05), size_in=1, size_out=1)
    nengo.Connection(stim, delay, synapse=None)
    probe1 = nengo.Probe(stim)
    probe2 = nengo.Probe(delay)
```

**Comment by hunse** [comment]
I think I'm with @tbekolay on this one. I would keep it as-is, but maybe add one example of Alternative 3 in a notebook to show how you can do more complicated closures using a class if you want.

One design constraint when I created Processes was to have them runable outside of a simulator, which is one reason I chose not to pass in the Node and just pass in size_in and size_out. If people want the full Node object, that's definitely a motivation to have a separate type for Node outputs, but I think those situations are very rare.

So far, we haven't addressed the related problem of how to make this stuff easy for backends. For example, if a backend wants to do a WhiteSignal on-chip, it would like to use the signal created by the `make_step` function. There's a similar issue with synapses. I'm not really looking to solve this problem right now, and I'm not sure if it can help inform this decision at all, but it is something to keep in mind.

Also, I have a dream that one day Processes and Synapses can share a common ancestor, or maybe Synapses inherit from Processes (since essentially they're a special type of process that has an equal size in and size out).

**Comment by tcstewar** [comment]
Sounds like the consensus so far is to leave things as they are, which is always kinda nice.  :)

I'm also "happier with the current state of affairs than I thought I would be".  There are definitely problems with the shallow copy approach, and if we stick with closures than alternative 1 doesn't really simplify much over what we currently have.  And I'm also good with ```size_in, size_out``` rather than ```node```.

And I like that the current approach allows for something like Alternative 3, if needed.  :)

I think it's also worth remembering that all of this stuff only matters if you're making a Node that needs to handle resetting and/or running multiple Simulators for.  So for novice and intermediate users, they can totally ignore all of this stuff and just define a Node the normal way and it'll work in the majority of cases (indeed, we didn't even notice this problem until recently).

So, I think the only thing I'd propose right now is that we toss in a ```from processes import Process``` into ```nengo/__init__,py``` so that people can just inherit from ```nengo.Process```.  Other than that, I think we're good.  :)  As we put together examples that need this sort of thing, we'll see if we want to start adding helper things like ```Stateful``` and how we want to structure examples.

**Comment by tbekolay** [comment]
I like the `Stateful` helper as a nice bridge for a certain level of user. I'm not exactly sure what level that is, but I have no doubt that they exist :) I think that all of these possibilities would be good to go over in an example notebook. I'll put that together, in addition to importing `Process` into the Nengo namespace, shortly.

**Comment by tbekolay** [comment]
PS: Thanks for consolidating all this discussion @tcstewar!

**Comment by tcstewar** [comment]
> Thanks for consolidating all this discussion @tcstewar!

Glad to have it sorted out!  And thank you to @hunse for doing the implementation.  :)

**Comment by tbekolay** [comment]
Note to self: when importing `Process` into Nengo namespace, remember to add documentation for `Process`, and reference it in a changelog entry.

**Comment by Seanny123** [comment]
Is this issue (and the issue this issue references) resolved by the merging of the process code into Nengo master or is there still further work to be done?

**Comment by tbekolay** [comment]
There's more work to be done, but not much. It's not necessary, but it'd be super helpful to have an example notebook that uses processes, if you want to speed things along...

**Comment by tbekolay** [comment]
I think this is done as of #955.
