### ISSUE TITLE
Should we make our own Exception classes?

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#740]
There's a lot of scary code in `nengo_gui` that uses bare `try`/`except` blocks. In some cases this can't be avoided, but in other cases, we could help out `nengo_gui` and other tools that embed Nengo by making Nengo-specific exception classes that all derive from `NengoError` or something like that (with a possible mixin of another exception class for IO errors, etc).

Any strong opinions either way? Or mild opinions, one way or another.

**Comment by tbekolay** [comment]
FYI this though came from looking at `nengo_gui` PRs and reading http://axialcorps.com/2013/08/29/5-simple-rules-for-building-great-python-packages/ simultaneously.

**Comment by tcstewar** [comment]
There's definitely a number of places that would be helpful.  In particular there are a bunch of places where the recent changes making the code more robust to exceptions is making it harder to debug the code, because we're handling the exceptions.  Rethinking the exception system would be great, but seems like a big change affecting lots of parts, so I was holding off till after the summer school.

**Comment by tbekolay** [comment]
All Nengo issues are post-summer school issues ;)

**Comment by jgosmann** [comment]
+1 to use own exception classes in most cases (in some cases the default classes should be fine, like ValueError if an invalid value is passed to one of our functions)

**Comment by jgosmann** [comment]
Don't we have our own exception classes now and close this issue?

**Comment by tbekolay** [comment]
Yerp!
