### ISSUE TITLE
InputGatedMemory should warn about auto-setting ptsc

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#742]
As discussed with Trevor and Xuan, a default post synaptic time constant is set when mem config is passed in that is different than when no mem config is passed in. The user should be warned when passing in a mem config without the post synaptic time constant set, since this may unexpectedly defy the expectations of the user, since the memory will stop acting as a memory. We also shouldn't over-ride the config of the user if no post synaptic time constant is set.

This decision is similar to the warning that occurs in the basal ganglia.

**Comment by Seanny123** [comment]
@tbekolay @xchoo I actually can't find where that warning happens in the basal ganglia? Was that actually an old version?

**Comment by xchoo** [comment]
Line 56-63 of ```actionselection.py``` in ```nengo\networks```

**Comment by Seanny123** [comment]
I don't see how that triggers a warning. I was looking for another example of a warning. If there is no example of a warning, should this be opened to wider discussion before I put in new warnings?

**Comment by tbekolay** [comment]
You're right; I think originally this was a warning, but then I changed it such that, if the user did not set a synapse, I temporarily set a synapse and then after the function is done, I unset the synapse with `del`. If you search in that file for all instances of the string `override` you can see how this logic plays out.

So, I guess you can use that kind of pattern rather than warning.

**Comment by Seanny123** [comment]
I noticed that this over-riding isn't tested. Should it be? Should I make sure to write a test for mine?

**Comment by tbekolay** [comment]
Yes, definitely test anything that isn't yet tested :)

**Comment by tbekolay** [comment]
We no longer pass configs to the `InputGatedMemory` so this issue is moot!
