### ISSUE TITLE
Allow function for probes

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#748]
It would be useful to be able to define a function on a probe. Currently it is necessary to introduce a node and apply the function to the connection to the node.

**Comment by hunse** [comment]
One thing I don't like about this is not all probes use connections. For example, if you probe the voltages of some neurons, you wouldn't be able to apply a function (without some big changes to the way we do probes). And if we allow it in some cases, then we're asking users to have judgement about when it's possible and when it's not, and that's not at all obvious unless you know the builder. 

That said, I guess the rule isn't terribly difficult: if you're probing an Ensemble or Node, you can compute a function, otherwise you can't (though you also can't change the target of the probe, for example `Probe(ens, 'input')`).

**Comment by arvoelke** [comment]
Doesn't there exist a reasonable interpretation of what the function would be in all cases? Basically just apply the function to whatever is going into `sim.data` (but before the filter if one exists). In the voltage case, it would be some n-dimensional function. For neurons, it would be the activity. For ensembles it would be the decoded activity?

I have wanted this feature at least 3 times in the past week, for what it's worth.

**Comment by hunse** [comment]
@arvoelke: So for ensembles, you're saying that we use the representational decoder and then apply the function to the result? That seems misleading to me; I would expect it to solve for the decoders for that function.

You're right though, I guess for the other stuff it could just be done as a Python function. That said, why not just compute those functions as part of your analysis once you've already collected the data?

When you say you wanted this feature, do you just mean for convenience (i.e. it was annoying to add the node)?

**Comment by arvoelke** [comment]
Yeah, I'll admit that is misleading. A compromise could be to rename `function` to something else, but that feels wrong. In all the cases where I've wanted this, though, I've wanted the function to be perfect in a sense, as it's just for analysis. Maybe there's another way that I don't see.

Sometimes storage might be a concern, so you might want to apply the function to reduce dimensionality before analysis.

But, yes, it was mostly just annoying to add the node. I think in one case I actually had to change the node to a direct mode ensemble, because I had Node -> Node with `synapse=None`.

**Comment by jgosmann** [comment]
> I've wanted the function to be perfect in a sense, as it's just for analysis

That's not true in my case.

Instead of allowing a function argument to probes, maybe could do some syntactic sugar to create that intermediate node, the connection, and the probe.

**Comment by tbekolay** [comment]
In case people don't already know this, you can probe the data going out of a connection with `nengo.Probe(connection)`. Just in case people are making unnecessary nodes and connections to them when they could just probe the connection they care about...

I suppose technically you could also make a modulatory connection to something and probe that, to save making the node. A possibility anyhow!

**Comment by jgosmann** [comment]
Nah, I need a node to make the connection in the first place :/

**Comment by hunse** [comment]
> Instead of allowing a function argument to probes, maybe could do some syntactic sugar to create that intermediate node, the connection, and the probe.

Again, though, we run into the problem that not everything that's probable can be connected (e.g. neuron voltages).

**Comment by drasmuss** [comment]
Since this hasn't come up as a high-demand feature in the last few years, our thinking is that we'll leave it with the current system (create a Node, connect to the node with the function you want, and then probe that node), rather than adding more complexity to the Probe API.
