### ISSUE TITLE
spa.Actions unsupported operand

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#759]
When I try to parse a spa.Actions like:

```
cortical_actions = spa.Actions(
    'out = (color_in * shape_in) ~cue'
)
```

I get the error:

```
TypeError: Invalid operator in expression ' (color_in * shape_in) * ~cue': unsupported operand type(s) for *: 'Convolution' and 'Source'
```

Is there a reason this type of operation is unsupported? It seems possible to chain those networks together through order of operations, but maybe I'm missing something? Is it that the expression is somewhat ambiguous as to what the user wants to do?

**Comment by tcstewar** [comment]
> Is there a reason this type of operation is unsupported?

The main reason is implementation -- it's annoying to implement all those possibilities.  Notice that ```dot(color, shape)``` also isn't supported.

That said, I think there's a design decision here.  After all, it's perfectly possible to implement what you described there by making a few buffers and doing CorticalActions.  Part of me thinks that might be the right way to do it, as it makes it more explicit what populations are being created.  So it's a matter of figuring out how explicit we want to be...

**Comment by Seanny123** [comment]
So the reason I was interested in implementing it as just a bunch of
chained operations was that it avoided me creating another buffer, which
meant I used less neurons. However, this may have been misguided. Are
pass-through buffers ignored in simulation just like pass-through nodes?

Is there a reason this type of operation is unsupported?

The main reason is implementation -- it's annoying to implement all those
possibilities. Notice that dot(color, shape) also isn't supported.

That said, I think there's a design decision here. After all, it's
perfectly possible to implement what you described there by making a few
buffers and doing CorticalActions. Part of me thinks that might be the
right way to do it, as it makes it more explicit what populations are being
created. So it's a matter of figuring out how explicit we want to be...

—
Reply to this email directly or view it on GitHub
<https://github.com/nengo/nengo/issues/759#issuecomment-114683512>.

**Comment by tcstewar** [comment]
> So the reason I was interested in implementing it as just a bunch of
> chained operations was that it avoided me creating another buffer, which
> meant I used less neurons

If you want it to be like a pass-through Node, then just set the spa.Buffer to direct=True.  That said, if people want these sorts of things, they could be implemented.  It is, however, tricky to handle all the cases, and I prefer a system that is clear about what it does and does not support, rather than one that supports more things but is unpredictable about what it does and does not support.  Mind you, I'm not sure we're clear yet about what we do and do not support, but that should be the goal....

**Comment by Seanny123** [comment]
First, in regards to how difficult this is, are we sure that it's actually a really hard problem and it's not just because we (or maybe just "I") don't know much about compilers?

Second, when it comes to what we do and do not want to support, do you have a platonic idea as to what you want the actions module to be? At this point, the only idea I have is that we want it to be a "production system", but that doesn't give much of an idea as to what degree of simplicity and scope of features we're aiming for. Has this type of discussion been had before?

**Comment by tcstewar** [comment]
> First, in regards to how difficult this is, are we sure that it's actually a really hard problem and it's not just because we (or maybe just "I") don't know much about compilers?

I'd say that it's probably not a *really* hard problem -- but it may require knowing stuff about compilers or thinking carefully about what we're doing.  What I should have said is just that it's not an *easy* problem, and so when I wrote the original code I just wanted something simple that covered the basic cases I needed.  Then @arvoelke reorganized the code to consolidate conditions and effects, but that was more about code reorg rather than about adding functionality.

> Second, when it comes to what we do and do not want to support, do you have a platonic idea as to what you want the actions module to be? At this point, the only idea I have is that we want it to be a "production system", but that doesn't give much of an idea as to what degree of simplicity and scope of features we're aiming for. Has this type of discussion been had before?

That is an excellent discussion point that we have not had yet.  And I'm of two minds on it.  Part of me wants to just keep throwing in capabilities in the rules and build things up, such that you could do rules like ```dot(a,b*c)*dot(q+P,c*~s) --> x=a*b*c*dot(q,~(c+d))```.  However, another part of me thinks that's a horrible idea because it means you're suddenly creating a VERY LARGE network to compute that, and that's an indication that you're doing things that aren't particularly suited for this approach.  In other words, the syntax should encourage the creation of things that neurons are good at computing.  Otherwise we run the risk of just implementing a Turing Machine, leading to very biologically implausible models.

One thing I really like with the current syntax for the input to the BG is that it only ever creates Connections.  That is, it is only suitable for computing things that can be directly computed given the neurons you already have.  That's why I've been a bit resistant to putting support for ```dot(a, b)```, since that requires creating an intermediate neural population.  Instead, you currently have to create a ```spa.Compare``` module.  So that way I'm a little bit aware of when I'm doing something that requires more neurons, and I have a hope of re-using those neurons for other rules.

For the output side, the Thalamus will create new neurons, but only as intermediate groups that end up getting inhibited.  That said, it still can require a fair number of neurons, such as ``` --> a=b*c```, where the intermediate population needs to compute the convolution.  But so far it has been consistent that any rule that requires routing only creates one EnsembleArray to do that routing.  So I'm a bit worried about ```--> a = b*c*d``` which requires two steps (or a new custom three-way CircularConvolution class).

So I think that's the way I'm leaning right now.  The rule syntax should be structured around doing things that are natural to implement in neurons with minimal extra cost.  For me that generally means that I don't mind anything that just adds new Connections, but I'd be careful on things that require more Ensembles.

**Comment by Seanny123** [comment]
I understand the philosophy behind the actions class now. The way I understand it is we're encouraging the user to explore more biologically plausible architecture by making it harder for them to shoot themselves in the foot by making a ton of neural populations instead of re-using them. That being said, I still think this philosophy should be explained somewhere (along with a brief explanation of what a production system is) either in a blog post or in the beginning of the SPA tutorials as I've mentioned in #686. Thus, I'll leave this issue open for now until I get around to updating the docs.

**Comment by tcstewar** [comment]
> That being said, I still think this philosophy should be explained somewhere (along with a brief explanation of what a production system is)

I definitely agree.  And I don't think I've even been coherent in my own thoughts about it until you asked this question.....   :)

**Comment by arvoelke** [comment]
When I did that code reorganization, I was definitely trying to take into account ideas from compilers. I think the only functionality I added was supporting symbol effects in the thalamus (6f5dd8d50c4ee5ff506c70ed015acbc91af49dbb), but it should now mean fewer changes to support larger classes of expressions.

Currently, you can think of `basalganglia`, `thalamus`, and `cortical` files, as three separate compilers for the same "action language", which consists of `Expression` and `Effect` structures. 

These compilers don't do much, because the language is not very deep. I believe the only one that has to create any population is the thalamus to support convolution between two dynamic inputs. All three support partially overlapping subsets of the language, but do not support hierarchical operations that require intermediate inputs or outputs, even if the language specification allows for this. This is why the repetition of code is currently not too painful.

But in the back of my head, I was anticipating that some day we might have a single compiler, which can be appropriately utilized by all three networks, and also support hierarchical operations. This compiler would build intermediate structures in memory, optimize away repeated computations, and then "compile" them into convolution/product networks, ensembles, and transforms. I believe that this would simplify the creation of more complex networks, while being able to take advantage of implementational details that a user might not be aware of or be thinking about.

I don't know if biological plausibility is a concern here, because the action language on its own is not Turing complete (although I did show that once you add recursion through the Basal ganglia, and add a learnable cleanup, then you do get Turing completeness). I think the main concern is doing things in a way that a user can't access, understand, or debug.

**Comment by Seanny123** [comment]
Given this discussion, should the `NotImplementedYet` that gets thrown when you do `dot(a,b)` (see [here](https://github.com/nengo/nengo/blob/2ebda418e91b17f5c30f3ed66954b8f34d9670c1/nengo/spa/compare.py#L72)) be replaced with an error saying that it's unsupported, as well as a link to this discussion?

**Comment by tcstewar** [comment]
> Given this discussion, should the NotImplementedYet that gets thrown when you do dot(a,b) (see here) be replaced with an error saying that it's unsupported, as well as a link to this discussion?

Seems reasonable to me....

**Comment by jgosmann** [comment]
> But in the back of my head, I was anticipating that some day we might have a single compiler, which can be appropriately utilized by all three networks, and also support hierarchical operations. This compiler would build intermediate structures in memory, optimize away repeated computations, and then "compile" them into convolution/product networks, ensembles, and transforms. I believe that this would simplify the creation of more complex networks, while being able to take advantage of implementational details that a user might not be aware of or be thinking about.

In the implementation of #1007 I started to do exactly that (minus the optimization part). So the questions becomes should we "cripple" this functionality to keep users from building too implausible or too large models?

**Comment by arvoelke** [comment]
Nice. I haven't looked very closely yet, but when I was talking about hierarchical operations I was envisioning things like supporting `a * b * c * d` expressions, which could be compiled into two levels of convolution using a binary tree like `((a * b) * (c * d))`. On the other hand I think you are referring to a hierarchy of modules? Or maybe these are the same ideas?

Either way, I don't like the idea of intentionally crippling functionality. My thinking is still that the most important thing is to give users a clear way to understand (and debug) how these systems are physically realized. It's hard to give arguments without any concrete examples however.

**Comment by jgosmann** [comment]
Expressions like `a * b * c * d` will be supported, but the order of operations will be `((a * b) * c) * d`. This is still the same number of convolutions, but the tree structure is deeper which might make a difference in a neural implementation? (That might be then a hint that it might be necessary to be able to turn such optimizations off, though in this case one can always add parenthesis to specify the exact syntax tree.)

I won't implement the optimization aspect of reusing parts like `a * b` and `c * d`. I have some ideas how one could approach that, but I am not sure how to solve the problem for all cases because `a * b` and should `b * a` should be treated the same (that is the easy problem). The hard problem is expressions like `a * b * c * d` can have multiple valid syntax trees and only some might match another expressions.

The hierarchy of modules is not really related to this. The only thing for that to consider is parsing expressions like `module.submodule` and resolving those names.

**Comment by arvoelke** [comment]
Cool, sounds about right.

> I have some ideas how one could approach that, but I am not sure how to solve the problem for all cases... 

Yes, it is a very hard problem in general. This is similar to optimizing the memory layout of assembly, because you can form little sub-routines that you can jump in and out of to reuse little sub-expressions like these. It's basically half of what compiler theory is about, and probably why gcc's highest optimizer is so damn slow and complex. One of us could easily "waste" a lifetime muddling around with doing similar stuff here, but luckily there is always some low-handing fruit to pick off!

**Comment by hunse** [comment]
> This compiler would build intermediate structures in memory, optimize away repeated computations, and then "compile" them into convolution/product networks, ensembles, and transforms.

I think we want to avoid too much "optimization". The point of Nengo, as I see it, is as a model description language, and we should focus on allowing people to describe models both concisely and explicitly. If people want to avoid repeated computations, they can make an intermediary buffer and store something there. But I think it should be explicit; we should never do this for them.

If we want I guess we *could* have some helper functions that optimize a SPA network, for people who want to use Nengo as a true "neural compiler" and just get stuff in neurons e.g. to put it on a neuromorphic chip. But I see Nengo first and foremost as a computational neuroscience tool, and for me that means explicit models that are clear from the code, not mysterious optimizations.

**Comment by arvoelke** [comment]
I agree with all that in principle, but there are a couple things I want to say (because, you know, different perspectives are great):
 - Currently it's actually quite difficult to do something like build an intermediate result into a buffer and reuse that for another computation. It involves manually creating the modules and transforms between them, when in theory we could just reuse the SPA language to do this in a single line. I think what Jan is doing right now gets us most of the way there.
 - Certain classes of optimizations may in fact be analogous to certain ideas in computational neuroscience, that people in fact want to model. For example, thinking about hierarchical reinforcement learning and finding repeated structure in sub-tasks, and how that's thought to map onto radially expanding hierarchies of computations away from BG. So it may be beneficial to view aspects of this problem as a form of "offline reinforcement learning" similar to how we view our decoders as coming from some form of offline supervised learning. But this is mainly speculative food for thought.

**Comment by tcstewar** [comment]
Quick summary of discussion in today's dev meeting:

- let's allow whatever the syntax supports, so things like ```dot(dot(a, b)*c+DOG, d+e*c*f*g+CAT) --> b=c*c*c+q*dot(c,CAT)``` could be legit rules, and it would go ahead and create all the intermediate ensembles needed.
- It's still unclear where to place the created components.  For now, place them wherever's easiest in the code, with the exception of gating Ensembles, which might be best just placed in the root Network (or have a parameter setting that places them in a separate routing Network)
- We should keep backwards compatibility with the existing examples and tutorials, but everything not covered by those tutorials is up for changing.

**Comment by jgosmann** [comment]
Resolved by #1137.

**Comment by ikajic** [comment]
Since I'm not too familiar with the new-spa dev process, I'm just guessing that this functionality has been implemented on a some branch but is not in the master yet. I currently need this (`dot(state1, state2)`) and I would prefer to work with master, so I wonder if there's a reference (for example, a code excerpt from someone who has done it) I could take a look at on how to implement this and use it until the other branch gets merged?

**Comment by Seanny123** [comment]
Does the `spa.Compare` module provide the functionality you require?

**Comment by ikajic** [comment]
Yes, that's what I needed, it was not clear to me how it's used but I figured something out from the tests...

**Comment by jgosmann** [comment]
In case you change your mind on preferring master: This functionality should be in a working state in the `new-spa` branch, but old SPA models will need some minor changes. It would be great to get it tested by more people in real scenarios.

In any case, to get this functionality with the legacy SPA system create a network `cmp = spa.Compare(dimensions)` and use two cortical rules `cmp_A = state1` and `cmp_B = state2`. Finally, manually connect the output to the input of the basal ganglia `nengo.Connection(cmp.output, bg.input[rule_index])`.

**Comment by tcstewar** [comment]
> Finally, manually connect the output to the input of the basal ganglia nengo.Connection(cmp.output, bg.input[rule_index]).

You don't have to do that part: you should be able to just include ``` + cmp``` on the basal ganglia rule.
