### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#764]
Do we have a policy or heuristic about when we make a release? I know we use Semantic Versioning, but when do we decide we've reached critical mass in terms of bug fixes or functionality additions, thus deciding to make a release?

**Comment by mundya** [comment]
Anecdote from the (Nengo flavoured) SpiNNaker world: we tend to try to ensure that a merge to master requires a release.  For Rig (a tool we use for developing for SpiNNaker) we have followed this policy and it made testing nengo_spinnaker against it considerably easier.

**Comment by Seanny123** [comment]
Given the amount of [work and vigilance](https://pythonhosted.org/nengo/releasing.html) that it takes to make a release, I'm unsure if that's feasible for our lab.

**Comment by mundya** [comment]
Wow, that's a *lot* of [work and vigilance](https://github.com/project-rig/rig/blob/master/DEVELOP.md#making-a-release).

**Comment by tcstewar** [comment]
> Do we have a policy or heuristic about when we make a release?

I'd like to lean towards having releases a bit more often....  The v2.0.1 branch is a fair bit behind.  I think the main thing is that we were a bit stalled with the Processes thing and the changes to LearningRule, both of which we want for 2.1.0, and so the moment either of those got merged into master we could no longer make any little bugfix releases on the 2.0.x line.  So I think in the future we'll try to have there be less time between a merge to master that requires a big change to our version number and the actual release coming out...  that'll help a fair bit...  :)

**Comment by tbekolay** [comment]
Yep, we're at a somewhat unfortunate point in Nengo history right now. It'll help a lot when someone's working on this stuff full time ;)

**Comment by jgosmann** [comment]
> so the moment either of those got merged into master we could no longer make any little bugfix releases on the 2.0.x line

We could still branch off of the corresponding `v2.0.x` tag and do a bugfix release from that branch. But the cleaner approach might be to have a `develop` branch in addition to the `master` branch.

I was under the impression that the main reason for not having a release was that most of the PRs did not get a review yet. But if it is indeed that we can't merge to master because of potential bugfix releases, we should rethink our development/branching model in my opinion. It seems beneficial to merge as soon as feature is finished and reviewed to be able to discover bugs resulting from the integration (we had quite a number of such bugs in nengo_gui).

**Comment by Seanny123** [comment]
+1 for dev branch with features and master branch for simple bug fixes

That being said, maybe we should take this offline and finish it off in the nengo dev meeting tomorrow?

**Comment by tbekolay** [comment]
> finish it off in the nengo dev meeting tomorrow?

Sounds good to me!

**Comment by Seanny123** [comment]
Given that the tempo of the project is uncertain at the moment, our policy will currently be to discuss (quickly) at the beginning of each dev meeting. If we find that this is too inconvenient or too cluttered, we will reconsider the overhead added by a development branch.
