### ISSUE TITLE
The default BCM learning rate (1e-9) should be lowered to 10% of their former value or more?

### ISSUE THREAD

**Issue by s72sue** [nengo/nengo#773]
When implementing the hPES (i.e., using PES and BCM together), learning doesn't work well at all.
Using PES alone works fine, so this related to the learning rate scaling for BCM.

Reducing the BCM learning rate by 10% makes the leaning work, so the default BCM learning rate in nengo should probably be lowered.

**Comment by hunse** [comment]
Yeah, we can do this. Default learning rule rates are hard to pick, though, since they depend a lot on the situation. It might be good to discuss whether the Oja and BCM learning rules could be made more invariant by dividing by the number of neurons, or other such modifications.

Also, when you say lower by 10 percent, do you mean *by* 10% (to 0.9e-9), or *to* 10% (of their former value, i.e. lowered by a factor of 10, to 1e-10)?

**Comment by s72sue** [comment]
Sorry, I meant to 10% of their former value, i.e., 1e-10

**Comment by s72sue** [comment]
According to the discussion with @hunse  and @tbekolay in the nengo meeting, I will test for invariance of the learning rate 1e-10 with the number of neurons. If it is invariant, we will change it to 1e-10, otherwise we will keep it the same.

**Comment by s72sue** [comment]
I found that 1e-10 performs well with upto 700 neurons, however on further increasing the number of neurons, performance starts to degrade. 

I also tried 1e-11, and it seems to work better than 1e-10. It performs well with upto 1500 neurons (I didn't test with more than 1500 neurons). 

@hunse, @tbekolay, should I change the learning rate to 1e-11 then?

**Comment by tbekolay** [comment]
How long are you running the networks? I think that the performance should degrade eventually (or the BCM rule isn't having any effect), but yeah, it should probably go for a while before it's that noticeable...

**Comment by s72sue** [comment]
I am running the network for 10s and I inhibit learning after 5s. However I just tried running it for upto 20s and the performance doesn't seem to degrade with a BCM learning rate of 1e-11. It does degrade with BCM learning rate of 1e-10 though.

**Comment by tbekolay** [comment]
We discussed this a bit at the last dev meeting. Unsupervised learning rules like BCM and Oja are difficult to reason about in the context of Nengo models; the rules work in neural activity space, which means that they depend only on the activities of the pre and post neurons, which means that the learning rule itself is in no way dependent on the size of the pre and post ensembles. However! If you are decoding from the post ensemble, you're dealing with the weighted sum of neural activities. So, a learning rule that changes connection weights at a certain rate will have a larger effect on the decoded value of larger ensembles simply because more connection weights are being changed.

I suspect that many people using activity-based rules are not using NEF decoding, so it would be surprising, I think, for us to change the learning rate based on the number of neurons in an ensemble. If they are using NEF decoding, then I think that we should recommend that they scale their learning rate by `1 / post.n_neurons`. For the time being, I think the simplest way to do that is to add something to the BCM and Oja docstrings, so I'll make a PR for that.
