### ISSUE TITLE
spa.Compare output transform

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#775]
The `spa.Compare` code has a [really weird output transform](https://github.com/nengo/nengo/blob/2ebda418e91b17f5c30f3ed66954b8f34d9670c1/nengo/spa/compare.py#L72).

Why does it do `vocab.parse("YES").v`? What's the motivation behind this transform anyways?

**Comment by tcstewar** [comment]
It was written before the support for scalar values was added.  So the output had to be a semantic pointer of some dimensionality, and so having some semantic pointer for YES (as in, "yes it's a match") seemed vaguely plausible.  

That said, now that scalar values are a bit more supported in spa.Actions the output really should just be a scalar.

**Comment by Seanny123** [comment]
I'm not sure what you mean by "the output should really just be a scalar"? Do you mean removing that line entirely and just letting the transform be the output scale?

**Comment by tcstewar** [comment]
> Do you mean removing that line entirely and just letting the transform be the output scale?

Yes, with the recognition that the output would now no longer be a vector (and would no longer have a Vocabulary associated with it), but it would just be a single-dimensional value.

**Comment by Seanny123** [comment]
Oh jeez. Since that means a total output change, does that mean this will have to wait until version 2.2 of Nengo?

**Comment by tcstewar** [comment]
> Since that means a total output change, does that mean this will have to wait until version 2.2 of Nengo?

Possibly.  Although spa.Compare is so incredibly infrequently used that I'd be willing to have it change and not worry about it.  Or come up with a new name and transition over to that (as we are with spa.State).

**Comment by jgosmann** [comment]
+1 for just returning a scalar.
This high dimensional output has annoyed me for quite a while now.

**Comment by Seanny123** [comment]
So I've made a network that just returns a scalar, but now I'm not sure how to include in the rest of the spa.Actions, regardless of whether they're cortical or basal-ganglia. I just keep getting that my output size (1) doesn't fit dimension-wise the rest of my vocabulary (32). Where do I need to make the change? In spa.Actions parsing or in spa.Compare?

**Comment by tcstewar** [comment]
Argh.  It looks like my memory was completely wrong.  I guess the *intent* was to modify things so that scalar values were handled well, but that wasn't completed.  Fortunately, it looks like it's pretty close.

What we need is to allow spa.BasalGanglia to handle this sort of spa.Action:

```dot(vision, DOG) + compare --> speech=BARK```

Right now if you try that you get an error like

```
  File "c:\users\terry\documents\github\nengo\nengo\spa\spa.py", line 87, in __setattr__
    value.on_add(self)
  File "c:\users\terry\documents\github\nengo\nengo\spa\basalganglia.py", line 79, in on_add
    "by the Basal Ganglia." % (c, action))
NotImplementedError: Subexpression 'compare' from action '<>' is not supported by the Basal Ganglia.
```

It should be fairly straightforward to add...  it'd be defining an ```add_scalar_input``` and just having that connect.  I think it'd even be easy to support ```compare*3``` as well...  although it should give an error on ```compare*DOG```.

**Comment by Seanny123** [comment]
So that I can add support for `compare*3` should I make the `Symbol` object be able to accept a scale, like the `DotProduct` does? Or is there some other way to do it?

**Comment by tcstewar** [comment]
> So that I can add support for compare*3 should I make the Symbol object be able to accept a scale, like the DotProduct does? Or is there some other way to do it?

???  You shouldn't have to do anything at all to Symbol here, since Symbol is the thing for representing ```DOG``` or ```DOG*CAT*3``` or things like that.

You also shouldn't have to change ```Source``` at all, since Source already handles a transform.  So you should be able to do this in the ```add_scalar_input``` -- just check if the thing you've been given is a Source and check its ```transform``` to make sure it's a scalar.
