### ISSUE TITLE
Working with read-only vocabularies have unintended side effects

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#784]
As a workaround to #699 and #731, PR #699 implements subvocabularies as read-only vocabularies. However, this poses a problem when trying to use spa modules that use these subvocabularies (the associative memory module, for example).

```
# Using the spa_subvocab branch
vocab = spa.Vocabulary(32)
vocab.parse('A+B+C')
subvocab = vocab.create_subset(['A'])

with spa.SPA() as model:
    model.buff = spa.Buffer(32)
    model.am = spa.AssociativeMemory(subvocab)

    ctx_actions = spa.Actions('buff=am * C')
    model.cortical = spa.Cortical(ctx_actions)
```

The above code throws the following error: `ValueError: Cannot add semantic pointer 'C' to read-only vocabulary.`. This is because (as intended), the spa code is looking for `C` in `model.am`'s vocabulary, and since that vocabulary is a subset vocabulary, it: 1) can't find `C`, 2) can't add `C` because it is read only.

One solution is to apply the vocabulary operations (looking for a semantic pointer, adding a semantic pointer) to a vocabulary's parent vocab if it is read only.

The current solution to the above problem is to insert a buffer after the associative memory:

```
with spa.SPA() as model:
    model.buff = spa.Buffer(32)
    model.am = spa.AssociativeMemory(subvocab)
    model.am_out = spa.Buffer(32)

    ctx_actions = spa.Actions('am_out=am', 'buff=am_out * C')
    model.cortical = spa.Cortical(ctx_actions)
```

**Comment by jgosmann** [comment]
> This is because (as intended), the spa code is looking for C in model.am's vocabulary

Why is this intended? Why not look for C in `model.buff`'s vocabulary?

**Comment by xchoo** [comment]
>Why is this intended? Why not look for C in ```model.buff's``` vocabulary?
Because C is being convolved with the output of ```am_out```, and it is to take into account the case where ```buff``` has a different dimensionality to ```am_out```.

**Comment by jgosmann** [comment]
Assuming `am_out` has dimensionality d1, `buff` dimensionality d2, and d1 != d2, then C will be looked up in `am_out` vocab which will make it d1-dimensional. The convolution of two d1-dimensional vectors produces another d1-dimensional vector. So how this vector converted to the required d2-dimensional vector? And why not to that conversion (whatever it is) for the output of `am_out` and look up C in `buff`'s vocabulary?

**Comment by xchoo** [comment]
There's a ```transform_to``` function between two vocabularies (in this case, the spa code will calculate the transform between ```buff```'s vocabulary and ```am_out```'s vocabulary) which is then applied on the routing connection.

**Comment by jgosmann** [comment]
But why should it be applied after the convolution and not before it?

**Comment by xchoo** [comment]
Good question. Perhaps @tcstewar can shed some light on this? :smile:

**Comment by tcstewar** [comment]
> But why should it be applied after the convolution and not before it?

It certainly could be implemented to do the transform_to after the convolution, rather than before.  The main problem with doing that is trying to come up with an understandable set of rules for when it does the transformation.  When I implemented it, the simple rule I was trying to stick with was "do everything in the target's vocabulary".  So for ```buff=am_out * C``` I'd do it all in ```buff```'s vocab.  That at least made it somewhat clear to me what was happening.

Now that we're introducing read-only Vocabs, though, I can see taking a close look at this.  The first thing that comes to mind is something like "if you can't find it in the target's vocab and the target's vocab is readonly then backtrack up the stack and try doing the convolution in the vocab of the thing you're connecting to"?  That's an ugly way to phrase it, but perhaps something like that can be made to be intuitive.

(Note: as an example of why I'd want the default to be in the target's vocab, this sort of thing comes up very readily in parsing models, so I'll often have something like ```phrase=vision*NOUN``` and there's no reason for NOUN to be in ```vision```'s vocab.... And, indeed, ```NOUN``` really should be in ```phrase```'s vocab to allow deconvolution later.  However, that then means that I'd probably also want ```motor=phrase*~NOUN``` to not require ```NOUN``` to be in ```motor```'s vocab......   So this really is something where we need some understandable way of controlling this....)

**Comment by xchoo** [comment]
Wait. If what you are saying is true (i.e. do everything in the target vocab), then the above example shouldn't be giving any errors. It only gives errors because it's trying to find ```C``` from the source vocab. (Unless I'm mixing up 'target' and 'source'. XD)

**Comment by tcstewar** [comment]
> Wait. If what you are saying is true (i.e. do everything in the target vocab), then the above example shouldn't be giving any errors. It only gives errors because it's trying to find C from the source vocab. (Unless I'm mixing up 'target' and 'source'. XD)

Argh.  I screwed up my own rule because I screwed up reading the comments in this thread.  Sorry about that.

Looks like the rule is "do everything in the vocab that you're reading data from".  That way there's only ever at most one ```transform_to``` happening.

**Comment by xchoo** [comment]
Re: backtracking:
I'd think that the backtracking process should be something like this:
- Is it in the target's vocab?
- If not, is the target's vocab read-only? (If no, add it in)
- If yes, does the target vocab have a non-None parent? (i.e. it's a subset of a larger vocabulary) (If yes, then apply operations to parent vocabulary (go back to the first step)
- If no, then look at the source's vocab (go back to first step)
- If all vocabs are read-only (source & target's), then look at the default vocabulary.

**Comment by xchoo** [comment]
> Looks like the rule is "do everything in the vocab that you're reading data from". That way there's only ever at most one transform_to happening.

Righto. That's the way I understood the code. XD

**Comment by tcstewar** [comment]
> Re: backtracking:
I'd think that the backtracking process should be something like this:

Is it in the target's vocab?
If not, is the target's vocab read-only? (If no, add it in)
If yes, does the target vocab have a non-None parent? (i.e. it's a subset of a larger vocabulary) (If yes, then apply operations to parent vocabulary (go back to the first step)
If no, then look at the source's vocab (go back to first step)
If all vocabs are read-only (source & target's), then look at the default vocabulary.

Gah.  I would really really prefer some sort of simpler logic than that.  That's giving me all sorts of warning bells about debugging that chain of logic and trying to understand what a model is doing is just going to get bizarre.  

But there may be no way around that.  So I'm not saying that chain of logic is wrong, I'm just saying I don't like it, and we should be cautious.  :)

**Comment by jgosmann** [comment]
> I'd think that the backtracking process should be something like this:

I don't feel like that it is simple enough. Too much implicit stuff going on depending on a lot of details. I might prefer some explicit way of expressing where the additional pointers should be looked up. ("Explicit is better than implicit.", "In the face of ambiguity, refuse the temptation to guess.")

**Comment by jgosmann** [comment]
If we want a simple rule, I would prefer to use the target's vocab. I am more likely to expect the "assignment" to influence the vocab than just "reading" a buffer in the rule.

**Comment by xchoo** [comment]
Out of curiosity, if you do something like:
```
vocab1 = spa.Vocabulary(32)
vocab1.parse('A+B+C')
vocab2 = spa.Vocabulary(32)
vocab2.parse('A+B+C')
vocab3 = spa.Vocabulary(16)
vocab3.parse('A+B+C')

with spa.SPA() as model:
    model.buff1 = spa.Buffer(32, vocab=vocab1)
    model.buff2 = spa.Buffer(32, vocab=vocab2)
    model.buff3 = spa.Buffer(16, vocab=vocab3)

    ctx_actions = spa.Actions('buff3=buff1 * C + buff2 * A')
    model.cortical = spa.Cortical(ctx_actions)
```
What vocabulary does it use to do the transform_to between ```buff1 * C + buff2 * A``` and ```buff3```?

**Comment by tcstewar** [comment]
> What vocabulary does it use to do the transform_to between buff1 * C + buff2 * A and buff3?

The nice thing is it gets split by the ```+``` sign, so the logic for doing ```buff1*C``` is completely independent from the stuff for ```buff2*A```.  So the first will use ```buff1``` and the second will use ```buff2```

**Comment by xchoo** [comment]
Ohhh right. D'oh. XD

**Comment by xchoo** [comment]
What if you do ```buff1 * C * buff2```, where does it get ```C``` from then?

**Comment by tcstewar** [comment]
> What if you do buff1 * C * buff2, where does it get C from then?

It defaults to ```buff1``` due to left-to-right order of operations, but you can control it with parentheses:  ```buff1*(C*buff2)``` will make it be processed by ```buff2```.

**Comment by xchoo** [comment]
So, if we were to default to using the target's vocabulary, we'd have to strip out the constants, and add them in later?

**Comment by tcstewar** [comment]
> So, if we were to default to using the target's vocabulary, we'd have to strip out the constants, and add them in later?

I think I'd need a more detailed description of what you mean by that and in what conditions you're thiinking of in order to give a useful answer.  Stripping things out from where?  All the parsing happens completely independent of vocabs -- the vocab stuff doesn't even enter the algorithm until it comes time to actually start making connections.  All the stuff about what constants are grouped to what modules is all handled by the ```Source``` and ```Symbol``` code, which never even needs to know about vocabularies.  It's just when the Thalamus goes to actually implement things that the Vocabularies come it.

**Comment by xchoo** [comment]
Hmm. I sense more discussion is needed on how best to handle where (which vocab) the constants come from when parsing these statements. I've had multiple people (Dan, Eric, people from the summer school) misunderstand where the constants come from vs where they think they come from.

One common theme I'm seeing is that they think the constants come from the default vocabulary (i.e. when all the buffers are the same dimensionality).

**Comment by tcstewar** [comment]
> Hmm. I sense more discussion is needed on how best to handle where (which vocab) the constants come from when parsing these statements. I've had multiple people (Dan, Eric, people from the summer school) misunderstand where the constants come from vs where they think they come from.

I definitely agree, but that's independent from the point I was making about your question about "we'd have to strip out the constants, and add them in later?".  You shouldn't have to do anything like stripping out constants and adding them in later, regardless of how you want to interpret the constants, since that's all handled by the Symbols and Sources stuff, which has nothing to do with Vocabularies.  That's just about parsing the strings.  So however you decide to interpret the constants and decide where they come from, that shouldn't have anything to do with the parsing of the constants.  (Unless I'm guessing wrong about what you meant by that question)

**Comment by xchoo** [comment]
Oh. I didn't mean to actually strip them out. I meant that the processing of the constants will have to be handled differently.

E.g. for ```buff1 * C * buff2``` the code would have to build the network for ```buff1 * buff2``` first (i.e. stripping out the constant), and then on the transform to ```buff3``` to the ```transform_to``` thing.

**Comment by xchoo** [comment]
That's if we use Jan's suggestion of always using the target's vocabulary.

**Comment by tcstewar** [comment]
> E.g. for buff1 * C * buff2 the code would have to build the network for buff1 * buff2 first (i.e. stripping out the constant), and then on the transform to buff3 to the transform_to thing.

Ah, the reason I was confused is that Symbols and Sources already do exactly that processing for you, so there's nothing to strip out.  You just have have change how that information is used.

**Comment by jgosmann** [comment]
This will be resolved in the new-spa system. There the action `buff=am * C` will raise an exception because the vocabs differ and one has to do an explicit conversion. Either `buff=reinterpret(am) * C` or `buff=translate(am) * C`. The former one is probably preferred because we have a subvocab which uses the same pointer, but one could add new vectors to the subvocab in which case `translate` might be preferred. Furthermore, `translate` will offer a `populate` argument to control whether missing keys should be added to the target vocab (there will never be keys added to the source vocab).
