### ISSUE TITLE
Setting seed for Processes?

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#787]
I'd like to be able to control the seed of a white noise process. I thought we could do this before by passing `seed` to the constructor. Is there any way I can reliably get two different simulations to use the exact same signal? 

Should `Node` accept a seed and propagate it to its child process?

**Comment by tcstewar** [comment]
You can set the ```seed``` on the Simulator...  it that what you're looking for?

But I agree it would be nice, I think, to be able to set the seed on a Process....  I think I'd set it there rather than on the Node.

**Comment by arvoelke** [comment]
That won't work for me because they are two different simulations (different ensembles and different connections), and so the effect depends on the build order. :frowning:

**Comment by tbekolay** [comment]
Setting a seed on the node makes sense to me. All of the other objects have seeds, so this seems the most idiomatic way to do it. In fact, we could move the seed to to the `NengoObject` base class.

**Comment by hunse** [comment]
Setting the seed on the node would suggest to me that it should be set implicitly if the network seed is set, like with other objects. In that case, there would be no need for a simulator seed.

**Comment by tcstewar** [comment]
> Setting the seed on the node would suggest to me that it should be set implicitly if the network seed is set, like with other objects. In that case, there would be no need for a simulator seed.

That was my intuition as well -- all the other seeds can get driven by the Network seed, but the Process one can't.  So it feels more consistent to me to set the seed on the Process instead of the Node.

**Comment by tbekolay** [comment]
> it should be set implicitly if the network seed is set

Yeah, I would think so... Would anyone argue that since the `Process` is a runtime thing (rather than a buildtime thing) then it shouldn't be made deterministic with setting the network seed?

> all the other seeds can get driven by the Network seed, but the Process one can't

Currently the process seed is not being set by the build process, but it certainly could be (the builder is what calls `make_step`). The question is whether or not it should be.

**Comment by hunse** [comment]
I had thought it would be useful to be able to change noise just with a reset, but that might just be because I've done a lot of stochastic stuff.

**Comment by tbekolay** [comment]
I think it depends on whether it's part of a node (which to me feels like it should be deterministic) or part of, say, noise injected into an ensemble (which feels like it shouldn't be). I must admit I can't come up with good reasons why either one should / shouldn't be set though, perhaps it should always be deterministic?

**Comment by tcstewar** [comment]
My understanding via a few conversations with @hunse is that the logic for the seed system right now is:

- the seeds in the Network (and Ensembles) are all about things that affect the build process.  Changing those seeds give you different individuals

- the seed in the Simulator is all about things external to the model.  Changing this seed gives you different random stimuli.  So this gets used for Processes whether they are attached to Nodes or as noise inputs

So that's why we have separate seeds for the Simulator and the Network.  As @hunse points out, one thing you can do on a ```reset``` is change the seed, which affects the Simulator seed, but not anything else.

**Comment by hunse** [comment]
I've done this as part of #800. I just gave each process object a seed, which if you set it means that process has the same output wherever it is used. Otherwise, randomness is drawn from the builder RNG.

**Comment by tbekolay** [comment]
This is now possible thanks to #824. There are some more issues with seeding things, but I'm going to defer that to other threads as this one's run its course!
