### ISSUE TITLE
Compiled things in release ZIPs

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#834]
As discussed in #637, it would be nice to have some "compiled" things in the release ZIP and TAR files that appear here on GitHub. Specifically
- [ ] Compiled docs (HTML, PDF, both?)
- [ ] Versions of the notebooks converted to `.py` files

I'm not sure what this would entail. I'm putting it down for 2.1 for now, with the hope that someone will look into it. If it turns out to be too hard, then we can put it off.

**Comment by hunse** [comment]
It looks like we can [manually add files to releases](https://help.github.com/articles/creating-releases/), so the simplest option would be just to document this as part of our release procedure and include the built docs and examples manually.

**Comment by Seanny123** [comment]
Partially resolved by building examples into the doc folder with #1349

**Comment by Seanny123** [comment]
We discussed this during the Nengo meeting and decided that shipping built docs with the package goes against the established Python package norms. However, providing the built docs somewhere with each release would be a good idea. This is especially true for the case of offline distribution.

**Comment by jgosmann** [comment]
> We discussed this during the Nengo meeting and decided that shipping built docs with the package goes against the established Python package norms.

Does it? [At least the setuptools documentation indicates that this not necessarily the case.](https://setuptools.readthedocs.io/en/latest/setuptools.html#non-package-data-files)

Also, it seems to me that this issue is about the downloads attached to the **GitHub releases** ... though, I suppose those files should match the PyPI distributions (which they do not currently do in a strict sense I believe because they are probably just the files packed up from master and not the setuptools dist file).

**Comment by tbekolay** [comment]
To expand on the discussion in the dev meeting, I don't think it makes sense to do anything special to the zips on the GitHub releases tab because I don't think anyone actually downloads and uses those. The default zips are the contents of the source repositories, which I would remove if I could (but we can't). We could start running `setup.py sdist bdist_wheel` and uploading those to the releases tab, but I think it's better to use the established Python tools (setuptools and pip) to get Nengo.

So, given that when you pip install Nengo you no longer have obvious access to the files in the distribution, I don't think it makes sense to add additional steps to our release process to include these files in the distribution that gets uploaded to PyPI (especially since the rendered plots are many times larger than the source itself). My strong preference is to refer people to the documentation websites rather than adding docs in `/usr/share` or elsewhere. I personally have never used those doc pages, though I may be in the minority there.

If we're agreed that the build docs are not things we want to include in the source distribution, then the only difficulty is when we're in a situation with no internet access. In that case, building and including docs in some form is something we should do when making a completely offline installer for Nengo, mostly useful for conferences with spotty internet access. That's tracked in another issue. Making it easy to get `.py` version of the examples is a separate issue I think, and best solved by something like https://github.com/nengo/nengo_spa/pull/49.

**Comment by jgosmann** [comment]
That sounds reasonable to me.
