### ISSUE TITLE
More input validation to Vocabulary.add?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#840]
As Jan pointed out while review my SPA similarity plot pull request in Nengo GUI, when you add a semantic pointer via `Vocabulary.add` you can enter basically any string. Maybe I'm misunderstanding what a semantic pointer key is supposed to be used for, but isn't supposed to start in a capitol and not include any weird punctuation? Should we check for this in `Vocabulary.add`?

**Comment by Seanny123** [comment]
@tbekolay says that adding input validation to this probably wouldn't break anything, but he like Terry to have the final word. @tcstewar what do you think?

**Comment by jgosmann** [comment]
I might still want to speak about this in person at a dev meeting.

**Comment by Seanny123** [comment]
I talked to Terry and he said that input validation on this thing is kind of hard. You could check if it's valid Python probably, but checking it's valid SPA pointer requires a bit more of a strict definition. Do we actually only want to allow alphabetic characters? What about unicode?

**Comment by Seanny123** [comment]
Chris says no unicode.

**Comment by tcstewar** [comment]
Hmm, I was going to say to stick with the Python definition of an ```identifier```, with the added constraint that the first character has to be an upper-case letter.

https://docs.python.org/2/reference/lexical_analysis.html#identifiers

However, in Python 3, that would also allow Unicode.  Still, I'd lean toward Chris' thought of no unicode.  So I suppose that means a quick little regex....   I think ```[A-Z](\w)*``` should do it, which isn't too bad....

**Comment by tbekolay** [comment]
Why no unicode, out of curiosity?

**Comment by jgosmann** [comment]
I am actually leaning towards allowing any string as key in `Vocabulary` and doing proper escaping when sending them to the GUI. It seems to me to be the most robust solution.
Of course that would allow to have pointers that can't be used in basal ganglia rules, but no one is forced to use such weird names.

**Comment by tcstewar** [comment]
For me, it's just the wide variety of weird things that can be done, including characters that look like spaces.  And the large set of things that count as capital letters.  Basically, it just makes the definition of what we allow as a SP identifier more complicated and less easy to immediately recognize.

**Comment by tcstewar** [comment]
> I am actually leaning towards allowing any string as key in Vocabulary and doing proper escaping when sending them to the GUI. It seems to me to be the most robust solution.
> Of course that would allow to have pointers that can't be used in basal ganglia rules, but no one is forced to use such weird names.

I could see that as an option too.  But I'm struggling to find a use case for a semantic pointer called ```"A,B"```.  

And it's not just basal ganglia rules.  It's also for direct cortical connections between and SPA modules.  So if you do define a semantic pointer called ```A,B```, then there's not way to use it when connecting things up (```model.cortical = spa.Cortical(spa.Actions('memory=vision*A,B'))``` will not work, for example.

This is why there was the intended restriction that semantic pointers should be valid Python identifiers.  However, I missed the fact that ```Vocabulary.add``` lets you do any string at all, opening the door to these rather weird pointers that can't be used in all the rest of ```spa``` that assumes valid identifiers.

**Comment by tbekolay** [comment]
I feel like in Python 3 you should be able to use whatever you can use for Python identifiers. Not sure if there's a function exposed to check if a string is an identifier... I guess you can use `eval` though.

**Comment by hunse** [comment]
I'm tempted to agree that barring unicode is unnecessary. If people want to make weird names with things that look like spaces, that's their problem. The one place where unicode could cause problems is with web stuff, specifically nengo_gui, but it seems like it shouldn't be too hard to support (it might actually work right now, who knows).

**Comment by tcstewar** [comment]
It looks like Python 3 has ```str.isidentifier()```, but in Python 2 the regex seems the only way to go (there is a built-in regex for it ```tokenizer.Name```).

I could be convinced to go with full unicode, although we'd have to make sure the capital letter check works fine for things on the unicode capital letter list.  And we'd have to make sure that the font we're using in the GUI either supports a reasonable range of unicode or is configurable.  And make sure that the JSON conversion handles it right.

Hmm, and it might make sense to redefine the restriction to be the first letter must be "non-lower-case" rather than "upper case"....

Note: the reason for this restriction in the first place is for rules like ```motor=vision*COLOR``` I find it's extremely helpful to know immediately what things are constants and what things are values in modules.  It would also be possible to not have a restriction at all and just rely on people naming things correctly; that was what I did initially but I found it meant that typos frequently created very hard-to-find bugs, such as accidentally typing ```motor=vison*COLOR``` and having it think ```vison``` is some new constant I want to define....

**Comment by jgosmann** [comment]
> And we'd have to make sure that the font we're using in the GUI either supports a reasonable range of unicode or is configurable.

If someone uses weird unicode, I would assume their system has the proper fonts. So as long as we're not overly specific with the font to be used, it should not be a problem. Also, the same thing applies to labels.

> And make sure that the JSON conversion handles it right.

That is good practice anyways. I assume we're using the Python json stdlib module and I would be surprised if that's not already the case. More problematic is were we implement our own protocol (as the SPA similarity plot), but there again it would be good practice to handle unicode and do proper escaping.

> the first letter must be "non-lower-case"

Wouldn't that allow digits as first letter?

> But I'm struggling to find a use case for a semantic pointer called "A,B"

I don't like limiting possibilities without good reason, just because I am unable to come up with a use case.

> the reason for this restriction in the first place is for rules like motor=vision*COLOR

I wouldn't have any problem to leave that restriction in place for the actions. If people add pointers to a vocab that can't be used in those rules, it is their fault or maybe they have a reason. It is also possible to use a vocab just to manage semantic pointers without the rest of the SPA system. In that case it wouldn't even be a problem.

> it's just the wide variety of weird things that can be done, including characters that look like spaces. And the large set of things that count as capital letters.

I think, it's the programmers/model builders responsibility to not do too weird things.

**Comment by tcstewar** [comment]
> If someone uses weird unicode, I would assume their system has the proper fonts. So as long as we're not overly specific with the font to be used, it should not be a problem. Also, the same thing applies to labels.

But even if they have a font that supports what they want to do installed, there still has to be a way to tell the GUI to use that font, rather than just using the default sans-serif font.  And yes, the same problem definitely comes up with labels, too.

> That is good practice anyways. I assume we're using the Python json stdlib module and I would be surprised if that's not already the case. More problematic is were we implement our own protocol (as the SPA similarity plot), but there again it would be good practice to handle unicode and do proper escaping.

I completely agree.  That'd be good practice, but it's also a big job to go through and test for and fix.

> Wouldn't that allow digits as first letter?

sorry, I meant that rule to be in addition to it being a valid Python identifier.  So a semantic pointer identifier would be a valid python identifier that did not start with a lower-case letter.  

> I don't like limiting possibilities without good reason, just because I am unable to come up with a use case.

For me, the good reason is that I don't want to end up with two classes of semantic pointers: semantic pointers that can be used in the spa architecture and semantic pointers that can't.

**Comment by celiasmith** [comment]
Same reason you don't use unicode in programming. Things are generally clearer with a more restricted set (which is sufficiently large) of characters.
________________________________

**Comment by tbekolay** [comment]
> Same reason you don't use unicode in programming

This is true for English speakers, but part of the reason most modern languages allow unicode in source files is because not everyone speaks English natively. Not that I'm arguing that we should put a lot of time and effort into making sure everything is unicode safe, but I don't see much reason to intentionally limit things to not allow unicode.

**Comment by celiasmith** [comment]
So, as many of these things do, this seems to boil down to the "let people do what ever they want" versus "let's restrict things for clarity".   I believe that the general consensus in good design is that the latter (when done judiciouisly) is preferable.  I know people react badly to the idea of 'limiting the use cases', but often restrictions help in lots of ways.  In this case (Nengo), where people are in an unfamiliar environment (lots of new theory and ideas in play) and so don't know what's 'reasonable' and what's not, restrictions are very important for helping them learn.    So a highly robust, slightly more restricted design strikes me as preferable...





________________________________

**Comment by tcstewar** [comment]
> This is true for English speakers, but part of the reason most modern languages allow unicode in source files is because not everyone speaks English natively. Not that I'm arguing that we should put a lot of time and effort into making sure everything is unicode safe, but I don't see much reason to intentionally limit things to not allow unicode.

That's pretty much my thoughts on this too.  That said, while in the long run we should go through and make sure everything is unicode-safe, I think other things are higher priority right now.  But we should still decide what the short-term decision is about what to allow in ```Vocabulary.add```.  These seem to be the options:

 1) leave it as it is.  If someone does ```vocab.add('A"B', v)``` then the gui will break horribly, but that it's a pretty rare and weird thing for people to do
 2) restrict ```vocab.add``` to valid Python2 identfiers that start with upper case.  
 3) leave vocab.add alone and rework the GUI to escape things and handle unicode
 4) restrict ```vocab.add``` to valid Python3 identifiers that do not start with lower case, and rework the GUI pointer displays protocol to escape things and handle unicode

Right now, I think option 2 is the easiest fix, and it's not horrible in the long run.  At some point in the future when we want to take unicode seriously, it shouldn't be too bad to go in and change things, but it seems like a big project to me.

**Comment by Seanny123** [comment]
I also like option two the most, for the exact reasons that Terry mentioned.

**Comment by tbekolay** [comment]
+1 for option 2 also.

Option 4 would have to be a `compat` style switch for Python 3+ specific things (Python 2 can't deal with unicode identifiers in many cases), so no need to do it now (might be worth making a long-term issue for Python 3 / unicode stuff).

**Comment by jgosmann** [comment]
I'm for option 5:
5) Escape stuff (quotes) in the GUI properly, but don't care about unicode for now (if it works, that's fine, if not, then it doesn't). I feel, if we don't do this, we might shoot ourselves in the feet later and escaping a string isn't super hard.

If you want to restrict `vocab.add` in addition to that, I'm fine with that. If option 2 is implemented, please test what happens in a Python 3 environment using a valid unicode Python 3 identifier in a rule.

**Comment by jgosmann** [comment]
Addressed in nengo_spa.
