### ISSUE TITLE
Fonction get_convolution_matrix()

### ISSUE THREAD

**Issue by MenelikV** [nengo/nengo#845]
Hello, 

I saw a code for a more stable working memory. 
The Code is the following :

``` python

import numpy as np

import nengo
from nengo.networks.workingmemory import InputGatedMemory as WM
from nengo.spa import Vocabulary

#Integrator parameters 
n_neurons = 100
d = 32
diff_gain = 15

vocab = Vocabulary(d, unitary=True)
vocab.parse('POS1')
vocab.parse('INC')

for n in range(4):
    vocab.add('POS%i' % (n + 2),
              vocab.parse('POS%i * INC' % (n + 1)))

#Input function
input_func = lambda t: (vocab.parse('POS1').v if t < 0.2
                        else vocab.parse('0').v)
gate_func = lambda t: [int((t * 10) % 2),
                       1 - int((t * 10) % 2)]

#Nengo model 
with nengo.Network() as model:
    # Generate the input to the memory
    in_node = nengo.Node(input_func, label='Input Node')
    gate_node = nengo.Node(gate_func, label='Gate Input')

    # Working memory networks (doubled up, with different
    # gate signals)
    mem1 = WM(n_neurons, d, difference_gain=diff_gain)
    mem2 = WM(n_neurons, d, difference_gain=diff_gain)

    nengo.Connection(in_node, mem1.input)
    nengo.Connection(mem1.output, mem2.input)
    nengo.Connection(
        mem2.output, mem1.input,
        transform=vocab['INC'].get_convolution_matrix())

    nengo.Connection(gate_node[0], mem1.gate)
    nengo.Connection(gate_node[1], mem2.gate)

    # Compute the similarity of the output vector
    sim_node = \
        nengo.Node(lambda t, x: np.dot(x, vocab.vectors.T),
                   size_in=d, label='similarity')
    nengo.Connection(mem1.output, sim_node)
```

I wanted to rewrite the code to make it work without the spa framework but I did not get what precisely the `transform=vocab['INC'].get_convolution_matrix()` is doing.

So the question is : what the method `get_convolution_matrix()` is doing ?
I search for it across the github but I was not able to obtain the source of this function.

Thanks in advance for your answers and your time,

Ménélik

**Comment by tcstewar** [comment]
Hello Ménélik,

The source code for that function is here:

https://github.com/nengo/nengo/blob/master/nengo/spa/pointer.py#L168

The basic is to define a matrix M_x such that dot(M_x, y) gives the same result as circconv(x,y).  

I hope that helps!

**Comment by xchoo** [comment]
Hi Menelik,

The code you posted is actually an example on how you can generate new semantic pointers using existing SPA components. (I.e. the network creates new position semantic pointers from semantic pointers stored in the memory) 

If you want a working memory block that operates similar to the code you posted, but without the SPA framework, see: https://github.com/xchoo/spaun2.0/blob/master/_spaun/_networks/mem_block_basic.py

**Comment by MenelikV** [comment]
Thanks for your answers !
@xchoo , your code seems to be what I was looking for :D
Just one short question about your code, why 3.5 / sqrt(dimensions) for the radius ?

**Comment by xchoo** [comment]
Regarding the radius: that's a SPA related issue. For a semantic pointer, the expected value of one element in the vector is ```1.0 / sqrt(D)```. The ```3.5``` factor is to account for the fact that each vector element is chosen from a distribution. If you are using vectors that have elements chosen from a distribution from (-1, 1), then the radius would be 1.

**Comment by MenelikV** [comment]
Ok thanks for the explanation :)

**Comment by xchoo** [comment]
Not a problem! :smile:

**Comment by MenelikV** [comment]
Sorry for reopening this old issue; but I faced a problem with your code ( @xchoo )
My goal was to save 5 different values on 5 different slots but, as shown on the picture attached, the value drifts much for the 4th slots.
Do you know how to reduce this drifts ?
![mem_var_probe_stirnfraesen_32 0_0 2s](https://cloud.githubusercontent.com/assets/11135251/10699642/897b2bfc-79b8-11e5-9241-f53b7964c555.png)

**Comment by xchoo** [comment]
Not a problem!
The simplest and easiest thing to do to increase the accuracy of the network is to increase the number of neurons. But I suspect that we can do better than that with the network you are using. 

Looking at the graph you posted, it seems like the values you are trying to store are relatively small, and are being stored over a relatively large time frame. 

The issue with storing small values is the radius you are using for your network. By default (in my code) the radius of the network is either ```1``` or ```3.5 / sqrt(d)``` (I'm not sure what values you are using in your network). If you have a relatively small ```d``` or are using a radius of ```1```, you'll run into storage accuracy problems because the neurons are optimized over the entire range of values (say -1 to 1) but is effectively only using a small range (so you get more errors within the small range).  If you adjust the radius of your network appropriately (say to -0.15 to 0.15 for your example above), the stored values are using up the entire range, thus making it more accurate.

The amount of time the value is being stored also affects its accuracy. Because the network is using integrators to store values, increasing the integrator feedback synaptic time constant will make the system more accurate at the price of making it more sluggish to respond to input changes (e.g. make the feedback synapse = 0.3 instead of 0.1)

**Comment by MenelikV** [comment]
Sorry for the late reply ^^"
Indeed increasing the feedback synapse was a good point, I should have thought about it ^^"
Thanks for the tips and your time :)

**Comment by xchoo** [comment]
Not a problem. :smile:

**Comment by tbekolay** [comment]
It's been over a year so I think this issue's run its course :) @MenelikV, if you have any more questions, we now have a forum at https://forum.nengo.ai/ for helping out with models!
