### ISSUE TITLE
review simulator API for read-only views

### ISSUE THREAD

**Issue by jaberg** [nengo/nengo#85]
@hunse caught a bad bug where client code was writing in-place to a signals buffer, except that in the case of OpenCL, the buffer in question was a temporary, rather than actually the OCL buffer.

This kind of bug can be caught more quickly in some cases by marking the views returned by e.g. sim.signals as being read-only.  It's basically a hard kind of error to catch and also hard to prevent, but it's worth being careful to explain what kind of syntax is guaranteed to set simulator variables regardless of the simulator backend used.

**Comment by tbekolay** [comment]
The consensus from the dev meeting yesterday was that #391 addressed this (to a certain extent) in the reference backend. There may be other issues specific to Nengo OCL, but the code have changed a lot since this issue was made, so I'm going to close it without being fully addressed. If someone wants to reopen this issue for OCL, please do so in the [nengo_ocl repo](https://github.com/nengo/nengo_ocl/issues).
