### ISSUE TITLE
Slow test times on TravisCI

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#863]
The TravisCI tests are taking a long time again. I think this might be because it's installing Numpy from `pip` again (this seemed to be the case from looking at the full log for a TravisCI test run). Did we do something special before to get it to install Numpy in a better way? (I recall we had a problem like this before.) Or did they do it on their end? Even if we can get it to `sudo apt-get install python-numpy`, I think we'd be in a lot better shape, but I don't know if we can control the Numpy version that way.

**Comment by jgosmann** [comment]
Afaik `sudo apt-get` requires to use the legacy infrastructure which does not support caching of the testing environment. So I wouldn't expect it to be any faster.

**Comment by tbekolay** [comment]
Hmm, it shouldn't be pip installing numpy, it should be using Conda... I'll check out the log.

**Comment by hunse** [comment]
> Afaik `sudo apt-get` requires to use the legacy infrastructure which does not support caching of the testing environment. So I wouldn't expect it to be any faster.

It's not the installing I'm talking about, it's the speed of the installed Numpy. Maybe it is installing with Conda, but either way I think the slowdown is because of a slow Numpy.

**Comment by tbekolay** [comment]
Yeah, the issue is definitely NumPy; if you look at, e.g., [this build](https://travis-ci.org/nengo/nengo/builds/83082486) it's plenty fast for NumPy 1.6 - 1.8, but on 1.9 it's super slow for Python 2.7, 3.4, and 3.5. It happens to be fast for Python 2.6... no idea why that is.

I tried replicating the environment used by TravisCI by running the exact same commands it runs for Python 3.5. Installed miniconda, installed everything, and ran the tests the same way... and it's fast on my machine, finishes in 5 minutes.

So, something is happening in the TravisCI environment. My guess is somehow a version of NumPy other than the Conda installed NumPy is being used? Which doesn't really make sense; we use their C language image, so it shouldn't have any Python stuff like NumPy installed at all...

I made a branch that should print out some NumPy config info, so we'll see what that prints out for those slow environments.

**Comment by tbekolay** [comment]
Hmm, interesting... the slow tests are using [OpenBLAS](https://travis-ci.org/nengo/nengo/jobs/83181059#L435), which is what Conda uses on my machine, and it's fast. On the fast tests, it's using [atlas and lapack](https://travis-ci.org/nengo/nengo/jobs/83181058#L387). Curious...

**Comment by tbekolay** [comment]
Looking at the [Conda package index](https://repo.continuum.io/pkgs/free/linux-64/), maybe something changed in 1.9.3 that's causing the slowdown? Notice that py26 doesn't have a 1.9.3 package. I'm going to try depending on NumPy 1.9.2 and see if that helps.

**Comment by hunse** [comment]
That would make sense, since 1.9.3 was just released, and now it's getting installed and slowing things down. Can we have specific requirements for the tests? It would be nice not to have the tests automatically use the newer version when one is released, for situations like this.

**Comment by tbekolay** [comment]
Yeah, right now we depend on `numpy=1.9`, so it gets the latest in the 1.9 release cycle. I just [changed it to `numpy=1.9.2`](https://travis-ci.org/nengo/nengo/builds/83183521); hopefully that'll speed it up.

**Comment by tbekolay** [comment]
Well... it's [faster](https://travis-ci.org/nengo/nengo/builds/83183521) but still not as fast as older versions.  The culprit seems to be Conda's `openblas` recipe. Anyhow, it's an improvement, so I'll make a PR.

**Comment by hunse** [comment]
I think this is fine now.
