### ISSUE TITLE
What should be allowed to be config-ed?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#872]
I'm trying to make my Tower of Hanoi model run as fast as possible by using one neuron per dimension and running the neurons in direct mode. Setting this through the config system isn't supported for spa.State, nor spa.Compare. Is there a reason for this? Is there a heuristic as what should be allowed to be set via the config system and what shouldn't?

**Comment by tbekolay** [comment]
A lot of why the config system is how it is is so that we don't have to make individual decisions about what should be configurable for each type of network and whatnot; you can never predict all of the weird things people are going to want to do with each network. So, the approach is to set the things that are necessary to set, and let the config system handle the rest.

In your case, the following snippet works for me:

```python
with nengo.Network() as net:
    net.config[nengo.Ensemble].neuron_type = nengo.Direct()
    st = nengo.spa.State(16)
```

The idea is that `State`'s configuration, for parameters that it doesn't explicitly specify, is handled by the context of the network it's being added to. That way we don't have to add in a ton of parameters to `State` for all of the possible configurable things, nor do we need to accept a `config` parameter. It just uses whatever is configured in the network (or possibly networks) that it is contained in.

Note that setting the number of neuron isn't necessary because `nengo.Direct` ignores the number of neurons and represents values directly.

**Comment by Seanny123** [comment]
Now I'm trying to understand why I thought setting the number of neurons did matter. Did it use to matter in Nengo 1.4?

**Comment by tbekolay** [comment]
Hmm... I don't think so. I can understand the through process of one direct-mode neuron per dimension, though.
