### ISSUE TITLE
Additional node checking

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#878]
This is the second part of the biological plausibility discussion at the dev meeting today. Basically, nodes are quite flexible, but that flexibility comes at the cost of it being very tricky to ensure that everything you're doing is biologically plausible. We tried to alleviate this by not allowing functions on passthrough nodes, but there are still some fringe cases where you can get nonlinear-ish behavior from passthrough nodes (e.g., weird synapses, recurrent connections). That by itself would probably be solvable, but since we use nodes in our networks for input / output, it's also possible to make a loop solely with nodes that you intended to go through neurons at some point.

I'm not sure if this is super common, but making models lately I am finding I expend a lot of mental energy keeping track of what's neurons and what's not, so we should try to address this somehow.

There are a few things that we could do to help this, I think, which I'll list below, but this is mostly a discussion issue, so please chime in with other ideas that could help this, or comments on these ideas, or reasons why you think this isn't actually an issue.

---

In increasing order of effort / impact:
1. Disallow recurrent connections in passthrough nodes (or nodes in general?)
2. Add a validation step which looks at the network to find any cycles (loops) that don't have at least one ensemble in the cycle.
3. Remove passthrough nodes, and any node with `size_in > 0 and size_out > 0`.

That last one is a bit of an extreme reaction to this issue I realize, but I've thought about it a fair bit, so please indulge the mini-rant that follows but take it with a grain of salt (I wrote it a few weeks ago but haven't posted it because I'm not 100% convinced that it's "worth it").

---
### 3: Source and sink nodes, but not both

We don't want to limit the API artificially, but I think adding some additional constraints to nodes might serve the dual purpose of making nodes easier to use and implement (especially for our poor backend developers) and making models more biologically plausible, generally.

Right now, if your node's output is a Python function, it can either be a function of time, or a function of time and some input, `x`. Generally, nodes that are a function of time are "sources" in that they provide input to networks, perhaps with simple signals, or by interacting with some external resource like a sensor. Nodes that take in input are generally "sinks" in that they take output from a network and do something with them (update a plot, drive a motor, etc).

In part because it was [easy to implement](http://lambda-the-ultimate.org/node/3186), we consider both of these nodes to be the same thing, and so you can also do combined source and sink nodes; i.e., a node that takes in some input and also produces some output. This also led to the now very common passthrough node, which routes its input to its output unchanged. This is undoubtedly quite convenient, but (IMO) has led to some biologically implausible models. We tried to limit these kinds of models by removing the ability to apply functions to connections from passthrough nodes, but there are ways around it, and it's easy to convince yourself that you're just testing things out now, and later on you'll replace this hack with something plausible.

So, with that in mind, my proposal to remove this temptation is to force nodes to either be a source or a sink; that is, if `size_in > 0`, then `size_out` must be 0. If `size_out > 0`, then `size_in` must be 0.

**Side benefits** (aside from the biological plausibility motivation):
- All node functions only accept one argument, though that argument has different semantics depending on whether it's a source or sink.
- Easier to determine how to deal with a node; if `size_in > 0` then it's a sink (and therefore we don't have to run the node function in order to determine `size_out`). If `size_in == 0` then we know that it's safe to run it with float input in order to determine `size_out`.
- Easier for backends to deal with nodes. We know that sources won't depend on the Nengo model, though it's still not completely straightforward because nodes that get input from the real world, for example, aren't idempotent. But, it should be the exception rather than the rule, so instead of informing backends that your node _is_ an idempotent function of time, it should be possible to switch so that you instead inform backends when your node _is not_ idempotent.
#### Hypothetical Q & A

_How can we fix models that use passthrough nodes?_

Fortunately, the vast majority of use cases can be converted to something more biologically plausible very easily.

Case 1: Passthrough nodes to one object.

As we've done in past, these should just be aliased to the object you're connecting to. If you're connecting to only part of that object, or some particular slice, then you can alias an `ObjView` of that object instead.

Case 2: Passthrough nodes to multiple objects.

This use case is the most common in the networks that come with Nengo, and likely in user code as well. There are two options for replacing these passthrough nodes. Both have pros and cons; I'll use `EnsembleArray`'s `input` node as an example.

Currently, when you make an `EnsembleArray` with `d` 1-dimensional ensembles, we create a node called `input` with `size_in == size_out == d`. We route each dimension to one of the ensembles in the ensemble; so, in this simple case where each ensemble in the array has 1 dimension, if `d == 2`, you get `nengo.Connection(ea.input[0], ea.ea_ensembles[0], synapse=None` and `nengo.Connection(ea.input[1], ea.ea_ensembles[1], synapse=None)`. There are two ways we could remove this passthrough node and keep the functionality.

Option 1: Replace the passthrough node with a direct-mode ensemble. A direct-mode ensemble should perform exactly the same function as a passthrough node; however, it has two important benefits. One, you have to figure out how many neurons should be allocated for it, so that even if you keep the ensemble in direct mode, it will show up when counting the number of neurons in your network. Two, when your network is done and working, you can easily do a final sanity check to make sure that this passthrough ensemble is biologically plausible by changing the direct-mode ensemble to one that uses a real neuron model. Even for a huge model like Spaun, this could be done in a few lines:

``` python
for ens in spaun.all_ensembles:
    ens.neuron_type = nengo.LIF()
```

Option 2: Implement a function to connect to your network, instead of exposing an object. This is, in fact, how we connect _from_ ensemble arrays; there is some symmetry to also doing this for connecting _to_ ensemble arrays. It would look something like this.

``` python
class EnsembleArray(object):
    ...
    @with_self
    def add_input(self, obj, function=None, synapse=nengo.Lowpass(0.005), **conn_kwargs):
        for i, ens in enumerate(self.ea_ensembles):
            nengo.Connection(obj, ens, function=function, synapse=synapse, **conn_kwargs)
```

These two options aren't necessarily mutually exclusive, but to me it makes sense to favour option 2 if your network is complicated enough to warrant a Network subclass, and option 1 if your network is simple and manageable as a short function.

_What about the edge cases where I really need a node with input and output?_

As a typical example of this, consider driving an arm model; it's mostly a motor, but you also want some feedback from it. In these cases, you're doing something complicated, and so it's very likely that you're manipulating state, and therefore using some kind of object to manage that state. If that's the case, then instead of exposing a single function to a node that deals with input and output, you would instead expose two functions, one to receive input from Nengo and one to provide output to Nengo. Each of those functions would be attached to a separate node.

If the state that you're trying to manipulate is part of your Nengo model, then this is a red flag that you are indeed doing something biologically implausible, so I would argue that this is is the type of edge case we're trying to identify and make impossible.

_What about feedforward chains of connected nodes? There's nothing biologically implausible about that._

This is the use case that comes to my mind as the one we would be most explicitly crippling with this change. For example, a lot of auditory periphery models are made up with a cascade of filter banks; the most natural way to implement it is for each chain in the filter cascade to be a separate node that feeds into the next one. It keeps the implementation straightforward and modular.

I don't have a satisfying response here, unfortunately. We can suggest that people collapse all of their step functions into a single function exposed by a single node. This might be possible to do in a generic way, or people will have to write a little piece of glue to pass data through all of their functions manually. In any case, it's not a very satisfying response.

_This is a big change that will affect a lot of user models._

Like all big-ish changes, this is something that we need to do in stages. If the consensus is to move forward with this, we shouldn't actually make this change until 2.2 at the earliest; if it does happen in 2.2, then we should make sure that 2.1 includes big warnings when using passthrough nodes, or any other node that has `size_in > 0 and size_out > 0`. Of course, we should ensure that the networks that are included with Nengo are changed accordingly so that no warnings are raised.

**Comment by xchoo** [comment]
I can think of another use case in which a node with inputs and outputs are used concurrently. That is when constructing some over-arching experimenter node that changes the stimuli presented to the model based of the responses the model gives (in Spaun, the reinforcement learning task is the most prominent example). While possible, having to expose multiple functions would add a layer of complexity on top of learning the nengo syntax (it's no longer as simple as writing a single function that takes in an x and returns a value).

**Comment by tcstewar** [comment]
I also just Nodes with both inputs and outputs a lot -- basically any situation where I want to connect a Nengo model up to the outside world.  

I think my difficulty with this proposal is that I'm still not sure what the problem is we're trying to avoid.  I completely agree that we should not be allowing recurrent loops that are all passthrough Nodes (either nodeA back to itself, or nodeA to nodeB and then back to nodeA).  It's a pain to find these, but hopefully that could be done.

Are there other problems that you're trying to solve with this proposal?  Are there other things that you're finding that you feel are biologically implausible that we should disallow?  Or is the proposal to disallow Nodes with both inputs and outputs simply a way to bypass having to detect those loops?

What worries me is this example:

> Replace the passthrough node with a direct-mode ensemble. A direct-mode ensemble should perform exactly the same function as a passthrough node; however, it has two important benefits. One, you have to figure out how many neurons should be allocated for it, so that even if you keep the ensemble in direct mode, it will show up when counting the number of neurons in your network. Two, when your network is done and working, you can easily do a final sanity check to make sure that this passthrough ensemble is biologically plausible by changing the direct-mode ensemble to one that uses a real neuron model.

This doesn't make sense to me at all.  The passthrough Node is not meant to be a stand-in for a population of neurons that I'm not bothering to implement.  It's meant to be a conceptual intermediary that disappears the moment we start talking about connection weights.  All passthough Nodes in the entire system can be compiled out and rolled into connection weights (except for ones that are involved in loops that don't ever involve Ensembles, which I agree we should get rid of).   If I have one EnsembleArray A and I connect its output to the input of another EnsembleArray B, I'm not saying that there's an intermediary group of neurons between those two groups of neurons.  I'm saying the neurons in A are connected to the neurons in B.  If I wanted to compute those connection weights, I'd roll all the connections together.  But I don't usually want to compute those connection weights.

**Comment by xchoo** [comment]
I concur with Terry, and in my experience with Spaun, I haven't run into the issue of keeping track of which part of the model are input&output nodes and which part of the model are neurons (because everything except for the experimenter node (and passthrough nodes) are neural ensembles. I also share Terry's confusion regarding using direct mode ensembles to replace nodes.

**Comment by tbekolay** [comment]
I don't really disagree with either of you, but I don't think that we're doing a good job explaining all of this to someone that's new to Nengo. People always think that there's some trick to what we're doing, and the proliferation of passthrough nodes in reasonably sized models makes me feel like something fishy is going on even if mathematically you can show that it's all equivalent. I am definitely not doing a good job of explaining what makes me uncomfortable with it, but a lot happens in a connection; the synaptic filtering transforms the signal, you can use the transform to scale signals without worrying about neuron saturation, etc. I know that all of these kinds of things can most likely be mapped to an equivalent network without passthrough nodes, but I think it takes way more thought to actually do that mapping than you two are suggesting. `nengo.utils.builder.remove_passthrough_nodes` doesn't work for a lot of our tests.

I guess another way of explaining it is that it's weird that we use nodes both for the most and least complex parts of a model. We use it for those big input / output nodes that connect to the outside world, where we want them to do whatever we want, so we've made nodes maximally flexible to support that. But we also use them to pass signals along with the promise that we're not doing anything funny to them, even though nodes have the flexibility to do anything we want. I am finding it hard to construct a clear mental model for this, even though, you know, I implemented a good chunk of it. I can see people really interested in biological plausibility immediately writing off Nengo after they look at a network diagram with tons of non-neural-seeming elements.

Anyway, like I say, I don't disagree with either of you, but I find myself skeptical and I'm trying to figure out why.

Out of curiosity, Xuan, can you run this and tell me how many passthrough nodes there are in Spaun, compared to the number of ensembles?

```python
print(len([node for node in spaun.all_nodes if node.output is None]))
print(len(spaun.all_ensembles))
```

**Comment by xchoo** [comment]
> print(len([node for node in spaun.all_nodes if node.output is None]))

584

> print(len(spaun.all_ensembles))

61134

**Comment by xchoo** [comment]
>  I can see people really interested in biological plausibility immediately writing off Nengo after they look at a network diagram with tons of non-neural-seeming elements.

I am beginning to see where your concerns are, but I don't know if this topic is something we should really be directing development effort towards. In my opinion, the question of whether or not a model is biologically plausible should be up to the modeler to decide (and to prove), not for Nengo to enforce. We aren't making the claim that all models created in Nengo are biologically plausible, instead, we are claiming that you can use Nengo to make biologically plausible models (at least imho). 

You can sort of use the same argument for tools like Neuron. You can use Neuron to make biolgically plausible/realistic models, but you can just a well write your own non-realistic neuron and use it in your model (and Neuron doesn't stop you from doing so)[although technically, I suppose it might still be realistic, because you could design a real neuron to behave in such a manner maybe?]. 

In any case, I think the onus of biologically plausibility should be on the modeler, not the tool. We could, however, introduce optional checks into the system to verify biological plausibility if there is a high demand for it.

**Comment by tcstewar** [comment]
I definitely agree that we're doing a horrible job of explaining passthough Nodes -- in fact, I don't think we even mention them in any of our documentation outside of the docstrings.  We should definitely at least make an attempt to do that better.

> the proliferation of passthrough nodes in reasonably sized models makes me feel like something fishy is going on even if mathematically you can show that it's all equivalent.

Interesting...  I've never gotten that sort of response from any user, but that's worth thinking about.  @celiasmith , have you run into this from people?

> a lot happens in a connection; the synaptic filtering transforms the signal, you can use the transform to scale signals without worrying about neuron saturation, etc. 

What is "etc." here?  Neither of those aspects worry me in the slightest about plausibility; indeed, they're they whole point of the NEF.  

> immediately writing off Nengo after they look at a network diagram with tons of non-neural-seeming elements.

That's a big part of why we display them as small dots in nengo GUI, to highlight that they *can't* do anything complicated and they're just for organization.  That said, we'd originally implemented them as a separate class called "Passthrough".  Would re-introducing that achieve what you're looking for here?

>  nengo.utils.builder.remove_passthrough_nodes doesn't work for a lot of our tests.

The only thing it doesn't work for that I'm aware of is chaining Synapses together, and that's just because it's not smart enough to turn two LowPass synapses into an Alpha synapse or whatever it's supposed to be.  And I've run remove_passthrough_nodes on Spaun.  Are there other things it fails on in your experience?

Note: the nengo_brainstorm backend currently relies on calling remove_passthrough_nodes, as did the nengo_spinnaker backend, so I've worked with that reorganizing a lot, but I've never documented or explained any of it, which is really bad.  That definitely has to get addressed.

**Comment by celiasmith** [comment]
No, I haven't run into that concern.  I suspect it's because people don't notice/think about pass through nodes.

**Comment by drasmuss** [comment]
I also lean towards making the tool more flexible, and putting the onus on the tool-user to enforce the constraints they care about.  I think "biologically plausible" is an ambiguous enough term that trying to strongly enforce it syntactically is a mug's game (:hand: @celiasmith).  For example, many people would consider Sigmoid or Rectified Linear neurons biologically implausible, yet we include them in Nengo.  I understand that your concern is about people being _accidentally_ biologically implausible, which is somewhat different.  But I think the best solution to that is to provide a warning or `network.utils.check_plausibility` helper function, not to remove functionality that has a lot of legitimate uses.

As a more distant metaphor, consider how many programming errors are accidentally made when someone has an aliased numpy array instead of a copy.  It would certainly cut down on those errors if every array was always a copy, and you could always come up with equivalent functionality.  But in many cases the added flexibility of references is quite useful, and I think most people would say that it is worth the extra cognitive effort of keeping track of which things are references and which are copies.

**Comment by tbekolay** [comment]
Cool cool, I'm on board y'all. So, let's cut this part of the discussion here and I'll reiterate the three concrete ideas from this thread:

1. Disallow recurrent connections on passthrough nodes
2. Detect cycles (loops) in the network that don't have at least one ensemble in the cycle (effectively a recurrent connection through nodes).
3. Implement a biological plausibility checker (a linter, if you will) that goes through a network and prints out aspects that may not be biologically plausible (e.g., exotic synaptic filters, ensembles with too much fan-in / fan-out, usage of Sigmoid / Recitfied Linear neurons, etc).

**Comment by tcstewar** [comment]
> Disallow recurrent connections on passthrough nodes

Definitely; and that's a nice easy thing to do.  I'm embarrassed that I never noticed that's even possible, although apparently I checked for it at one point in the remove_passthrough_node code:  https://github.com/nengo/nengo/blob/master/nengo/utils/builder.py#L227

> Detect cycles (loops) in the network that don't have at least one ensemble in the cycle (effectively a recurrent connection through nodes).

I'd change that to disallowing loops that *only have passthough Nodes*.  I use loops between Nodes fairly often when building the environment that nengo models have to interact with.  It also comes up a lot when temporarily replacing parts of a large model with Nodes that do whatever as a placeholder for an eventual neural model.   If I make a Node with a function in it, then I'm already being biologically implausible, so I should be allowed to do whatever I want.

> Implement a biological plausibility checker (a linter, if you will) that goes through a network and prints out aspects that may not be biologically plausible

That is a *cool* idea.  Yes!  And I love that there'd be all sorts of different things looked for and reported on in there.  That'd be very helpful given that there's all sorts of different levels of things people might be thinking of when they are looking for biological plausibility (things like "are there mechanistic problems" versus "are there things that would be difficult for developmental processes to learn").  But it'd be so neat to have an automated report that could be generated for any model like this.

**Comment by drasmuss** [comment]
>That is a cool idea. Yes! And I love that there'd be all sorts of different things looked for and reported on in there. That'd be very helpful given that there's all sorts of different levels of things people might be thinking of when they are looking for biological plausibility (things like "are there mechanistic problems" versus "are there things that would be difficult for developmental processes to learn"). But it'd be so neat to have an automated report that could be generated for any model like this.

Yeah, that also sounds like a really interesting/useful feature to me.  It would also be a place to concretely write down those biological constraints, and unify them across models.

**Comment by studywolf** [comment]
It would be super cool to be able to run a check like that and have a
visual overlay on the model in the GUI with different colors for biological
plausibility

On Wed, Oct 21, 2015 at 11:09 AM, Daniel Rasmussen <notifications@github.com

**Comment by drasmuss** [comment]
We still think adding some kind of "biological plausibility checker" would be a cool idea, but we don't have any plans to add that based on our current development resources/priorities. But if anyone wanted to do so, we'd be interested!
