### ISSUE TITLE
Create standard for networks with two inputs

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#887]
There are a lot of networks with two input nodes: `Compare`, `Bind`, `CircularConvolution` and `Product`. Currently they don't all use the same input standard. `Compare` use `inputA` and `inputB` and the others use `A` and `B`. None of these actually obey the typical python naming conventions, given that one uses camel-case, while the other starts with an upper case despite only being an attribute.

Should we change `Compare` to conform or should we change them all to actually be in line with normal Python?

**Comment by jgosmann** [comment]
Just came across this and I would like to propose to potentially decide on this and include it in the 2.1 release. Because it might change the API of these networks, it doesn't seem like we would want to introduce these changes in a 2.1.1 release. So if we don't do it in 2.1, it probably won't happen before 2.2? Also, it seems to me benificial to have this standardized earlier than later.

**Comment by tbekolay** [comment]
I'd rather leave it to 2.2, with the understanding that there will be a much shorter development cycle for 2.2 compared to 2.1 ;)

**Comment by tcstewar** [comment]
I agree with putting it off till 2.2 and having a shorter development time.  :)

**Comment by jgosmann** [comment]
ok :)

**Comment by jgosmann** [comment]
> Compare use inputA and inputB and the others use A and B

It's even worse. Depending on how you connect to `Compare` you either have to use `inputA` and `inputB` or `A` and `B`. I feel using `A` and `B` is much more common in the code base and I'd vote for that variant (but I haven't gone through the code base and checked that my feeling is actually right).

**Comment by jgosmann** [comment]
Another option would be to use lists (and potentiall dictionaries) to address the inputs as `inputs[0]` and `inputs[1]`. However, this might not be easily possible in the SPA action system and I have to check that.

**Comment by jgosmann** [comment]
It seems to me that adding support for input lists is not straight-forward in the current SPA system (and I'm not likely to make the required changes). With the rewritten SPA compiler (#1014), however, it should be reasonably straight-forward. Unfortunately, the current plan is to not merge this into main Nengo, but to create a separate package and that will probably take a while to handle the logistics and add required features to nengo_gui.

**Comment by jgosmann** [comment]
This question should also be answered for #431. Unlike other existing networks, the order of inputs matters in this case.

**Comment by tbekolay** [comment]
We revisited this issue in the dev meeting, and decided to enumerate out possible options for standards to see if any of them stick as being the best.

It probably helps to also brainstorm about use cases. From what I've seen, there are three:

1. Single node input (as in `EnsembleArray`).
2. Multiple inputs, inputs are interchangeable (as in `Product`, `CircularConvolution`).
3. Multiple inputs, each with different function (as in `InputGatedMemory`).

Currently, we do the following:

1. `net.input` node (everywhere)
2. `net.A` / `net.B` (`Product`, `CircularConvolution`, `spa.Bind`), `net.inputA` / `net.inputB` (`spa.Compare`)
3. Freeform names (`InputGatedMemory`), names prefixed with `input` (I can't actually find any instances of this, does it happen in SPA?)

Below are possibilities; please comment with any other options you come up with!

## Option 1: always use `net.input`

The idea here is to have all networks specify their inputs through a `input` attribute. For the three use cases, we would do:

1. `net.input` is a node (as we currently do now, could be an ensemble or objview)
2. `net.input` is a list, each element being an object to connect to
3. `net.input` is a dict, keys being useful names, values being the object to connect to.

What it looks like:

```python
nengo.Connection(ens, net.input)  # Case 1
nengo.Connection(ens, net.input[0])  # Case 2
nengo.Connection(ens, net.input['gate'])  # Case 3
```

Note that instead of `input` we could use some other name (`inputs`, `ins` or something) if we want to avoid `input` being syntax highlighted in some editors since it's a builtin name.

## Option 2: prefix inputs with `input`

The idea here is to have all networks use a consistent naming scheme for all inputs, but not use Python data structures that users might not know. For the three cases, we would do:

1. `net.input` as before
2. `net.input_a`, `net.input_b` or possibly `net.input_1`, `net.input_2`
3. `net.input_<name>`

What it looks like:

```python
nengo.Connection(ens, net.input)  # Case 1
nengo.Connection(ens, net.input_a)  # Case 2
nengo.Connection(ens, net.input_gate)  # Case 3
```

---

Let me know if I've misrepresented any of the options!

**Comment by tcstewar** [comment]
> The idea here is to have all networks use a consistent naming scheme for all inputs, but not use Python data structures that users might not know.

I think another reason for Option 2 is that it also gives a consistent way of showing things in the GUI.  I'm not sure how to depict in the GUI that things are inside an array....

**Comment by jgosmann** [comment]
> It probably helps to also brainstorm about use cases. From what I've seen, there are three:

I would add a fourth one which is inbetween 2 and 3. Networks that have inputs that cannot interchanged because order matters, but are similar in function. We have this in the matrix multiplication network (probably going into extras) where the factors cannot be exchanged without transposing the result.

> or possibly net.input_1, net.input_2

This poses the questions whether it should be `input_1` and `input_2` or `input_0` and `input_1`.

**Comment by Seanny123** [comment]
> I think another reason for Option 2 is that it also gives a consistent way of showing things in the GUI. I'm not sure how to depict in the GUI that things are inside an array....

Why would this be different from what we currently do? I'm assuming each index in that array still points to a node, so we could just display that node with it's corresponding indexed name, like `input[0]`. Are you referring to drag-drop functionality if someone is making their own network?

I like option 2, because it's more explicit, but I can see it being less practical to iterate through than the alternative, as Jan mentioned.

**Comment by tbekolay** [comment]
> I would add a fourth one which is inbetween 2 and 3. Networks that have inputs that cannot interchanged because order matters, but are similar in function.

Hmm... to me, that's a special case of the 3rd use case; specifically for matrix multiplication I would call the arguments `left` and `right` (i.e., `input['left']`, `input['right']` or `input_left`, `input_right`).

---

I should probably also mention that my vote is for Option 1, or the hidden Option 0 (don't have a standard, let people do what makes sense to them).

**Comment by Seanny123** [comment]
My vote is tentatively for Option 1, unless Terry can explain to me what will go horribly wrong with the Nengo GUI.

**Comment by bjkomer** [comment]
I like bits and pieces of both options, so my vote would be for an Option 3 that combines the strengths of both of them. Any place where a name is informative, use that name. When there are multiple inputs with a similar role (i.e. product network), use a list. There are also additional cases that came to mind that I don't think exists in any of our networks yet, but may in the future.

4. Arbitrary number of inputs (e.g. product network that multiplies N numbers)
5. Multiple list inputs (e.g. network that multiplies N numbers and divides M numbers)

These last two cases don't work very nicely with the `input_a`, `input_b` way of doing things.

```
nengo.Connection(ens, net.input)  # Case 1
nengo.Connection(ens, net.input[0])  # Case 2
nengo.Connection(ens, net.input_gate)  # Case 3
nengo.Connection(ens, net.input[0:N])  # Case 4
nengo.Connection(ens, net.divide[0])  # Case 5
nengo.Connection(ens, net.multiply[0])  # Case 5
```

**Comment by Seanny123** [comment]
> Arbitrary number of inputs (e.g. product network that multiplies N numbers)

I feel like this would be determined when you built the network.

> Multiple list inputs (e.g. network that multiplies N numbers and divides M numbers)

I feel like in this case you would just have two networks to organise the inputs.

```
net.divide.input[0]
net.multiply.input[0]
```
net.ouput

**Comment by bjkomer** [comment]
> >Arbitrary number of inputs (e.g. product network that multiplies N numbers)

> I feel like this would be determined when you built the network.

This is true, it would be some parameter in the constructor, but you'll still need some way of accessing each element. Giving an index to a list seems nicer than `input_d`, `input_e`, `input_f`, etc.

**Comment by jgosmann** [comment]
> Hmm... to me, that's a special case of the 3rd use case; specifically for matrix multiplication I would call the arguments left and right (i.e., input['left'], input['right'] or input_left, input_right).

ok, I can see that.

I'd vote against the hidden option 0. Otherwise still open/undecided.

A few thoughts about the list/dict approach (nothing of which is a deal breaker to me):

* Typing `input['left']` is more cumbersome than typing `input_left`. This is less an issue on US american keyboards where you have all those characters on level 1 (though both characters in `['` and `']` are typed with the right pinky which is not ideal), but other language keyboard layouts this is often not the case. For each of the special characters `[']_` I have to press a modifier key to type them which adds up to three more keystrokes. It's not extremly horrible, but can be slightly annoying when having to write lots of dictionary accesses.
* I would not want to use `inputs` for a network with a single `input`.
* Using `input`, hower, gives us the syntax highlighting problem.
* When having `input[0]` and `input[1]`, people might think they could do stuff like:

```python
ens = nengo.Ensemble(50, 2)
prod = nengo.networks.Product(n_neurons=100, dimensions=1)
nengo.Connection(ens, prod)
```

**Comment by tbekolay** [comment]
> > > Arbitrary number of inputs (e.g. product network that multiplies N numbers)

> > I feel like this would be determined when you built the network.

> This is true, it would be some parameter in the constructor, but you'll still need some way of accessing each element. Giving an index to a list seems nicer than input_d, input_e, input_f, etc.

Additionally, writing code to create and access those attributes is not great, and probably most linters will complain:

```python
for i in range(d):
    setattr(self, "input_%s" % (string.ascii_lowercase[i]), ...)
```

**Comment by tcstewar** [comment]
> Why would this be different from what we currently do? I'm assuming each index in that array still points to a node, so we could just display that node with it's corresponding indexed name, like input[0]. Are you referring to drag-drop functionality if someone is making their own network?

Ah, right, I'd forgotten that the GUI currently does handle the case of lists, and correctly shows them with their name as ```input[0]```.  However, it does not handle the case of dictionaries, so right now those wouldn't get labelled as ```input['left']```.

**Comment by tbekolay** [comment]
> When having input[0] and input[1], people might think they could do stuff like `nengo.Connection(ens, prod)`

Can you explain the connection between using input lists and trying to connect to a network?

As a historical sidenote / curiosity, in my initial implementation of the Nengo API both `connect` and `probe` were not objects but functions that would do something different depending on the types of `pre` and `post` (or `target` in the case of probes). Specifically, for `connect` it would do something like `return pre.connect_to(post)`, which meant that you could customize the connection behavior and allow things like `nengo.connect(ens, prod)`. However, this ended up causing more problems than it solved because you have to figure out, for each object, what is the correct `pre` behavior and `post` behavior, and then deal with all the combinations of possible `pre` and `post` types... so by leaving this to the build phase we get to consider them together instead of separately, which avoids the combinatorial explosion.

> Using input, hower, gives us the syntax highlighting problem.

This is the case for both options 1 and 2; alternative names definitely welcome!

**Comment by tcstewar** [comment]
> This is true, it would be some parameter in the constructor, but you'll still need some way of accessing each element. Giving an index to a list seems nicer than input_d, input_e, input_f, etc.

I think this is definitely true for ```N>3```, and maybe even for ```N>2```.  When there's only two options, though, it seems a bit less clear to me.  

In fact, since the ```input_left``` and ```input_right``` names were mentioned for the matrix multiplication example, I wonder if those might be good names for the circular convolution and product networks as well?

**Comment by tcstewar** [comment]
> Can you explain the connection between using input lists and trying to connect to a network?

I had the same thing come to mind as well as a potential confusion.  If we have a 2D Node ```a```, we allow:

```python
nengo.Connection(..., a)
nengo.Connection(..., a[0])
nengo.Connection(..., a[1])
```

And so if in this input Node case, there's this odd inconsistency, since we're actually indexing into a list rather than slicing:

```python
nengo.Connection(..., a.input)   # not allowed
nengo.Connection(..., a.input[0])
nengo.Connection(..., a.input[1])
```

**Comment by jgosmann** [comment]
> Can you explain the connection between using input lists and trying to connect to a network?

With ensembles you can do the following things:

```python
a = nengo.Ensemble(50, 2)
b = nengo.Ensemble(50, 2)
nengo.Connection(a[0], b[0])  # Connect to a specific dimension
nengo.Connection(a, b)  # Connect both dimensions in one line
```

Given the input list, one does usually the following:

```python
a = nengo.Ensemble(50, 2)
b = nengo.networks.Product(n_neurons=100, dimensions=1)
nengo.Connection(a[0], b.inputs[0])  # Looks like connection to a specific dimensions (in a sense it is)
nengo.Connection(a[1], b.inputs[1])
```

This look similar to the first example. So someone might think by analogy that the following is possible:

```python
nengo.Connection(a, b.inputs)
```

But it isn't because `inputs` is not a single Nengo node, but a list of nodes.

Does this answer the question?

**Comment by Seanny123** [comment]
> However, it does not handle the case of dictionaries, so right now those wouldn't get labelled as input['left'].

I feel like this would be a minimal change for the GUI, so my vote is still for Option 1.

> But it isn't because inputs is not a single Nengo node, but a list of nodes.

How bad of an idea would it be to code into Nengo the ability to connect to a list of nodes just like you connect to multiple dimensions of a Node?

**Comment by tbekolay** [comment]
Ah, I get it now, thanks! Yes, that's definitely a note against Option 1, specifically that:

```python
nengo.Connection(ens, net.input[0])
```

Could mean that you have multiple nodes as an input, or it could mean that you're slicing into a single node named `input`. You would have to do `type(net.input)` to figure it out.

**Comment by jgosmann** [comment]
> How bad of an idea would it be to code into Nengo the ability to connect to a list of nodes just like you connect to multiple dimensions of a Node?

I think the problem is that the semantics aren't clear for multiple inputs with more than 1-dimensions. For example,

```python
prod = nengo.networks.Product(n_neurons=100, dimensions=4)
nengo.Connection(x, prod.inputs)
```

would require `x` to be 8-dimensional, but the order of dimensions is not obvious. Should it be `[a0, a1, a2, a3, b0, b1, b2, b3]` or `[a0, b0, a1, b1, a2, b2, a3, b3]`?

**Comment by tbekolay** [comment]
> connect to a list of nodes just like you connect to multiple dimensions of a Node

I believe Travis made a feature request for that at one point, so it's not a bad idea... But to me this falls under the general umbrella of "feature creep"; my intention has always been to not mask away the fact that we're using Python but to embrace it and help people learn Python by way of Nengo.

Another example where we do this is to force people to give us Python function objects. We could instead allow people to pass in strings that we then parse or `eval`, which is what Nengo 1.4 did, but we force them to make function instead, even though that sometimes means two or three lines to do a simple `x * x`. Similarly, despite heated arguments, we force people to keep handles to `Ensemble`, `Node` etc objects instead of having them be accessible by a unique string ID, which is also what Nengo 1.4 did.

I guess that's kind of why I like Option 1 here too. Yes, it is slightly more cognitive load to force our users to learn what Python lists and dicts are. But teaching them about that (if we can manage it) enriches their general programming experience, in addition to keeping out code Pythonic (which is a goal of mine, even when other things might be simpler).

**Comment by bjkomer** [comment]
> connect to a list of nodes just like you connect to multiple dimensions of a Node

Is it currently possible to do something like this to get that functionality? (although the syntax isn't the same, it might be more clear that you are connecting to multiple things)

`nengo.Connection(ens, net.input[:])`

**Comment by jgosmann** [comment]
It seems most people are in favour of option 1. I would use the name `inputs` for all networks that have multiple inputs. For networks with a single input, I would use the name `input`. Some editors might highlight that name, but:
* There doesn't seem to be a good synonym.
* We're not actually hiding the built-in `input`, because it it will be an attribute on the network.

**Comment by jgosmann** [comment]
The best alternative names for `input` I came up with:
* `input_node` (but it may not be a node)
* `input_object` (so much to type and object is not very specific)
* `input_obj` (making the previous name more cryptic)

**Comment by tcstewar** [comment]
> It seems most people are in favour of option 1.

I'm still partial to option 2, because it
 - avoids the slicing confusion when it's a list
 - avoids the dictionary syntax for named items, which I find makes it easier to type and remember (```input_gate``` rather than ```inputs['gate']```)

**Comment by Seanny123** [comment]
So... Since we seem to have discussed all the relevant points here, I have made [a poll on the forum](https://forum.nengo.ai/t/vote-standard-for-multiple-input-networks/120?u=seanny123). If this poll is actually premature, then I can close it until after further discussion. (:

**Comment by tbekolay** [comment]
I was hoping we'd be able to come up with some additional options, but worth seeing how the vote goes I suppose?

**Comment by bjkomer** [comment]
Can we add Option 3 to that poll? I still prefer that one to the other two

**Comment by jgosmann** [comment]
Option 3 would be
* `input` (node) for single input network
* `inputs` (list of nodes) for multi input networks with arbitrary order
* `input_left`, `input_right` etc. for named inputs
?

**Comment by jgosmann** [comment]
I might actually favour that variant.

With regards to the potential slicing confusion with lists: If one tried to connect to the list, it would give an error (and we could make it an informative error). This makes me think that it might not be too bad.

**Comment by Seanny123** [comment]
I added option 3 to the poll and [made a new topic](https://forum.nengo.ai/t/vote-standard-for-multiple-input-networks/121?u=seanny123). Sorry Brent. <3

**Comment by hunse** [comment]
The thing that seems strange about Option 3 to me is that (compared with Option 1) we replace the dictionary with individual attributes, but leave the list there. It seems like a weird half-way point.

> With regards to the potential slicing confusion with lists: If one tried to connect to the list, it would give an error (and we could make it an informative error). This makes me think that it might not be too bad.

I would argue that good code isn't just about avoiding errors, it's about being able to look at a piece of code and know immediately what it's doing without running it. And I think that the list syntax obscures that, because we use the same syntax for objectview slicing. So if I see `net.input[0]`, is that a network that has one input node that I'm getting the first dimension of, or multiple input nodes and I'm getting the first one? It's not immediately apparent (unless you know that we use "inputs" with an 's' for multiple inputs, but that's a very subtle difference).

Also, we're talking about a standard for our core networks here, which I think never have more than two inputs. So it doesn't seem necessary to have the full power of a list. Also, the names `input_a` and `input_b` are very similar to what we currently have in most (all?) two-input networks, so it's an easy switch.

**Comment by tcstewar** [comment]
> So if I see net.input[0], is that a network that has one input node that I'm getting the first dimension of, or multiple input nodes and I'm getting the first one?

Ooo...  that's a very good point.  Yeah, that makes me step even farther back from the list approach.

Also, I think I'd argue that CircularConvolution isn't an example of a "multi-input network with arbitrary order", due to the ```invert_a``` and ```invert_b``` flags.  So it might be that the only example we have for the list approach is the Product network.

**Comment by jgosmann** [comment]
From the vote it seems we will go with option 2?

1. `net.input` as before
2. `net.input_a`, `net.input_b` or possibly `net.input_1`, `net.input_2`
3. `net.input_<name>`

We could still discuss the excat names to use, but I think it's best to stick with `net.input_a` and `net.input_b` because that's the most consistent with what we're doing right now. For the matrix multiplication network (for nengo_extras), though, I will use either `net.input_left` and `net.input_right` or `net.input_lhs` and `net.input_rhs` to make the order of multiplication clearer. I don't think this is required for the circular convolution where the order only matter when inverting exactly one input where this inversion should be clear from the `invert_[ab]=True` argument.

Any preferences for `left`/`right` vs. `lhs`/`rhs`? (lhs = left-hand side, rhs = right-hand side; more commonly used to denote the sides of equal signs, but not unheard of for infix operators)

**Comment by tbekolay** [comment]
> Any preferences for left/right vs. lhs/rhs?

I often use left/right, so that would be my preference. I forget where I picked up that convention, but rest assured I did not come up with it myself!

**Comment by Seanny123** [comment]
I also prefer `left` and `right`.

**Comment by drasmuss** [comment]
Done in #1179 and #1296
