### ISSUE TITLE
Move SPA gate and channel to target module

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo#894]
Currently the gates and channels created for actions that require them are placed in the thalamus itself. This seems to suggest a higher connectivity/bandwidth between cortex/thalamus that I think is expected.  These could instead go in the target modules of those connections, having things depend more on cortical-cortical connections that are mediated by thalamus.

This does not change any models, it just places elements in different places.

**Comment by Seanny123** [comment]
Does this imply just taking these things out of the thalamus or putting them into somewhere else as well?

**Comment by celiasmith** [comment]
Yes, moving them into cortex. @tcstewar had some ideas about how to accomplish this, but basically making them go into the containing network of the target of the action was the plan.  this would make 'Cortical' unnecessary, use that network structure, and allow functions on State to take care of the connections.

**Comment by s72sue** [comment]
I am wondering what the purpose of the bias node in the thalamus is, and where does this node get created?

**Comment by s72sue** [comment]
Figured it out, bias node basically assists in routing and gets created in nengo.networks.Thalamus. 
@celiasmith, I agree that the channels should be moved to the target module, however does moving the gates make much difference?

(a) Following is what moving only the channels looks like in the GUI:
![channels shifted](https://cloud.githubusercontent.com/assets/12284191/11194660/64a125b8-8c7b-11e5-97cb-fe33c9ce1826.png)

(b) and following is what moving both channel and the gates looks like:
![channels and gate shifted](https://cloud.githubusercontent.com/assets/12284191/11194664/6b0d7e4c-8c7b-11e5-84d8-5642300a5a2c.png)
(b)  looks a bit confusing because there are two connections from thalamus to each of the components in the cortex. Keeping the gates in thalamus (as shown in (a) ) makes it look a bit more clear.

**Comment by xchoo** [comment]
The thalamus bias node can be spilt up and relocated into each of the target networks.

**Comment by s72sue** [comment]
Okay, I moved the gate, channel and the bias nodes to the target module. 
However, the connections from thalamus to cortex show up only when I double click the thalamus. @tcstewar, can this be fixed on the nengo_gui side, or should I be doing the restructuring in a different way? 
![image](https://cloud.githubusercontent.com/assets/12284191/11328641/6c589daa-915c-11e5-91a4-db36a7486d30.png)

**Comment by Seanny123** [comment]
The reason you can't see the connections is because you made the connections in the Thalamus context. If you make them outside of the context you should be able to see them. If that sentence didn't make sense to you, msg me and I'll show you in your code.

**Comment by s72sue** [comment]
Gotcha...thanks!

**Comment by s72sue** [comment]
Do we have any example which uses `add_conv_effect` method (i.e, an example which sets an action to combine two sources and send to the target)? If not, I will create my own.

**Comment by Seanny123** [comment]
There should be some in the tests

**Comment by Seanny123** [comment]
Resolved via #906
