### ISSUE TITLE
spa.SPA should only accept a string as a label

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#902]
I accidentally passed in a vocab and everything proceeded as normal.

**Comment by jgosmann** [comment]
This is not a SPA problem, but affects all `nengo.Networks` because the label is just passed through to the `nengo.Network`. Whatever you pass in will get converted to a string. Maybe we should require it to be a string in the first place? I'm fine either way.

Anyways, as this is not SPA specific this will *not* be fixed in new-spa. :crying_cat_face:

**Comment by jgosmann** [comment]
Kind of a duplicate of #1275 which has finally been fixed #1277. Seems like this was more widespread that it seemed.
