### ISSUE TITLE
iPython learning notebooks need to be update with new syntax

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#910]
The learning connection syntax has changed, but the iPython notebook examples do not reflect this.

**Comment by tbekolay** [comment]
I believe they have been updated ([e.g.](https://github.com/nengo/nengo/blob/master/examples/learning/learn_product.ipynb)). If you're looking at the docs at https://pythonhosted.org/nengo, it's because those docs are for the currently released version (2.0.2) not the development version. Eventually we'll have both available, but for now we assume most people will use a stable release.

**Comment by Seanny123** [comment]
Aw jeez, I didn't realise pythonhosted was synced with the release, but
that makes sense.
