### ISSUE TITLE
Positional arguments in spa.State

### ISSUE THREAD

**Issue by ikajic** [nengo/nengo#912]
This doesn't produce any warnings or errors and it can be very confusing:

```
spa.State(1, 2, 3)
```

In the `spa.State` constructor, only the first parameter is positional and the rest are keyword arguments. Therefore, if a user attempts to treat keyword arguments as positional they should at least be warned so they know that these arguments are discarded (my guess of what happens).

**Comment by tbekolay** [comment]
Unfortunately, this is a bit of a quirk of Python that we can't do much about ourselves -- at least not in Python 2.

Python assumes that additional arguments past the explicitly positional arguments correspond to the keyword argument of your function, in the order that they're defined. Since `spa.State.__init__` has the function signature

```python
def __init__(self, dimensions, subdimensions=16, neurons_per_dimension=50,
             feedback=0.0, feedback_synapse=0.1, vocab=None, label=None,
             seed=None, add_to_container=None):
```

calling `spa.State(1, 2, 3)` is equivalent to calling `spa.State(1, subdimensions=2, neurons_per_dimension=3)`. I can definitely see why this is confusing. So do the Python developers -- in Python 3 they added some syntax to differentiate between keyword arguments that can be specified positionally, and those that must be passed as keyword arguments. If we did that for `spa.State.__init__`, it would look like

```python
def __init__(self, dimensions, *, subdimensions=16, neurons_per_dimension=50,
             feedback=0.0, feedback_synapse=0.1, vocab=None, label=None,
             seed=None, add_to_container=None):
```

and calling `spa.State(1, 2, 3)` would raise an error.

Unfortunately, this is a Python 3 only feature, and since it changes the grammar of Python, it won't ever be backported to Python 2. So, it's something that we can only take advantage of if we maintain separate Python 2 and 3 codebases, which is quite a pain.

**Comment by ikajic** [comment]
Right, thanks for explaining! Given that, I still wonder if there is a way to make it less confusing. I guess the example I gave was not the best, since some users really might want to do that.
I guess this is closer to what I had in mind:
```
spa.State(1, 'text')
```
what happens in that case? Is 'text' just going to be ignored?

**Comment by tbekolay** [comment]
Arguments are never ignored, Python attempts to use them as though you mean to do `spa.State(1, 'text')`. As such, it will continue until a string is unexpected and causes an error. I think that would happen [pretty quickly](https://github.com/nengo/nengo/blob/master/nengo/spa/state.py#L46) for `spa.State`, but that's not always true; it could even run completely unnoticed until you notice the network isn't running correctly. This is essentially the tradeoff with dynamic languages: it's flexible, and you can do a lot with few characters. But that means you can do a lot that you didn't mean to.

We tried to add some additional validation in the core Nengo objects with the parameters system; see [`Ensemble`](https://github.com/nengo/nengo/blob/master/nengo/ensemble.py#L53), for example. We do sanity checking on most parameters of the Nengo objects. Something similar could be done for SPA modules as well, though the parameter / config system is tricky to use.

**Comment by ikajic** [comment]
Oh, gosh, now I finally understand what happened in my case! So, this is what I've done:
```
spa.State(dim, vocab)
```
and `min(vocab, subdimensions)` in `state.py` evaluated to `subdimensions` so that's why my simulation was running perfectly fine, but the vocabulary just "disappeared". So even for `min(text, subdimensions)` it would return the default value in `subdimensions`.

**Comment by xchoo** [comment]
Hmmm. We've encountered this issue before... #902 #884

**Comment by hunse** [comment]
Parameters are set up so they can be used outside the config system, too, see e.g. `processes.py`. There's no reason the same couldn't be done here to add some validation.

**Comment by jgosmann** [comment]
Note: Future versions of SPA might use the config systems and thus get more validation of the arguments for free.

**Comment by tcstewar** [comment]
I just ran into this bug again, in code that was written as

```python
spa.State(256, vocab)
```

but should have been

```python
spa.State(256, vocab=vocab)
```

I think if we just check that the ```subdimensions``` argument is a positive integer, that'd be quite handy.

It was especially annoying in this case since it interpreted it as ```subdimensions=256```, which meant it tried to create an ensemble with 256*50=12800 neurons, and then solve for decoders, which grinds the computer to a halt as it chews up all available memory.

**Comment by jgosmann** [comment]
As I said before:

> Note: Future versions of SPA might use the config systems and thus get more validation of the arguments for free.

So I would encourage people to review #1137 so that work on the new SPA can move forward.

Of course this would also easily be fixed in the current SPA. So if anyone wants to do that, go ahead.

**Comment by jgosmann** [comment]
I think this should be resolved in new-spa-overhaul. There `spa.State` does not accept separate `dimensions` and `vocab` arguments. There is only a `vocab` argument that is allowed to be an integer. This should avoid problems of `dimensions` not matching the `vocab.dimensions`. Furthermore, thanks to the config system there is now more validation on the arguments (you get an error trying to pass a vocab to an integer argument).

Of course there are still situations where one could mess things up (e.g. swap order of dimensions and subdimensions), but I'd say there is no way to catch every potential mistake.
