### ISSUE TITLE
Hypersphere teminology

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#923]
Currently, the `UniformHypersphere` distribution accepts a `surface=False` argument. According to both Wolfram and Wikipedia, a [Hypersphere](http://mathworld.wolfram.com/Hypersphere.html) is _always_ the surface, while a [Ball](http://mathworld.wolfram.com/Ball.html) (a.k.a. n-Disk) is what we have erroneously been calling a sphere (and is the default). It may be too late to change this, so perhaps we should make this clear in the documentation? Or, at the very least, keep this note in mind for any time we're talking about these things to people.

**Comment by hunse** [comment]
Well, they hypersphere is just the generalization of the sphere, and it makes sense to talk about either the volume or the surface of a hypersphere. You're right, though, the sphere is defined by its surface, so UniformHypersphere is a bit misleading, especially because `surface` defaults to `False`. I wish we'd thought of this originally, UniformBall is a much nicer name :) The documentation is definitely lacking; I think I can make it better.

**Comment by xchoo** [comment]
UniformHyperball* 
:smile:

**Comment by arvoelke** [comment]
Related note: In #768 we mentioned we should use `ppf` instead of `invcdf` to be consistent with `scipy.stats`. Likewise, noting that `rvs` should be used instead of `sample` to be consistent as well.

**Comment by hunse** [comment]
I don't think we should adopt the whole Scipy interface for distributions. I think `sample` is a much more descriptive, intuitive, and sensible name than `rvs` (why is it even called that?). How many of our users are going to be familiar with the Scipy interface? When would we need to substitute one of our distributions in for a Scipy one? Also, I think "only missing method" is a bit misleading, since we don't require things like `ppf` to be implemented for our distributions; the only one that we guarantee is `sample`, I think.

**Comment by arvoelke** [comment]
For context, there's a library that I'm using to pick encoders so that they are "uniformly scattered". It takes arbitrary `scipy.stats` distributions, but only seems to require `ppf` and `rvs`. The adoption is certainly not necessary. It just would have been super cool if it had worked out of the box, rather than having to monkey-patch the `rvs` for our existing beta distributions. I'll talk about this more at the Jan 15 meeting.
