### ISSUE TITLE
spa.State does not correctly represent high dimensional orthogonal vectors

### ISSUE THREAD

**Issue by ikajic** [nengo/nengo#925]
When working with orthogonal semantic pointers, the `spa.State` module misrepresents the semantic pointers at the output.
Minimal example:

``` python
import nengo
from nengo import spa

D = 64
vocab = spa.Vocabulary(D, randomize=False)
vocab.parse('A')

with spa.SPA('Net') as model:
    model.state = spa.State(D, vocab=vocab)

    model.inp = spa.Input(state='A')
```

To see what happens, look at the semantic pointer plot for `state` in GUI and try increasing D (e.g. 512). As D increases the representation of A becomes more dissimilar to the input vector. The reason for this lies in the way the radius is set for individual ensembles in `state`, which is optimized for random vectors but not for orthogonal, where the represented radius needs to stay 1.

**Comment by tcstewar** [comment]
Oops...  good point.

There are a couple workarounds for this situation...  the easiest is to set the radius yourself:

```python
for ens in model.state.all_ensembles:
        ens.radius=1
```

Another thing you might want to try is just increasing the subdimensions to 64....  that'll help mitigate this effect (but not completely have it go away), at the cost of having larger ensembles (3,200 neurons, rather than 800).  With a decent numpy install 3200 shouldn't be too bad....  and I think we might even be able to go higher....

**Comment by jgosmann** [comment]
Maybe I'm mistaken (it's late in my timezone), but I believe you cannot set the radius because of [this](https://github.com/nengo/nengo/blob/master/nengo/spa/state.py#L57) and [this](https://github.com/nengo/nengo/blob/master/nengo/networks/ensemblearray.py#L57) line.

The larger ensemble *might* actually be faster to simulate, but will take longer to build.

**Comment by jgosmann** [comment]
> Maybe I'm mistaken (it's late in my timezone), but I believe you cannot set the radius because of this and this line.

To clarify: You can set the radius, but it won't have an effect.

**Comment by tcstewar** [comment]
> To clarify: You can set the radius, but it won't have an effect.

It works fine if you set it yourself, though:

```python
with spa.SPA('Net') as model:
    model.state = spa.State(D, vocab=vocab)
    for ens in model.state.all_ensembles:
        ens.radius = 1
```

That's what I meant by my suggestion...  I'm pretty sure spa.State *shouldn't* have an option to set the radius, as I don't think this is a particularly common use case.  Alternatively, it could inspect the vocab argument and see if it is orthoganal and change its scaling accordingly, but that might be a bit too magic....

**Comment by xchoo** [comment]
Why are you of the opinion that spa.State not have an option to set the radius? While the orthogonal vector use-case is pretty rare, it is an option when creating a vocabulary, and the behaviour of spa.State deteriorates non-intuitively when used with an orthogonal vector vocabulary (more dimensions gives you lower accuracy and performance).

And also, why not inspect the vocabulary to determine the radius? It is currently what we do to determine the radius of the internal ensembles (which also really only works for SubD > 8).

**Comment by tcstewar** [comment]
> Why are you of the opinion that spa.State not have an option to set the radius? While the orthogonal vector use-case is pretty rare, it is an option when creating a vocabulary, and the behaviour of spa.State deteriorates non-intuitively when used with an orthogonal vector vocabulary (more dimensions gives you lower accuracy and performance).

I could see adding an option to handle the orthogonal case, but that's different from having an option to set the radius.  I don't think we should have an option to set the radius on a spa.State for the same reason that I don't think we should have an option to set the radius on the spa.Vocabulary -- it's much to rare a use case, and anyone who needs it has to understand pretty much all the internals of a spa.State anyway, so they may as well do it manually like in the example I posted above.

> And also, why not inspect the vocabulary to determine the radius? It is currently what we do to determine the radius of the internal ensembles (which also really only works for SubD > 8).

I think I'm agreeing with you here that this is an option... that sounds like what I meant to say with inspecting the vocab argument.  I'm just cautious about adding new features.  :)

**Comment by arvoelke** [comment]
There seem to be multiple ways to address this. One approach that might get more to the root would be to change how `randomize=False` works to instead produce a random orthogonal matrix (that's really what we want, right?). This can be done very easily by calling `np.linalg.qr` on a set of randomly chosen vectors. The benefit of doing it this way is the vectors would be drawn from the same distribution in both cases, and so we don't have to worry about handling different cases as a consequence of getting these different statistics in the coefficients (for the radius, evaluation points, intercepts, etc...).

**Comment by xchoo** [comment]
Does that method also handle adding additional vectors to the vocabulary while maintaining the orthogonality constraint?

**Comment by xchoo** [comment]
Also, in that case, I'd rename the parameter from "randomize" to "orthogonal"

**Comment by arvoelke** [comment]
Since the dimensionality is fixed, you could just pay the small cost of generating the square matrix to begin with and taking only the columns that you need. Alternatively, the lazy way of doing it is just Gram-Schmidt.

**Comment by xchoo** [comment]
Hmmm. Yeah. That'll work.

**Comment by tcstewar** [comment]
That'd definitely be a neat new option to add....  I do think there's still a place for having an option to give axis-aligned vectors, but the "orthogonal" option would cover most of what "randomize=False" covers now.

**Comment by jgosmann** [comment]
> It works fine if you set it yourself, though:

Yes, my mind somehow parsed the code you provided as adjusting the config. :tired_face:

I wonder, whether setting the radius in this (your) way is obvious enough. I wanted to set the radius before (probably related to spaopt experimentation) and I did not think of this solution.

> This can be done very easily by calling np.linalg.qr on a set of randomly chosen vectors.

Not all random orthogonal matrices are made equal. I can't recall, but the distribution of vector components with QR factorization might not be the best. [What I found to work best is SVD.](https://github.com/ctn-waterloo/summerschool2015/blob/workingmemory/workingmemory/Encode%20similarity%20structure.ipynb) But actually you neither need QR nor SVD factorization. All you need is to create a random orthonormal projection matrix in the right way:

```python
projection = np.random.randn(d, d)
projection /= np.linalg.norm(projection, axis=1)[:, None]

# orthogonalize
for i in range(1, d):
    projection[i] -= np.dot(projection[:i].T, np.dot(projection[:i], projection[i]))
    projection[i] /= np.linalg.norm(projection[i])
```

**Comment by arvoelke** [comment]
The snippet above is actually just precisely Gram-Schmidt, which is an algorithm for [QR-decomposition](https://en.wikipedia.org/wiki/QR_decomposition#Using_the_Gram.E2.80.93Schmidt_process). Unfortunately, it seems as though `np.linalg.qr` uses householder reflections, and so the results aren't identical (namely, there is an asymmetric blip near 0). There may be a way to reconcile this difference, but in the mean time Gram-Schmidt should work well.

**Comment by arvoelke** [comment]
aaand FYI, you can also do this with a slick one-liner ([source](https://en.wikipedia.org/wiki/Orthogonal_matrix#Nearest_orthogonal_matrix)), although probably not since it requires scipy (just for fun):

```
def nearest(d):
    from scipy.linalg import sqrtm
    p = nengo.dists.UniformHypersphere(surface=False).sample(d, d)
    return np.dot(p, np.linalg.inv(sqrtm(np.dot(p.T, p))))
```

And an image showing that both methods do the right thing:
![qr](http://i.imgur.com/c0XZPo5.png)

**Comment by hunse** [comment]
You can do that matrix square root with a Cholesky decomposition, which is in Numpy (in fact we use it for decoder solving).

**Comment by jgosmann** [comment]
Cholesky decompesition doesn't work well because you get a triangular matrix and that changes the distribution of the vector components.

**Comment by arvoelke** [comment]
I believe Eric meant that one can use the decomposition to compute `sqrtm`, to bypass the need for scipy that I mentioned.

However... you can actually just use the SVD instead to get the transpose of the previous snippet (so... the exact same thing). It's also even more slick! This is now my preferred method (and I've verified that it gives the correct distribution as shown in the previous image):

```
def nearest(d):
    p = nengo.dists.UniformHypersphere(surface=True).sample(d, d)
    u, s, v = np.linalg.svd(p)
    return np.dot(u, v)
```

**Comment by jgosmann** [comment]
I can do an even shorter one-liner: ;)
```python
np.dot(*np.linalg.svd(nengo.dists.UniformHypersphere(True).sample(d, d))[::2])
```

I also did a quick test of all the proposed methods and it seems that they all work equally well to orthogonalize a random matrix. Apparently, Gram-Schmidt can be numerically unstable, I suppose that is why it is not used by `np.linalg.qr`. (But it is possible to generate not-so-well-behaved orthogonalizations with other methods than suggested here.) The problem with Cholesky decomposition only occurs when using it to factorize a correlation matrix to encode a similarity structure in the vectors, but not when orthogonalizing the projection matrix.

**Comment by jgosmann** [comment]
I just talked with @tcstewar about this. The SPA system is essentially based on the assumption that uniformly distributed random unit vectors are used and adding good support for other distributions (e.g. orthogonal, axis aligned vectors) is not super easy. Thus, there will be no support for this in the new-spa system at first. That also means removing the `randomize` option from `Vocabulary` as it is not of much use without the support of the rest of the system. If we introduce other distributions at some point, it would probably be best to implement those as separate classes with the `Vocabulary` interface instead of adding flags like `randomize`.

**Comment by jgosmann** [comment]
Related to this I had the thought that the vocabulary should provide the SPA modules with the appropriate radius. Every SPA module will now its vocab and the vocab is basically what defines the distribution of vectors.

Unfortunately, it is not quite that simple because there might be multiple valid ways to define the appropriate radius. For the default uniform distribution one can use the current defaults, spa-opt inspired defaults, or actual radii determined by spa-opt. Maybe one wants to mix different methods in a model and in that case this should not require separate vocabs.

**Comment by jgosmann** [comment]
Closing this as this will not be implemented in core Nengo. If anyone has a strong desire for this, please open a new issue in the nengo_spa repository.
