### ISSUE TITLE
Synaptic filter 

### ISSUE THREAD

**Issue by MarcoSaku** [nengo/nengo#951]
Hi all! I am using nengo for my simulations and I would understand well how the synaptic filter is implemented. I use as neuron model the LIF. 
Here there is how is implemented the voltage update in LIF neurons: 

```
dV = -np.expm1(-dt / self.tau_rc) * (J - voltage)
voltage += dV
```

where:
`J = (np.dot(x, e)*gain + bias)`
I would understand well how is calculated the input current J.  I set the gain and the bias manually. I avoid the encoders by connecting inputs directly to the neurons. I don't know how x is calculated. In specific, I would understand how the synapse filters the input current. For example, if I set the synapse with 
`model.config[nengo.Connection].synapse = nengo.synapses.Alpha(0.005)`
I have that impulse-response function is
`alpha(t) = (t / tau) * exp(-t / tau)`
I think that this alpha(t) is used to calculate x: if yes, could anyone explain me how? 
I read some pdf about the NEF available on internet but I didn't find the solution.
Any help would be appreciated.
Thanks all.

**Comment by arvoelke** [comment]
Hi Marco. Thanks for the question. The short answer is that the impulse-response is [convolved](https://en.wikipedia.org/wiki/Convolution#Visual_explanation) with the input current `J` to produce a "filtered" (a.k.a. smoothed) current. Note that since convolution is linear, this is also equivalent to filtering `x`, or even filtering the presynaptic activities. 

The longer answer lies in the deep theory of [LTI systems](https://en.wikipedia.org/wiki/LTI_system_theory#Overview). We take the [Laplace transform](https://en.wikipedia.org/wiki/Laplace_transform) of the impulse-response, [discretize](https://en.wikipedia.org/wiki/Discretization#Discretization_of_linear_state_space_models) it, and then use the [LCCD equation](https://en.wikipedia.org/wiki/Z-transform#Linear_constant-coefficient_difference_equation) to simulate its transitions.

I can try to be a bit more specific and point you to some more resources if you have any further questions.

**Comment by MarcoSaku** [comment]
Thanks @arvoelke for the quick reply. Theoretically, I think that I have understood how the input current is filtered. I used nengo for an application for my project and I would report the "equation" of synapse filter. I try to explain well: in my report, I would like to write how the _alpha(t)_ is used in formula to filter the input current J. I think that it is into _nengo/synapse.Alpha_ but I didn't figured out well how it is computed.
Thanks for your valuable support.

**Comment by arvoelke** [comment]
Computing the convolution integral isn't as simple as evaluating the `alpha(t)` formula. An equation that you could write is <img src="http://www.sciweavers.org/tex2img.php?eq=%28J%20%5Cast%20alpha%29%28t%29&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt="(J \ast alpha)(t)" width="114" height="19" /> where `*` denotes the convolution operator. This gives the filtered version of the input current to the neuron.

As shown in the first link I sent, this is basically achieved by a weighted summation of `J`, going backwards in time, where the weights are given by the impulse-response of `alpha`. But in practice, this computation is performed using the Laplace transform <img src="http://www.sciweavers.org/tex2img.php?eq=H%28s%29%20%3D%201%2F%28%5Ctau%20s%20%2B%201%29%5E2&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt="H(s) = 1/(\tau s + 1)^2" width="153" height="21" /> as described in my "longer answer".

**Comment by MarcoSaku** [comment]
Sorry @arvoelke  I cannot read the formulas, could you kindly rewrite please? Thanks a lot

**Comment by MarcoSaku** [comment]
Now I can see, thanks a lot!

**Comment by Seanny123** [comment]
@MarcoSaku did @arvoelke's answer help you out? Is this issue now resolved?

**Comment by Seanny123** [comment]
Since this problem is apparently resolved, I'm going to go ahead and close the issue.

**Comment by tbekolay** [comment]
Also if there are any lingering unanswered questions, we now have a shiny new [forum](https://forum.nengo.ai/) for support and sharing models!
