### ISSUE TITLE
PresentInput skips first input

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo#976]
I was using the `PresentInput` process to present a series of inputs one timestep at a time, and ran into this issue.  Basically because the first time step in Nengo is `t=dt` (not `t=0`), `PresentInput` starts with the second item in the list instead of the first.  Here's a minimal example:

``` python
import nengo
import numpy as np

inputs = np.arange(10)
dt = 1e-3
with nengo.Network() as net:
    x = nengo.Node(output=nengo.processes.PresentInput(inputs, dt))
    p = nengo.Probe(x)

sim = nengo.Simulator(net, dt=dt)
sim.run_steps(5)

print(sim.data[p])
print(sim.trange())
```
prints
```
[[ 1.] [ 2.] [ 3.] [ 4.] [ 5.]]
[ 0.001  0.002  0.003  0.004  0.005]
```
(note, we never see 0).

My proposed fix would be to change the step function to:
``` python
    def step_presentinput(t):
            i = int((t-dt) / presentation_time + 1e-7)
            return inputs[i % n]
```
Would that cause any problems (or seem wrong) to you @hunse?

**Comment by hunse** [comment]
No, I don't think that would cause any problems.

I designed PresentInput to be more for things that you're presenting for a few timesteps, in which case you never lose an input, but this change does have the nice effect of each input now appearing for the same amount of time, rather than the first input appearing for one time step less. So I think this is a good change.
