### ISSUE TITLE
Copying Nengo objects

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#977]
From today's meeting, it would be nice to be able to copy Nengo object's cleanly. I think in general we want shallow copies (i.e., don't deepcopy the parameter values); deepcopies aren't necessary since everything we do to make sure we can make multiple simulators also means we don't need to do deepcopies.

Todo:
- [x] Implement `__getstate__` `__setstate__` (see [pickle-config branch](https://github.com/nengo/nengo/tree/pickle-config); ensure we don't duplicate code with `FrozenObject` which does some copy stuff)
- [x] Implement `.copy` method
  - [x] Include an `add_to_network` arg on the copy method that adds or doesn't add to current `Network.context`
- [x] Make sure it plays well with Python's `copy` module

**Comment by tbekolay** [comment]
Also, related to #941.

**Comment by jgosmann** [comment]
I started implementing this and it seems to be possible in a quite general manner. The added `copy` method on `NengoObject`s can take an `add_to_network` argument, but neither the Python `copy.copy` function can nor the unpickling functions. Should we add the object in those cases to the network or shouldn't we? Or maybe only if we are in the context of a network?

Probably we don't want to add the object always to a network (otherwise unpickling outside of a network would not be possible because it would raise an exception).

**Comment by hunse** [comment]
Yeah, I would say don't add it when unpickling. 

Maybe we shouldn't allow `copy.copy` at all? We could just have a NotImplementedError that tells people to use our `copy` method. That would make things more straightforward, and I don't think it really makes anything inconvenient, either.

**Comment by jgosmann** [comment]
I'm using `__getstate__` and `__setstate__`. I have to, to support pickling/unpickling and it gives me copying basically for free. But because of that it is not possible to raise `NotImplementedError` for the Python `copy` function. Furthermore, I'm using exactly that function in our `copy` implementation.

**Comment by hunse** [comment]
What about something like [this](https://github.com/nengo/nengo/commit/ff00ca6d8cc4a43cc1f55dc14090fd12446fff2c)?

**Comment by jgosmann** [comment]
Isn't this using a private method in the `copy` module?

**Comment by hunse** [comment]
Yep! Probably a bit strange, but I basically just took out the parts of their code that do copying if there's no `__copy__` function. Though we should check if this works in 3.x. Also, maybe better to just write all our own code to do it using `__getstate__` and `__setstate__`, which shouldn't be too hard. I just threw it together quick as a proof of concept.

**Comment by jgosmann** [comment]
To me it seems to be slightly more effort to disable Python's `copy` than it is worth. It's actually fully functional, the copy just doesn't get added to the network which might actually not to surprising (and of course in examples we would prefer `NengoObject.copy` where there is an `add_to_network` argument).

**Comment by hunse** [comment]
Yeah, I just don't want people to be confused or surprised by it not getting added to the model. I feel like on the user side, we want the default behaviour to be to add it to the network, since I think that's what users will expect. It seems strange if our `copy` does it one way and Python's `copy` does it the other.

**Comment by jgosmann** [comment]
I finished the PR. Using Python's `copy` or unpickling in the context of a network will produce a warning that the object was not added to the network. This still allows to use Python`s `copy` but the warning should make it clear that this might not have the intended effect.

**Comment by drasmuss** [comment]
Copying of Nengo objects is implemented now.
