### ISSUE TITLE
Make inverting semantic pointers more discoverable

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#990]
Ivana and I were a little surprised to learn that to invert a semantic you can just prepend the variable with `~`, for example:

```
import nengo
from nengo import spa

vo = spa.Vocabulary(16)
af = vo.parse("PANTS")
res = vo.parse("PANTS*SOCKS")*~af
print(vo.text(res))
```

This isn't easily discoverable. Would it be reasonable to create an attribute or a function such as `ptr.inv` and indicate in the doc string the `~` alternative?

**Comment by hunse** [comment]
So this all comes from the fact that the way semantic pointer *strings* are implemented, is by actually overloading all the necessary ops on the SemanticPointer class, then executing the string as a Python statement. So anything that you can do in strings you can do with the objects, too. But I agree, this isn't well documented, because I think it was basically considered a side-effect of the way we implemented the strings.

The way that we implement the `*` operator is by having a `convolve` function and calling out to it. I would advocate having this for all the operators we overload (i.e. have `add`, `subtract`, and `inv` functions as well). That way the user can either use that function or the operator.

The other option is just to better document that all these operators are overloaded, so you can use them. That would be okay, too, IMO.

**Comment by Seanny123** [comment]
When you say "better document" what do you envision?

**Comment by arvoelke** [comment]
Might I suggest adding an example notebook to the [SPA examples](https://pythonhosted.org/nengo/examples.html#semantic-pointer-architecture) covering the SPA language itself? Could be used to discuss "actions" and "effects" in the context of Basal/Thalamus/Cortical networks, by defining the syntax and semantics of this custom language.

**Comment by jgosmann** [comment]
Moved to nengo/nengo_spa#19.
