### ISSUE TITLE
SP plot: similarity values in legends appear only after running the simulation

### ISSUE THREAD

**Issue by ikajic** [nengo/nengo#992]
The similarity values in the legend (numbers next to the semantic pointer labels) of a semantic pointer plot  appear only after I run the simulation for the first time, and then press the simulation reset button (or play again). They never appear right away. 

I have observed this with two different browsers on my machine (and my laptop), so I have been wondering if anyone else can reproduce this?

**Comment by jgosmann** [comment]
Not sure if that's a bug or a feature, but before running the simulation there is no data on which a similarity could be computed (one could assume 0, but one could equally well argue that it is undefined)

**Comment by ikajic** [comment]
The numbers I'm talking about are read-outs from the SP plot and they are computed real time. So at t=0 it should be 0 and after that whatever the plot is showing. When you press the play button first time the plot displays the similarities but the legend doesn't reflect those (there are just labels)

**Comment by jgosmann** [comment]
Maybe we should discuss this in person. (Or an image might help.)

**Comment by jgosmann** [comment]
I still can't reproduce it, but I understand now what the bug is.

The steps to reproduce would be (if the bug appears on your machine which it might not):

1. Start nengo_gui and open a SPA model
2. Add a semantic pointer plot. (Labels will show no similarities; expected as the simulation hasn't started.)
3. Run the simulation. While the simulation is running, the similarities might not be shown (perfectly reproducible on Ivana's computers, perfectly not reproducible on my computers)
4. Stop and restart the simulation. Now the similarities are shown.

**Comment by tbekolay** [comment]
I can reproduce the bug given those steps! What branches are you on @jgosmann?

Also, should we move this issue to https://github.com/nengo/nengo_gui ?

**Comment by jgosmann** [comment]
> What branches are you on @jgosmann?

both current master (nengo: 8158ea2088, nengo_gui: 47500695ad)

> Also, should we move this issue to https://github.com/nengo/nengo_gui ?

I would say so, I didn't realize that this is on the Nengo issue tracker.

**Comment by jgosmann** [comment]
Can someone of you try this with the nengo_gui `server-refactor` branch?

**Comment by jgosmann** [comment]
(moved to nengo/nengo_gui#709)
